# Generated by Django 6.0.1 on 2026-05-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='edited_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=10)),
                ('target_id', models.CharField(max_length=36)),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('edited_at', models.BigIntegerField()),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits_made', to='api.user')),
            ],
            options={
                'db_table': 'edit_history',
                'ordering': ['edited_at'],
            },
        ),
    ]
