# Generated by Django 5.2.14 on 2026-05-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_badge_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='edithistory',
            new_name='edit_histor_target__ea3ea5_idx',
            old_name='api_edithistory_target_idx',
        ),
        migrations.RenameIndex(
            model_name='fcmtoken',
            new_name='fcm_tokens_user_id_204a04_idx',
            old_name='api_fcmtoken_user_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='follows_followi_dcb467_idx',
            old_name='api_follow_following_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='follows_followe_ca9b09_idx',
            old_name='api_follow_follower_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_user_id_dfa368_idx',
            old_name='api_post_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_categor_c9aadc_idx',
            old_name='api_post_category_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_is_arch_d30fed_idx',
            old_name='api_post_archived_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_thumbs__f11b42_idx',
            old_name='api_post_thumbs_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='replies_post_id_839534_idx',
            old_name='api_reply_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_status_d7deb7_idx',
            old_name='api_report_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_target__f1c53d_idx',
            old_name='api_report_target_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='resources_subject_9c7755_idx',
            old_name='api_resource_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='resources_grade_l_604786_idx',
            old_name='api_resource_grade_idx',
        ),
        migrations.RenameIndex(
            model_name='resource',
            new_name='resources_type_f63025_idx',
            old_name='api_resource_type_idx',
        ),
        migrations.RenameIndex(
            model_name='userphoto',
            new_name='user_photos_user_id_fd2a6f_idx',
            old_name='api_userphoto_user_idx',
        ),
    ]
