# Generated by Django 5.2.14 on 2026-05-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260531_2233'),
        ('api', '0017_notifications'),
    ]

    operations = [
    ]
