# Generated by Django 5.2.14 on 2026-06-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_resource_comments_and_likes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='bookmarks_user_id_76f91f_idx',
            old_name='api_bookmark_user_type_idx',
        ),
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='bookmarks_target__eba581_idx',
            old_name='api_bookmark_target_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_2d3764_idx',
            old_name='notif_recip_time_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_dde14f_idx',
            old_name='notif_recip_unread_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_target__031211_idx',
            old_name='notif_target_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecomment',
            new_name='resource_co_resourc_2b3498_idx',
            old_name='resource_comment_res_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecomment',
            new_name='resource_co_parent__d21096_idx',
            old_name='resource_comment_parent_idx',
        ),
        migrations.AddField(
            model_name='resource',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='source_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='source_type',
            field=models.CharField(choices=[('admin', 'Added by Admin'), ('user', 'User Upload'), ('anonymous', 'Anonymous Upload'), ('external', 'External Source')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='source_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to='api.user'),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='api_url',
            field=models.TextField(default='https://chat.qwen.ai/api/v2'),
        ),
        migrations.AlterField(
            model_name='resourcecommentlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resourcelike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-like_count'], name='resources_like_co_ba51c0_idx'),
        ),
    ]
