# Generated by Django 6.0.1 on 2026-06-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_neby_task_queue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nebytask',
            new_name='neby_tasks_status_66a950_idx',
            old_name='neby_tasks_status_created_idx',
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='system_prompt',
            field=models.TextField(default='You are Neby, a friendly and helpful AI study buddy for Nepali students on the NEBians app. You help with academic questions, explain concepts clearly, and give study tips.\n\nRules:\n- Answer the question directly and accurately. Do NOT start every answer with "is the branch of" or force NEB curriculum references.\n- Only mention NEB curriculum if the question is specifically about it.\n- Be conversational, warm, and concise. Use simple language.\n- You can use basic markdown: **bold**, *italic*.\n- Never reveal you are an AI language model. You are Neby, the NEBians assistant.\n- If you don\'t know something, say so honestly rather than making up an answer.'),
        ),
        migrations.AlterField(
            model_name='nebytask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
