# Generated by Django 6.0.1 on 2026-06-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_neby_tasks_status_created_idx_neby_tasks_status_66a950_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('grade_level', models.CharField(blank=True, default='', max_length=20)),
                ('requester_name', models.CharField(blank=True, default='', max_length=100)),
                ('requester_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=10)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.BigIntegerField()),
                ('fulfilled_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'resource_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequestUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'resource_request_upvotes',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewed_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resources', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['approval_status'], name='resources_approva_0e821e_idx'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilling_requests', to='api.resource'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_requests', to='api.user'),
        ),
        migrations.AddField(
            model_name='resourcerequestupvote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='api.resourcerequest'),
        ),
        migrations.AddField(
            model_name='resourcerequestupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_upvotes', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['status', '-upvote_count'], name='resource_re_status_a0bdef_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['subject'], name='resource_re_subject_f1cc53_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['grade_level'], name='resource_re_grade_l_c545b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcerequestupvote',
            unique_together={('request', 'user')},
        ),
    ]
