# Generated by Django 6.0.1 on 2026-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_resource_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('Final', 'Final Exam'), ('Midterm', 'Midterm / Internal'), ('Board', 'Board Exam'), ('Entrance', 'Entrance Exam'), ('SEE', 'SEE Exam'), ('Mock', 'Mock / Model'), ('Assignment', 'Assignment / Project'), ('Notes', 'Class Notes'), ('Reference', 'Reference Material'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='pradesh',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='program',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='exam_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='pradesh',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='program',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='grade_level',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(default='PDF', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='grade_level',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['faculty'], name='resources_faculty_bff3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['exam_type'], name='resources_exam_ty_a7e2ff_idx'),
        ),
    ]
