# Generated by Django 6.0.1 on 2026-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_resource_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='school',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='school',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
