# Generated by Django 6.0.1 on 2026-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_school_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('post', 'Post'), ('reply', 'Reply'), ('user', 'User'), ('resource', 'Resource'), ('resource_comment', 'Resource Comment'), ('system', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like_post', 'Liked your post'), ('like_reply', 'Liked your reply'), ('like_resource', 'Liked your resource'), ('like_resource_comment', 'Liked your comment on a resource'), ('reply', 'Replied to your post'), ('reply_reply', 'Replied to your comment'), ('resource_comment', 'Commented on your resource'), ('resource_comment_reply', 'Replied to your comment on a resource'), ('follow', 'Started following you'), ('mention', 'Mentioned you'), ('resource_approved', 'Your resource was approved'), ('resource_rejected', 'Your resource was rejected'), ('system', 'System notification')], max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
