# Generated by Django 6.0.1 on 2026-06-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_auth_tokens'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userauthtoken',
            new_name='user_auth_t_user_id_a801f0_idx',
            old_name='user_auth_t_user_id_e4923b_idx',
        ),
        migrations.RenameIndex(
            model_name='userauthtoken',
            new_name='user_auth_t_token_h_b859c5_idx',
            old_name='user_auth_t_token_h_060eb2_idx',
        ),
    ]
