# Generated by Django 6.0.1 on 2026-06-04
# Cleaned up: removed spurious arena index renames that may not exist on production

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_botconfig_multi_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botconfig',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nebytask',
            name='bot_config',
            field=models.ForeignKey(blank=True, db_column='bot_config_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.botconfig'),
        ),
    ]