# Generated by Django 5.2.14 on 2026-06-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_arena_index_ignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakedownRequest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('infringing_url', models.TextField()),
                ('proof_of_ownership', models.TextField()),
                ('statement_good_faith', models.BooleanField(default=False)),
                ('statement_accurate', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('created_at', models.BigIntegerField()),
                ('resolved_at', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_takedowns', to='api.user')),
            ],
            options={
                'db_table': 'takedown_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
