# Generated by Django 5.2.14 on 2026-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_takedownrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_lead',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='upload_group_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
