# Generated by Django 5.2.14 on 2026-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_post_reply_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusContent',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('grade_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('chapter_id', models.CharField(max_length=100)),
                ('chapter_title', models.CharField(max_length=200)),
                ('text_content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Syllabus Content',
                'verbose_name_plural': 'Syllabus Contents',
                'db_table': 'syllabus_content',
                'ordering': ['grade_level', 'subject', 'order'],
            },
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_view_co_7fa22a_idx',
            old_name='api_post_view_co_idx',
        ),
    ]
