# Generated by Django 6.0.1 on 2026-06-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_syllabuscontent_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('institution', 'Institution')], db_index=True, default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_subjects',
            field=models.TextField(blank=True, default=''),
        ),
    ]
