# Generated by Django 5.2.14 on 2026-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_add_user_role_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('institution', 'Institution'), ('explorer', 'Explorer')], db_index=True, default='student', max_length=20),
        ),
    ]
