# Generated by Django 6.0.1 on 2026-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
