# Generated by Django 6.0.1 on 2026-06-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_add_teacher_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, default='', max_length=300)),
                ('duration_ms', models.BigIntegerField(choices=[(0, 'No expiry'), (3600000, '1 hour'), (86400000, '24 hours'), (259200000, '3 days'), (604800000, '7 days')], default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.BigIntegerField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='api.post')),
            ],
            options={
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.poll')),
            ],
            options={
                'db_table': 'poll_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='api.user')),
            ],
            options={
                'db_table': 'poll_votes',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.BigIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.post')),
            ],
            options={
                'db_table': 'post_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll_id', 'order'], name='poll_option_poll_id_3f4c2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('poll', 'user')},
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post_id', 'order'], name='post_images_post_id_8637ba_idx'),
        ),
    ]
