# Generated by Django 6.0.1 on 2026-06-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_add_post_images_and_polls'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poll',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('voting', 'Voting'), ('mcq', 'MCQ Quiz')], default='voting', max_length=10),
        ),
        migrations.AddField(
            model_name='polloption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll_id', 'user_id'], name='poll_votes_poll_id_2d8a90_idx'),
        ),
    ]
