# Generated by Django 6.0.1 on 2026-06-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_arena_session_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('file_url', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=200)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_generated_at', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_documents', to='api.user')),
            ],
            options={
                'db_table': 'study_documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyFlashcard',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('card_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.studydocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_flashcards', to='api.user')),
            ],
            options={
                'db_table': 'study_flashcards',
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='StudyFlashcardReview',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('confidence', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.BigIntegerField(default=0)),
                ('next_review_at', models.BigIntegerField(default=0)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.studyflashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_flashcard_reviews', to='api.user')),
            ],
            options={
                'db_table': 'study_flashcard_reviews',
            },
        ),
        migrations.CreateModel(
            name='StudyQuiz',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.studydocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_quizzes', to='api.user')),
            ],
            options={
                'db_table': 'study_quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyQuizAttempt',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('answers', models.TextField(blank=True, default='')),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.studyquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_quiz_attempts', to='api.user')),
            ],
            options={
                'db_table': 'study_quiz_attempts',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyQuizQuestion',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField(blank=True, default='')),
                ('option_b', models.TextField(blank=True, default='')),
                ('option_c', models.TextField(blank=True, default='')),
                ('option_d', models.TextField(blank=True, default='')),
                ('correct_answer', models.CharField(default='A', max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.studyquiz')),
            ],
            options={
                'db_table': 'study_quiz_questions',
                'ordering': ['question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='studydocument',
            index=models.Index(fields=['user', '-updated_at'], name='study_docum_user_id_4ea7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='studyflashcardreview',
            index=models.Index(fields=['user', 'flashcard'], name='study_flash_user_id_0911bd_idx'),
        ),
    ]
