# Generated by Django 6.0.1 on 2026-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_study_lab_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='model',
            field=models.CharField(default='qwen3.7-plus', max_length=200),
        ),
    ]
