# Generated by Django 6.0.1 on 2026-06-11 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_provider_choices_expand'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('summary', 'Summary'), ('mindmap', 'Mindmap'), ('quiz', 'Quiz'), ('flashcard', 'Flashcard')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=12)),
                ('params', models.TextField(blank=True, default='')),
                ('result', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('started_at', models.BigIntegerField(default=0)),
                ('completed_at', models.BigIntegerField(default=0)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='api.studydocument')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='api.studyspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='api.user')),
            ],
            options={
                'db_table': 'generation_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='generation__status_166da0_idx'), models.Index(fields=['user', '-created_at'], name='generation__user_id_1a1c21_idx'), models.Index(fields=['space', 'job_type', '-created_at'], name='generation__space_i_d7acbd_idx')],
            },
        ),
    ]
