# Generated by Django 6.0.1 on 2026-06-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_generation_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.BigIntegerField()),
                ('scheduled_delete_at', models.BigIntegerField()),
                ('completed_at', models.BigIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deletions', to='api.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='api.user')),
            ],
            options={
                'db_table': 'account_deletion_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
