# Generated by production performance pass.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_create_class12_results_announcement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['status', '-created_at'], name='resreq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['requested_by', '-created_at'], name='resreq_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_archived', '-thumbs_up_count', '-created_at'], name='post_arch_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['post_id', 'is_archived', '-thumbs_up_count', 'created_at'], name='reply_post_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['user_id', '-created_at'], name='reply_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecomment',
            index=models.Index(fields=['resource_id', '-like_count', 'created_at'], name='rescomm_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecomment',
            index=models.Index(fields=['user_id', '-created_at'], name='rescomm_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='studyspace',
            index=models.Index(fields=['visibility', '-updated_at'], name='space_visibility_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='studyspace',
            index=models.Index(fields=['user', 'visibility', '-updated_at'], name='space_user_vis_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='studydocument',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='studydoc_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studydocument',
            index=models.Index(fields=['space', 'status', '-updated_at'], name='studydoc_space_status_idx'),
        ),
    ]
