# Generated by Django 6.0.1 on 2026-07-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_performance_indexes_hot_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'follow_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='followrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow_requests', to='api.user'),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_requests', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='followrequest',
            index=models.Index(fields=['receiver_id'], name='follow_requ_receive_10062a_idx'),
        ),
        migrations.AddIndex(
            model_name='followrequest',
            index=models.Index(fields=['sender_id'], name='follow_requ_sender__24211f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
