# Generated by Django 6.0.1 on 2026-07-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_followrequest_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='announcement',
                    new_name='announcemen_status_03b481_idx',
                    old_name='ann_stat_pub_idx',
                ),
                migrations.RenameIndex(
                    model_name='announcement',
                    new_name='announcemen_categor_1b56b5_idx',
                    old_name='ann_cat_stat_idx',
                ),
                migrations.RenameIndex(
                    model_name='announcement',
                    new_name='announcemen_is_pinn_05ad76_idx',
                    old_name='ann_pin_pub_idx',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='arenachatsession',
            name='provider',
            field=models.CharField(choices=[('ai4bharat', 'AI4Bharat Arena'), ('qwen', 'Qwen (chat.qwen.ai)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('eqing', 'EQing / EasyChat (chat3.eqing.tech)'), ('freegpt', 'FreeGPT (standalone.freegpt.win:3001)'), ('deepseekai', 'DeepSeek AI (deep-seek.ai)'), ('surfsense', 'SurfSense (surfsense.com)'), ('g4f', 'G4F (g4f.space / Pollinations AI)')], default='ai4bharat', max_length=20),
        ),
    ]
