# Generated by Django 5.2.14 on 2026-07-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_merge_20260707_1940'),
        ('api', '0070_pageview_and_dailystat'),
    ]

    operations = [
    ]
