# Generated by Django 6.0.1 on 2026-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_analytics_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
