# Generated by Django 6.0.1 on 2026-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_social_link_clicks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sociallink',
            new_name='social_link_user_id_d891d1_idx',
            old_name='api_social_user_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='sociallinkclick',
            new_name='social_link_user_id_b352c4_idx',
            old_name='slc_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='sociallinkclick',
            new_name='social_link_platfor_85174a_idx',
            old_name='slc_platform_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='school_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
