# Generated by Django 6.0.1 on 2026-07-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_rename_api_social_user_sort_idx_social_link_user_id_d891d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinkclick',
            name='clicker_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sociallinkclick',
            name='clicker_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sociallinkclick',
            name='clicker_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sociallinkclick',
            name='is_follower',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sociallinkclick',
            index=models.Index(fields=['is_follower'], name='social_link_is_foll_6b44c4_idx'),
        ),
    ]
