# Generated by Django 6.0.1 on 2026-07-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_remove_g4f_freegpt_deepseekai_surfsense_eqing'),
        ('api', '0104_restore_studydoc_space_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspacenote',
            name='board_content',
        ),
        migrations.RemoveField(
            model_name='studyspacenote',
            name='board_version',
        ),
        migrations.AlterField(
            model_name='arenachatsession',
            name='provider',
            field=models.CharField(choices=[('ai4bharat', 'AI4Bharat Arena'), ('qwen', 'Qwen (chat.qwen.ai)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)')], default='ai4bharat', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('ai4bharat', 'AI4Bharat Arena (Indic LLM Arena)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('custom', 'Custom OpenAI-compatible endpoint')], default='qwen', max_length=20),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.BigIntegerField(default=0)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.announcement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='api.user')),
            ],
            options={
                'db_table': 'blog_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
