# Generated by Django 5.2.14 on 2026-07-16 10:39

from django.db import migrations, models
import time

def seed_hero_backgrounds(apps, schema_editor):
    HeroBackground = apps.get_model('api', 'HeroBackground')
    now_ms = int(time.time() * 1000)
    backgrounds = [
        ("Paper Sky", "paper_sky_hero_background.svg", True, 1),
        ("Soft SaaS", "soft_saas_hero_background-pixel-perfect.svg", False, 2),
        ("Winter Himalayan", "winter_himalayan_hero_background-pixel-perfect.svg", False, 3),
        ("Pastel SaaS", "pastel_saas_hero_background-pixel-perfect.svg", False, 4),
        ("Diwali SaaS", "diwali_saas_hero_background-pixel-perfect.svg", False, 5),
        ("NEB Dashain", "neb_dashain_hero_background-pixel-perfect.svg", False, 6),
    ]
    for name, filename, is_active, sort_order in backgrounds:
        HeroBackground.objects.create(
            name=name,
            filename=filename,
            is_active=is_active,
            sort_order=sort_order,
            created_at=now_ms
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_blog_comment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'hero_backgrounds',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_hero_backgrounds),
    ]

