# Generated for the NEBians background coding agent.
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_post_view_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundAgentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(default=0)),
                ('github_login', models.CharField(blank=True, default='', max_length=255)),
                ('github_avatar_url', models.TextField(blank=True, default='')),
                ('encrypted_access_token', models.TextField(blank=True, default='')),
                ('token_scopes', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('last_validated_at', models.BigIntegerField(default=0)),
                ('revoked_at', models.BigIntegerField(default=0)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_agent_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'background_agent_credentials'},
        ),
        migrations.CreateModel(
            name='BackgroundAgentProject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('github_repo_id', models.BigIntegerField(default=0)),
                ('repo_full_name', models.CharField(max_length=255)),
                ('repo_html_url', models.TextField(blank=True, default='')),
                ('clone_url', models.TextField()),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('preferred_base_branch', models.CharField(blank=True, default='', max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('syncing', 'Syncing'), ('ready', 'Ready'), ('error', 'Error'), ('archived', 'Archived')], db_index=True, default='new', max_length=20)),
                ('mirror_path', models.TextField(blank=True, default='')),
                ('last_synced_at', models.BigIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_agent_projects', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='api.backgroundagentcredential')),
            ],
            options={'db_table': 'background_agent_projects', 'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='BackgroundAgentSession',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('goal', models.TextField()),
                ('source_branch', models.CharField(max_length=255)),
                ('work_branch', models.CharField(blank=True, default='', max_length=255)),
                ('base_sha', models.CharField(blank=True, default='', max_length=64)),
                ('head_sha', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('running', 'Running'), ('paused', 'Paused'), ('waiting', 'Waiting for input'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('control_state', models.CharField(blank=True, choices=[('', 'None'), ('pause', 'Pause'), ('stop', 'Stop')], default='', max_length=10)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_label', models.CharField(blank=True, default='Queued', max_length=255)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('max_iterations', models.PositiveIntegerField(default=30)),
                ('workspace_path', models.TextField(blank=True, default='')),
                ('agent_state', models.TextField(blank=True, default='{}')),
                ('summary', models.TextField(blank=True, default='')),
                ('final_diff', models.TextField(blank=True, default='')),
                ('changed_files', models.TextField(blank=True, default='[]')),
                ('test_summary', models.TextField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('worker_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_heartbeat_at', models.BigIntegerField(db_index=True, default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('started_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('completed_at', models.BigIntegerField(default=0)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_agent_sessions', to=settings.AUTH_USER_MODEL)),
                ('bot_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_agent_sessions', to='api.botconfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.backgroundagentproject')),
            ],
            options={'db_table': 'background_agent_sessions', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='BackgroundAgentMessage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], db_index=True, max_length=12)),
                ('content', models.TextField()),
                ('metadata', models.TextField(blank=True, default='{}')),
                ('created_at', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.backgroundagentsession')),
            ],
            options={'db_table': 'background_agent_messages', 'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='BackgroundAgentEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.TextField(blank=True, default='{}')),
                ('created_at', models.BigIntegerField(db_index=True, default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.backgroundagentsession')),
            ],
            options={'db_table': 'background_agent_events', 'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='BackgroundAgentArtifact',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('changes_zip', 'Changed files ZIP'), ('patch', 'Git patch'), ('log', 'Execution log')], db_index=True, max_length=20)),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.backgroundagentsession')),
            ],
            options={'db_table': 'background_agent_artifacts', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='BackgroundAgentAction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('push', 'Push branch'), ('open_pr', 'Open pull request'), ('refresh', 'Refresh repository'), ('artifacts', 'Rebuild artifacts')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('payload', models.TextField(blank=True, default='{}')),
                ('result', models.TextField(blank=True, default='{}')),
                ('error', models.TextField(blank=True, default='')),
                ('worker_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.BigIntegerField(default=0)),
                ('started_at', models.BigIntegerField(default=0)),
                ('completed_at', models.BigIntegerField(default=0)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_agent_actions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.backgroundagentsession')),
            ],
            options={'db_table': 'background_agent_actions', 'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='BackgroundAgentWorker',
            fields=[
                ('worker_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('process_id', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('idle', 'Idle'), ('busy', 'Busy'), ('stopping', 'Stopping')], db_index=True, default='starting', max_length=20)),
                ('current_kind', models.CharField(blank=True, default='', max_length=20)),
                ('current_id', models.CharField(blank=True, default='', max_length=36)),
                ('started_at', models.BigIntegerField(default=0)),
                ('last_heartbeat_at', models.BigIntegerField(db_index=True, default=0)),
            ],
            options={'db_table': 'background_agent_workers', 'ordering': ['worker_id']},
        ),
        migrations.AddConstraint(
            model_name='backgroundagentproject',
            constraint=models.UniqueConstraint(fields=('admin_user', 'repo_full_name'), name='uniq_bg_agent_admin_repo'),
        ),
        migrations.AddIndex(model_name='backgroundagentproject', index=models.Index(fields=['admin_user', '-updated_at'], name='bg_project_admin_updated_idx')),
        migrations.AddIndex(model_name='backgroundagentproject', index=models.Index(fields=['status', '-updated_at'], name='bg_project_status_updated_idx')),
        migrations.AddIndex(model_name='backgroundagentsession', index=models.Index(fields=['status', 'created_at'], name='bg_session_status_created_idx')),
        migrations.AddIndex(model_name='backgroundagentsession', index=models.Index(fields=['admin_user', '-created_at'], name='bg_session_admin_created_idx')),
        migrations.AddIndex(model_name='backgroundagentsession', index=models.Index(fields=['project', '-created_at'], name='bg_session_project_created_idx')),
        migrations.AddIndex(model_name='backgroundagentmessage', index=models.Index(fields=['session', 'created_at'], name='bg_message_session_created_idx')),
        migrations.AddIndex(model_name='backgroundagentevent', index=models.Index(fields=['session', 'id'], name='bg_event_session_id_idx')),
        migrations.AddConstraint(model_name='backgroundagentartifact', constraint=models.UniqueConstraint(fields=('session', 'kind'), name='uniq_bg_artifact_session_kind')),
        migrations.AddIndex(model_name='backgroundagentaction', index=models.Index(fields=['status', 'created_at'], name='bg_action_status_created_idx')),
        migrations.AddIndex(model_name='backgroundagentaction', index=models.Index(fields=['session', 'created_at'], name='bg_action_session_created_idx')),
        migrations.AddIndex(model_name='backgroundagentworker', index=models.Index(fields=['status', '-last_heartbeat_at'], name='bg_worker_status_heartbeat_idx')),
    ]
