from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0082_post_view_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingAgentProject',
            fields=[
                ('id', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('repo_owner', models.CharField(help_text='GitHub owner/org login (e.g. NikitHamal)', max_length=200)),
                ('repo_name', models.CharField(help_text='Repository name (e.g. NEB)', max_length=200)),
                ('repo_full_name', models.CharField(max_length=400)),
                ('repo_description', models.TextField(blank=True, default='')),
                ('default_branch', models.CharField(default='main', max_length=120)),
                ('repo_url', models.CharField(default='', max_length=500)),
                ('is_private', models.BooleanField(default=False)),
                ('access_token', models.TextField(help_text='GitHub OAuth access token (server-only).')),
                ('token_scope', models.CharField(default='repo', max_length=40)),
                ('github_user_login', models.CharField(blank=True, default='', max_length=120)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Optional override system prompt prepended to every session.')),
                ('agent_provider', models.CharField(blank=True, default='', help_text='Optional override AI provider (qwen/ai4bharat/inception/...).', max_length=20)),
                ('agent_model', models.CharField(blank=True, default='', max_length=200)),
                ('max_iterations', models.PositiveIntegerField(default=80, help_text='Safety cap per session.')),
                ('is_archived', models.BooleanField(default=False)),
                ('last_used_at', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('owner_user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='coding_agent_projects', to='api.user')),
            ],
            options={
                'db_table': 'coding_agent_projects',
                'ordering': ['-updated_at'],
                'unique_together': {('owner_user', 'repo_full_name')},
                'indexes': [
                    models.Index(fields=['owner_user', '-updated_at'], name='ca_proj_owner_idx'),
                    models.Index(fields=['repo_full_name'], name='ca_proj_repo_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CodingAgentSession',
            fields=[
                ('id', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', help_text='Short human label for the session.', max_length=255)),
                ('task', models.TextField(help_text='The task / goal the agent is asked to accomplish.')),
                ('branch', models.CharField(default='', help_text='Branch name the agent creates and works on.', max_length=200)),
                ('base_ref', models.CharField(default='', help_text='Commit SHA the session branched from.', max_length=120)),
                ('status', models.CharField(choices=[
                    ('queued', 'Queued'),
                    ('setup', 'Setting up'),
                    ('running', 'Running'),
                    ('paused', 'Paused'),
                    ('awaiting_input', 'Awaiting input'),
                    ('finished', 'Finished'),
                    ('failed', 'Failed'),
                    ('stopped', 'Stopped'),
                    ('pr_opened', 'PR opened'),
                ], default='queued', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('provider', models.CharField(default='', max_length=20)),
                ('model', models.CharField(default='', max_length=200)),
                ('iterations', models.PositiveIntegerField(default=0)),
                ('tool_calls_count', models.PositiveIntegerField(default=0)),
                ('input_tokens_estimate', models.PositiveIntegerField(default=0)),
                ('output_tokens_estimate', models.PositiveIntegerField(default=0)),
                ('workspace_path', models.CharField(default='', max_length=500)),
                ('last_message_id', models.CharField(blank=True, default='', max_length=36)),
                ('summary', models.TextField(blank=True, default='')),
                ('pr_url', models.CharField(blank=True, default='', max_length=500)),
                ('pr_number', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('push_state', models.CharField(blank=True, default='', max_length=20)),
                ('paused_at', models.BigIntegerField(default=0)),
                ('stopped_at', models.BigIntegerField(default=0)),
                ('finished_at', models.BigIntegerField(default=0)),
                ('last_activity_at', models.BigIntegerField(default=0)),
                ('started_at', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='sessions', to='api.codingagentproject')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='assigned_coding_sessions', to='api.user')),
            ],
            options={
                'db_table': 'coding_agent_sessions',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-priority', 'created_at'], name='ca_sess_queue_idx'),
                    models.Index(fields=['project', '-created_at'], name='ca_sess_proj_idx'),
                    models.Index(fields=['assigned_to', '-created_at'], name='ca_sess_user_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CodingAgentMessage',
            fields=[
                ('id', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[
                    ('system', 'System'),
                    ('user', 'User'),
                    ('assistant', 'Assistant'),
                    ('tool', 'Tool'),
                ], max_length=20)),
                ('kind', models.CharField(choices=[
                    ('message', 'Message'),
                    ('tool_call', 'Tool call'),
                    ('tool_result', 'Tool result'),
                    ('note', 'Note'),
                ], default='message', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=60)),
                ('tool_args_json', models.TextField(blank=True, default='')),
                ('tool_result_json', models.TextField(blank=True, default='')),
                ('tool_status', models.CharField(blank=True, default='', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='messages', to='api.codingagentsession')),
            ],
            options={
                'db_table': 'coding_agent_messages',
                'ordering': ['sequence', 'created_at'],
                'indexes': [
                    models.Index(fields=['session', 'sequence'], name='ca_msg_seq_idx'),
                    models.Index(fields=['session', '-created_at'], name='ca_msg_session_created_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CodingAgentToolCall',
            fields=[
                ('id', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('args_json', models.TextField(blank=True, default='')),
                ('result_text', models.TextField(blank=True, default='')),
                ('result_truncated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[
                    ('pending', 'Pending'),
                    ('ok', 'OK'),
                    ('error', 'Error'),
                    ('denied', 'Denied'),
                    ('timeout', 'Timeout'),
                ], default='pending', max_length=12)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('message_id', models.CharField(blank=True, default='', max_length=36)),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField(default=0)),
                ('finished_at', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='tool_calls', to='api.codingagentsession')),
            ],
            options={
                'db_table': 'coding_agent_tool_calls',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['session', 'created_at'], name='ca_tool_session_idx'),
                    models.Index(fields=['name', '-created_at'], name='ca_tool_name_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CodingAgentFileChange',
            fields=[
                ('id', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('op', models.CharField(choices=[
                    ('create', 'Create'),
                    ('modify', 'Modify'),
                    ('delete', 'Delete'),
                    ('rename', 'Rename'),
                ], default='modify', max_length=10)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('patch', models.TextField(blank=True, default='')),
                ('committed', models.BooleanField(default=False)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=36)),
                ('created_at', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='file_changes', to='api.codingagentsession')),
            ],
            options={
                'db_table': 'coding_agent_file_changes',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['session', '-created_at'], name='ca_file_session_idx'),
                    models.Index(fields=['session', 'path'], name='ca_file_path_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CodingAgentEvent',
            fields=[
                ('id', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[
                    ('status', 'Status'),
                    ('tool', 'Tool'),
                    ('log', 'Log'),
                    ('push', 'Push'),
                    ('pr', 'PR'),
                    ('interrupt', 'Interrupt'),
                ], default='log', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('payload_json', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='events', to='api.codingagentsession')),
            ],
            options={
                'db_table': 'coding_agent_events',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['session', '-created_at'], name='ca_event_session_idx'),
                ],
            },
        ),
    ]
