# Generated by Django 5.2.14 on 2026-07-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_post_view_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundAgentMessage",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("created_at", models.BigIntegerField()),
            ],
            options={
                "db_table": "api_background_agent_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackgroundAgentSession",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("repo_url", models.CharField(max_length=512)),
                ("branch_name", models.CharField(max_length=255)),
                ("goal", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.BigIntegerField()),
                ("updated_at", models.BigIntegerField()),
                ("git_output", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "api_background_agent_session",
            },
        ),
        migrations.AddField(
            model_name="backgroundagentsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="background_agent_sessions",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="backgroundagentmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="api.backgroundagentsession",
            ),
        ),
    ]
