# Generated by Django 5.2.14 on 2026-07-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_background_agent_user_apiuser'),
        ('api', '0086_fix_bg_agent_fk_targets'),
    ]

    operations = [
    ]
