# Generated by Django 5.2.14 on 2026-07-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_merge_20260718_0059'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postview',
            new_name='post_views_post_id_b3b1a3_idx',
            old_name='pv_post_viewed_idx',
        ),
        migrations.RenameIndex(
            model_name='postview',
            new_name='post_views_user_id_78fe02_idx',
            old_name='pv_user_idx',
        ),
        migrations.AlterField(
            model_name='postview',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='api.post'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='api.user'),
        ),
    ]
