# Generated by Django 5.2.14 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_remove_codingactionlog_task_and_more'),
        ('api', '0089_retire_legacy_coding_agent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundagentsession',
            name='context_compacted_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backgroundagentsession',
            name='context_compactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backgroundagentsession',
            name='context_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backgroundagentsession',
            name='context_tokens_estimate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backgroundagentsession',
            name='context_window_tokens',
            field=models.PositiveIntegerField(default=131072),
        ),
        migrations.AddField(
            model_name='backgroundagentsession',
            name='last_compaction_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BackgroundAgentAttachment',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('content_type', models.CharField(blank=True, default='application/octet-stream', max_length=160)),
                ('extension', models.CharField(blank=True, default='', max_length=24)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video')], db_index=True, default='document', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('sent_iteration', models.PositiveIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.backgroundagentmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.backgroundagentsession')),
            ],
            options={
                'db_table': 'background_agent_attachments',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['session', 'created_at'], name='bg_attach_session_created_idx'),
                    models.Index(fields=['message', 'created_at'], name='bg_attach_message_created_idx'),
                ],
            },
        ),
    ]
