# Generated by Django 6.0.1 on 2026-07-19 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_background_agent_mediumtext_logging'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'blog_comment_likes',
            },
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='edited_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.blogcomment'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['announcement_id', 'created_at'], name='blog_commen_announc_f8691c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['parent_comment_id', 'created_at'], name='blog_commen_parent__1612a8_idx'),
        ),
        migrations.AddField(
            model_name='blogcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.blogcomment'),
        ),
        migrations.AddField(
            model_name='blogcommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_likes', to='api.user'),
        ),
        migrations.AlterUniqueTogether(
            name='blogcommentlike',
            unique_together={('comment', 'user')},
        ),
    ]
