# Generated by Django 6.0.1 on 2026-07-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_llm_provider_switching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userllmprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to='api.user'),
        ),
    ]
