# Generated by Django 5.2.14 on 2026-07-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_userllmprovider_user'),
        ('api', '0098_anonymous_forum_media'),
    ]

    operations = [
    ]
