# Generated by Django 5.2.14 on 2026-07-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_merge_20260720_2031'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postmedia',
            new_name='post_media_post_id_fc20f0_idx',
            old_name='post_media_post_order_idx',
        ),
        migrations.RenameIndex(
            model_name='postmedia',
            new_name='post_media_reply_i_985fb4_idx',
            old_name='post_media_reply_order_idx',
        ),
    ]
