# Generated by Django 5.2.14 on 2026-07-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_blog_comment_media'),
        ('api', '0100_rename_post_media_post_order_idx_post_media_post_id_fc20f0_idx_and_more'),
    ]

    operations = [
    ]
