# Generated by Django 6.0.1 on 2026-07-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_merge_20260721_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seller_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(default='qr_code', max_length=50)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payments/%Y/%m/')),
                ('payment_proof_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField(default=0)),
                ('verified_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'payment_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerBalance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_balance', serialize=False, to='api.user')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'seller_balances',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank Transfer')], default='esewa', max_length=30)),
                ('payout_details', models.TextField(help_text='Account holder name, ID, or account number')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Paid'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField(default=0)),
                ('processed_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='blogcommentmedia',
            new_name='blog_commen_comment_d58ce2_idx',
            old_name='blog_commen_comment_f1ab0f_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecommentmedia',
            new_name='resource_co_comment_3a70dd_idx',
            old_name='resource_co_comment_2f3f1a_idx',
        ),
        migrations.AddField(
            model_name='resource',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_paid'], name='resources_is_paid_3266ea_idx'),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_purchases', to='api.user'),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.resource'),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_sales', to='api.user'),
        ),
        migrations.AddField(
            model_name='paymentverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='api.user'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to='api.user'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='paymentverification',
            index=models.Index(fields=['buyer', 'resource', 'status'], name='payment_ver_buyer_i_47b612_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentverification',
            index=models.Index(fields=['seller', 'status'], name='payment_ver_seller__c0ab4e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentverification',
            index=models.Index(fields=['status', '-created_at'], name='payment_ver_status_670faf_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='withdrawal__user_id_dc11ea_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', '-created_at'], name='withdrawal__status_e67567_idx'),
        ),
    ]
