# Generated by Django 6.0.1 on 2026-07-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_paymentverification_sellerbalance_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_comments', to='api.user'),
        ),
    ]
