# Generated by Django 5.2.14 on 2026-08-16 04:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_postmedia_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatsession',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Think (k2think.ai — MBZUAI K2 Think V2)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)')], default='qwen', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='model',
            field=models.CharField(default='qwen3.8-max', max_length=200),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Think (k2think.ai — MBZUAI K2 Think V2)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)'), ('custom', 'Custom OpenAI-compatible endpoint'), ('agnes', 'Agnes 2.0 Flash (Sapiens AI — official API, currently free)'), ('openai', 'OpenAI (ChatGPT official API)'), ('anthropic', 'Anthropic (Claude official API)'), ('gemini', 'Google Gemini (official API)'), ('deepseek', 'DeepSeek (official API)'), ('agentrouter', 'AgentRouter (proxy/router)')], default='qwen', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='points_per_rupee_buyer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='points_per_rupee_seller',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=6),
        ),
        migrations.AlterModelTable(
            name='paymentconfig',
            table=None,
        ),
    ]
