# Generated by Django 6.0.1 on 2026-08-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_ai_feedback'),
        ('api', '0108_alter_arenachatsession_provider_and_more'),
    ]

    operations = [
    ]
