# Generated by Django 6.0.1 on 2026-08-22 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_user_inline_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasBoard',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled canvas', max_length=200)),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'canvas_boards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CanvasNode',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='generating', max_length=12)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('web_search_enabled', models.BooleanField(default=False)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'canvas_nodes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='canvasboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_boards', to='api.user'),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.canvasboard'),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.canvasnode'),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_nodes', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='canvasboard',
            index=models.Index(fields=['user', '-updated_at'], name='canvas_boar_user_id_0293c8_idx'),
        ),
        migrations.AddIndex(
            model_name='canvasnode',
            index=models.Index(fields=['board', 'created_at'], name='canvas_node_board_i_bba1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='canvasnode',
            index=models.Index(fields=['parent', 'created_at'], name='canvas_node_parent__88e981_idx'),
        ),
    ]
