# Generated by Django 6.0.1 on 2026-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_canvas_board_and_nodes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aifeedback',
            new_name='ai_feedback_surface_223784_idx',
            old_name='ai_fb_surf_created_idx',
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('longcat', 'LongCat (longcat.chat — free, no login)'), ('geminiweb', 'Gemini Web (gemini.google.com — anonymous Flash-Lite)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Think (k2think.ai — MBZUAI K2 Think V2)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)'), ('custom', 'Custom OpenAI-compatible endpoint'), ('agnes', 'Agnes 2.0 Flash (Sapiens AI — official API, currently free)'), ('openai', 'OpenAI (ChatGPT official API)'), ('anthropic', 'Anthropic (Claude official API)'), ('gemini', 'Google Gemini (official API)'), ('deepseek', 'DeepSeek (official API)'), ('agentrouter', 'AgentRouter (proxy/router)')], default='qwen', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='system_prompt',
            field=models.TextField(default="You are Neby, a friendly and helpful AI assistant for NEBians — a Nepali learning community platform for teachers, learners, explorers, students, and parents across all levels, faculties, and fields. You help with questions, explain concepts clearly, and assist with resources and learning.\n\nRules:\n- Answer the question directly and accurately. Do NOT force curriculum references.\n- Be conversational, warm, and concise. Use simple language.\n- You can use basic markdown: **bold**, *italic*.\n- Never reveal you are an AI language model. You are Neby, the NEBians assistant.\n- If you don't know something, say so honestly rather than making up an answer."),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
