# Generated by Django 6.0.1 on 2026-08-23 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_agent_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasSnapshot',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='Checkpoint', max_length=120)),
                ('payload', models.TextField()),
                ('created_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'canvas_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='agentaction',
            new_name='agent_actio_persona_e8edb0_idx',
            old_name='agent_actio_persona_idx',
        ),
        migrations.RenameIndex(
            model_name='agentaction',
            new_name='agent_actio_persona_e46d2e_idx',
            old_name='agent_actio_persona_2_idx',
        ),
        migrations.RenameIndex(
            model_name='agentaction',
            new_name='agent_actio_created_2aef53_idx',
            old_name='agent_actio_created_idx',
        ),
        migrations.RenameIndex(
            model_name='agentapikey',
            new_name='agent_api_k_user_id_2ec2a9_idx',
            old_name='agent_api_k_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='agentpersona',
            new_name='agent_perso_autonom_929bff_idx',
            old_name='agent_perso_autonom_idx',
        ),
        migrations.AddField(
            model_name='canvasboard',
            name='settings',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='ai', max_length=24),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='metadata',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='backgroundagentproject',
            name='autofix_enabled',
            field=models.BooleanField(default=True, help_text='When a GitHub Actions run fails on an agent-created task branch (never main), queue an agent session with the failing job log.'),
        ),
        migrations.AddField(
            model_name='canvassnapshot',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.canvasboard'),
        ),
        migrations.AddField(
            model_name='canvassnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_snapshots', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='canvassnapshot',
            index=models.Index(fields=['board', '-created_at'], name='canvas_snap_board_created_idx'),
        ),
    ]
