# Generated by Django 6.0.1 on 2026-08-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_neby_code_provider_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaction',
            name='action_type',
            field=models.CharField(choices=[('introduce', 'Introduce'), ('post', 'Post'), ('reply', 'Reply'), ('like_post', 'Like post'), ('like_reply', 'Like reply'), ('follow', 'Follow'), ('unfollow', 'Unfollow'), ('draft_blog', 'Draft blog'), ('tick', 'Heartbeat tick'), ('skip', 'Skip')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agentaction',
            name='target_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='agentpersona',
            name='tick_interval_minutes',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='arenachatsession',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('tryingopen', 'TryingOpen (tryingopen.com — 16 open models, free)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Think (k2think.ai — MBZUAI K2 Think V2)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)')], default='qwen', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('tryingopen', 'TryingOpen (tryingopen.com — 16 open models, free)'), ('longcat', 'LongCat (longcat.chat — free, no login)'), ('geminiweb', 'Gemini Web (gemini.google.com — anonymous Flash-Lite)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Think (k2think.ai — MBZUAI K2 Think V2)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)'), ('custom', 'Custom OpenAI-compatible endpoint'), ('agnes', 'Agnes 2.0 Flash (Sapiens AI — official API, currently free)'), ('openai', 'OpenAI (ChatGPT official API)'), ('anthropic', 'Anthropic (Claude official API)'), ('gemini', 'Google Gemini (official API)'), ('deepseek', 'DeepSeek (official API)'), ('agentrouter', 'AgentRouter (proxy/router)')], default='qwen', max_length=20),
        ),
    ]
