# Generated by Django 5.2.14 on 2026-08-28 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_lazy_doc_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatsession',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('tryingopen', 'TryingOpen (tryingopen.com — 16 open models, free)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Think (k2think.ai — MBZUAI K2 Think V2)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)'), ('empero', 'Empero (free.empero.org)')], default='qwen', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('tryingopen', 'TryingOpen (tryingopen.com — 16 open models, free)'), ('longcat', 'LongCat (longcat.chat — free, no login)'), ('geminiweb', 'Gemini Web (gemini.google.com — anonymous Flash-Lite)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Think (k2think.ai — MBZUAI K2 Think V2)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)'), ('custom', 'Custom OpenAI-compatible endpoint'), ('agnes', 'Agnes 2.0 Flash (Sapiens AI — official API, currently free)'), ('openai', 'OpenAI (ChatGPT official API)'), ('anthropic', 'Anthropic (Claude official API)'), ('gemini', 'Google Gemini (official API)'), ('deepseek', 'DeepSeek (official API)'), ('agentrouter', 'AgentRouter (proxy/router)'), ('empero', 'Empero (free.empero.org — Qwen 3.8 27B free)')], default='qwen', max_length=20),
        ),
        migrations.CreateModel(
            name='LazyAgentRun',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('goal', models.TextField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=12)),
                ('plan_json', models.TextField(blank=True, default='{}')),
                ('transcript_json', models.TextField(blank=True, default='[]')),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('max_iterations', models.PositiveIntegerField(default=14)),
                ('model_key', models.CharField(blank=True, default='neby-pro', max_length=32)),
                ('llm_provider', models.CharField(blank=True, default='', max_length=64)),
                ('llm_model', models.CharField(blank=True, default='', max_length=160)),
                ('tool_calls', models.PositiveIntegerField(default=0)),
                ('workspace', models.CharField(blank=True, default='', max_length=200)),
                ('error', models.TextField(blank=True, default='')),
                ('meta', models.TextField(blank=True, default='{}')),
                ('created_at', models.BigIntegerField(default=0)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('finished_at', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='api.lazydocsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lazy_runs', to='api.user')),
            ],
            options={
                'db_table': 'lazy_agent_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LazyAgentStep',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(default=0)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('think', 'Thought'), ('plan', 'Plan'), ('tool', 'Tool'), ('artifact', 'Artifact'), ('status', 'Status'), ('final', 'Final'), ('error', 'Error')], default='status', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('detail', models.TextField(blank=True, default='{}')),
                ('status', models.CharField(blank=True, default='ok', max_length=12)),
                ('created_at', models.BigIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.lazyagentrun')),
            ],
            options={
                'db_table': 'lazy_agent_steps',
                'ordering': ['index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LazyArtifact',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('doc', 'Document'), ('slides', 'Slides'), ('sheet', 'Spreadsheet'), ('pdf', 'PDF'), ('code', 'Code'), ('data', 'Data'), ('image', 'Image'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=260)),
                ('mime', models.CharField(blank=True, default='', max_length=140)),
                ('size', models.PositiveIntegerField(default=0)),
                ('storage', models.CharField(blank=True, default='workspace', max_length=16)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('blob_token', models.CharField(blank=True, default='', max_length=80)),
                ('meta', models.TextField(blank=True, default='{}')),
                ('created_at', models.BigIntegerField(default=0)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.lazyagentrun')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.lazydocsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lazy_artifacts', to='api.user')),
            ],
            options={
                'db_table': 'lazy_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lazyagentrun',
            index=models.Index(fields=['user', '-created_at'], name='lazy_run_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lazyagentrun',
            index=models.Index(fields=['session', '-created_at'], name='lazy_run_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lazyagentstep',
            index=models.Index(fields=['run', 'index'], name='lazy_step_run_index_idx'),
        ),
        migrations.AddIndex(
            model_name='lazyartifact',
            index=models.Index(fields=['run', '-created_at'], name='lazy_art_run_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lazyartifact',
            index=models.Index(fields=['user', '-created_at'], name='lazy_art_user_created_idx'),
        ),
    ]
