# Generated by Django 6.0.1 on 2026-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_alter_arenachatsession_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenachatsession',
            name='provider',
            field=models.CharField(choices=[('qwen', 'Qwen (chat.qwen.ai)'), ('tryingopen', 'TryingOpen (tryingopen.com — 16 open models, free)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Horizon (chat.ifm.ai — MBZUAI 375B reasoning)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)'), ('empero', 'Empero (free.empero.org)')], default='qwen', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='provider',
            field=models.CharField(choices=[('qwenfast', 'QwenFast (qwenfast-demo.vercel.app — Qwen3.8-27B superfast)'), ('qwen', 'Qwen (chat.qwen.ai)'), ('tryingopen', 'TryingOpen (tryingopen.com — 16 open models, free)'), ('longcat', 'LongCat (longcat.chat — free, no login)'), ('geminiweb', 'Gemini Web (gemini.google.com — anonymous Flash-Lite)'), ('egov', 'eGov Chat AI (Philippines)'), ('deepai', 'DeepAI (deepai.org)'), ('inception', 'Inception Labs (Mercury 2)'), ('k2think', 'K2 Horizon (chat.ifm.ai — MBZUAI 375B reasoning)'), ('poolside', 'Poolside (chat.poolside.ai — Laguna 2.1)'), ('custom', 'Custom OpenAI-compatible endpoint'), ('agnes', 'Agnes 2.0 Flash (Sapiens AI — official API, currently free)'), ('openai', 'OpenAI (ChatGPT official API)'), ('anthropic', 'Anthropic (Claude official API)'), ('gemini', 'Google Gemini (official API)'), ('deepseek', 'DeepSeek (official API)'), ('agentrouter', 'AgentRouter (proxy/router)'), ('empero', 'Empero (free.empero.org — Qwen 3.8 27B free)')], default='qwen', max_length=20),
        ),
    ]
