package com.neb.ians.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors - clean Google-style M3
val md_theme_light_primary = Color(0xFF1A73E8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E3FD)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF5F6368)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8EAED)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1F1F)
val md_theme_light_tertiary = Color(0xFF188038)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCEEAD6)
val md_theme_light_onTertiaryContainer = Color(0xFF002106)
val md_theme_light_error = Color(0xFFD93025)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFCE8E6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF202124)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF202124)
val md_theme_light_surfaceVariant = Color(0xFFF1F3F4)
val md_theme_light_onSurfaceVariant = Color(0xFF5F6368)
val md_theme_light_outline = Color(0xFFDADCE0)
val md_theme_light_outlineVariant = Color(0xFFE8EAED)
val md_theme_light_surfaceTint = Color(0xFF1A73E8)

// Dark theme colors - clean Google-style M3
val md_theme_dark_primary = Color(0xFF8AB4F8)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF174EA6)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3E3FD)
val md_theme_dark_secondary = Color(0xFFBDC1C6)
val md_theme_dark_onSecondary = Color(0xFF303134)
val md_theme_dark_secondaryContainer = Color(0xFF3C4043)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8EAED)
val md_theme_dark_tertiary = Color(0xFF81C995)
val md_theme_dark_onTertiary = Color(0xFF003913)
val md_theme_dark_tertiaryContainer = Color(0xFF137333)
val md_theme_dark_onTertiaryContainer = Color(0xFFCEEAD6)
val md_theme_dark_error = Color(0xFFF28B82)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFFCE8E6)
val md_theme_dark_background = Color(0xFF202124)
val md_theme_dark_onBackground = Color(0xFFE8EAED)
val md_theme_dark_surface = Color(0xFF292A2D)
val md_theme_dark_onSurface = Color(0xFFE8EAED)
val md_theme_dark_surfaceVariant = Color(0xFF3C4043)
val md_theme_dark_onSurfaceVariant = Color(0xFFBDC1C6)
val md_theme_dark_outline = Color(0xFF5F6368)
val md_theme_dark_outlineVariant = Color(0xFF3C4043)
val md_theme_dark_surfaceTint = Color(0xFF8AB4F8)
