package com.agentx.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val AxPrimary = Color(0xFF004AC6)
val AxOnPrimary = Color(0xFFFFFFFF)
val AxPrimaryContainer = Color(0xFFDBE1FF)
val AxOnPrimaryContainer = Color(0xFF00174B)
val AxTertiary = Color(0xFF56545A)
val AxOnTertiary = Color(0xFFFFFFFF)
val AxTertiaryContainer = Color(0xFFE5E1E8)
val AxOnTertiaryContainer = Color(0xFF1D1B20)
val AxError = Color(0xFFBA1A1A)
val AxOnError = Color(0xFFFFFFFF)
val AxErrorContainer = Color(0xFFFFDAD6)
val AxOnErrorContainer = Color(0xFF410002)
val AxBackground = Color(0xFFF5F6F8)
val AxOnBackground = Color(0xFF0B1C30)
val AxSurface = Color(0xFFF5F6F8)
val AxOnSurface = Color(0xFF0B1C30)
val AxSurfaceVariant = Color(0xFFE8EAED)
val AxOnSurfaceVariant = Color(0xFF434655)
val AxOutline = Color(0xFF737686)
val AxOutlineVariant = Color(0xFFD8DADE)
val AxSurfaceTint = Color(0xFF0053DB)
val AxInverseSurface = Color(0xFF213145)
val AxInverseOnSurface = Color(0xFFEAF1FF)
val AxInversePrimary = Color(0xFFB4C5FF)
val AxSurfaceDim = Color(0xFFDADBDD)
val AxSurfaceBright = Color(0xFFF5F6F8)
val AxSurfaceContainerLowest = Color(0xFFFFFFFF)
val AxSurfaceContainerLow = Color(0xFFF1F3F6)
val AxSurfaceContainer = Color(0xFFECEEF1)
val AxSurfaceContainerHigh = Color(0xFFE6E8EB)
val AxSurfaceContainerHighest = Color(0xFFE1E3E6)

val AxPrimaryDark = Color(0xFFB4C5FF)
val AxOnPrimaryDark = Color(0xFF002D78)
val AxPrimaryContainerDark = Color(0xFF003EA8)
val AxOnPrimaryContainerDark = Color(0xFFDBE1FF)
val AxTertiaryDark = Color(0xFFC4C7C9)
val AxTertiaryContainerDark = Color(0xFF444749)
val AxErrorDark = Color(0xFFFFB4AB)
val AxErrorContainerDark = Color(0xFF93000A)
val AxBackgroundDark = Color(0xFF0B1C30)
val AxOnBackgroundDark = Color(0xFFE5EEFF)
val AxSurfaceDark = Color(0xFF0B1C30)
val AxOnSurfaceDark = Color(0xFFE5EEFF)
val AxSurfaceVariantDark = Color(0xFF434655)
val AxOnSurfaceVariantDark = Color(0xFFC3C6D7)
val AxOutlineDark = Color(0xFF8D90A1)
val AxOutlineVariantDark = Color(0xFF434655)
val AxSurfaceTintDark = Color(0xFFB4C5FF)
val AxInverseSurfaceDark = Color(0xFFE5EEFF)
val AxInverseOnSurfaceDark = Color(0xFF0B1C30)
val AxInversePrimaryDark = Color(0xFF2563EB)
val AxSurfaceDimDark = Color(0xFF0B1C30)
val AxSurfaceBrightDark = Color(0xFF313442)
val AxSurfaceContainerLowestDark = Color(0xFF060F1B)
val AxSurfaceContainerLowDark = Color(0xFF131B2E)
val AxSurfaceContainerDark = Color(0xFF1A2133)
val AxSurfaceContainerHighDark = Color(0xFF252B3E)
val AxSurfaceContainerHighestDark = Color(0xFF30364A)

val AxSuccess = Color(0xFF15803D)
val AxSuccessContainer = Color(0xFFDCFCE7)
val AxWarning = Color(0xFFB45309)
val AxWarningContainer = Color(0xFFFEF3C7)
val AxUnreadDot = Color(0xFFEF4444)
val AxBrandStart = Color(0xFF0058DF)
val AxBrandMid = Color(0xFF004BD4)
val AxBrandEnd = Color(0xFF003CC3)

val LightColorScheme = lightColorScheme(
    primary = AxPrimary,
    onPrimary = AxOnPrimary,
    primaryContainer = AxPrimaryContainer,
    onPrimaryContainer = AxOnPrimaryContainer,
    secondary = AxPrimary,
    onSecondary = AxOnPrimary,
    secondaryContainer = AxPrimaryContainer,
    onSecondaryContainer = AxOnPrimaryContainer,
    tertiary = AxTertiary,
    onTertiary = AxOnTertiary,
    tertiaryContainer = AxTertiaryContainer,
    onTertiaryContainer = AxOnTertiaryContainer,
    error = AxError,
    onError = AxOnError,
    errorContainer = AxErrorContainer,
    onErrorContainer = AxOnErrorContainer,
    background = AxBackground,
    onBackground = AxOnBackground,
    surface = AxSurface,
    onSurface = AxOnSurface,
    surfaceVariant = AxSurfaceVariant,
    onSurfaceVariant = AxOnSurfaceVariant,
    outline = AxOutline,
    outlineVariant = AxOutlineVariant,
    surfaceTint = AxSurfaceTint,
    inverseSurface = AxInverseSurface,
    inverseOnSurface = AxInverseOnSurface,
    inversePrimary = AxInversePrimary,
    surfaceDim = AxSurfaceDim,
    surfaceBright = AxSurfaceBright,
    surfaceContainerLowest = AxSurfaceContainerLowest,
    surfaceContainerLow = AxSurfaceContainerLow,
    surfaceContainer = AxSurfaceContainer,
    surfaceContainerHigh = AxSurfaceContainerHigh,
    surfaceContainerHighest = AxSurfaceContainerHighest
)

val DarkColorScheme = darkColorScheme(
    primary = AxPrimaryDark,
    onPrimary = AxOnPrimaryDark,
    primaryContainer = AxPrimaryContainerDark,
    onPrimaryContainer = AxOnPrimaryContainerDark,
    secondary = AxPrimaryDark,
    onSecondary = AxOnPrimaryDark,
    secondaryContainer = AxPrimaryContainerDark,
    onSecondaryContainer = AxOnPrimaryContainerDark,
    tertiary = AxTertiaryDark,
    onTertiary = AxOnPrimaryDark,
    tertiaryContainer = AxTertiaryContainerDark,
    onTertiaryContainer = AxOnTertiaryContainerDark,
    error = AxErrorDark,
    onError = AxOnPrimaryDark,
    errorContainer = AxErrorContainerDark,
    onErrorContainer = AxErrorContainerDark,
    background = AxBackgroundDark,
    onBackground = AxOnBackgroundDark,
    surface = AxSurfaceDark,
    onSurface = AxOnSurfaceDark,
    surfaceVariant = AxSurfaceVariantDark,
    onSurfaceVariant = AxOnSurfaceVariantDark,
    outline = AxOutlineDark,
    outlineVariant = AxOutlineVariantDark,
    surfaceTint = AxSurfaceTintDark,
    inverseSurface = AxInverseSurfaceDark,
    inverseOnSurface = AxInverseOnSurfaceDark,
    inversePrimary = AxInversePrimaryDark,
    surfaceDim = AxSurfaceDimDark,
    surfaceBright = AxSurfaceBrightDark,
    surfaceContainerLowest = AxSurfaceContainerLowestDark,
    surfaceContainerLow = AxSurfaceContainerLowDark,
    surfaceContainer = AxSurfaceContainerDark,
    surfaceContainerHigh = AxSurfaceContainerHighDark,
    surfaceContainerHighest = AxSurfaceContainerHighestDark
)
