from django.urls import path, include
from django.views.generic import RedirectView
from . import views
from . import views_admin_chat
from . import views_background_agent as ba_views
from . import views_background_agent_lifecycle as ba_lifecycle_views
from . import views_background_agent_mobile as ba_mobile_views
from . import views_llm as ba_llm_views
from . import views_monitor
from . import views_needle
from . import views_avatar
from . import views_videos
from . import views_content_images

app_name = 'web'

urlpatterns = [
    path('', views.home, name='home'),
    path('health/', views_monitor.health_check, name='health_check'),
    path('ajax/neby-assist/', views_needle.ajax_neby_assist, name='ajax_neby_assist'),
    path('ajax/neby-assist/cloud/', views_needle.ajax_neby_cloud, name='ajax_neby_cloud'),
    path('manifest.json', views.manifest_json, name='manifest_json'),
    path('sitemap.xml', views.sitemap_xml, name='sitemap_xml'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('library/', views.library, name='library'),
    path('interactive/', views.interactive_hub, name='interactive_hub'),
    path('interactive/sandbox/frame/', views.interactive_sandbox_frame, name='interactive_sandbox_frame'),
    path('interactive/<str:course_slug>/', views.interactive_course, name='interactive_course'),
    path('interactive/<str:course_slug>/<str:lesson_slug>/', views.interactive_lesson, name='interactive_lesson'),
    path('subject/<str:grade_slug>/<str:subject_slug>/', views.subject_page, name='subject_page'),
    path('search/', views.search, name='search'),
    path('news/', views.news_list, name='news_list'),
    path('news/<slug:slug>/', views.news_detail, name='news_detail'),
    path('results/', views.results_guide, name='results_guide'),
    path('results/check/', views.result_check_page, name='result_check'),
    path('tools/', views.tools_hub, name='tools_hub'),
    path('ajax/results/check/', views.ajax_check_result, name='ajax_check_result'),
    path('ajax/news/comment/', views.ajax_blog_comment, name='ajax_blog_comment'),
    path('ajax/news/<slug:slug>/comments/', views.ajax_blog_comments, name='ajax_blog_comments'),
    path('ajax/search/', views.ajax_instant_search, name='ajax_instant_search'),
    path('forum/', views.forum, name='forum'),
    path('forum/categories/', views.forum_categories, name='forum_categories'),
    path('forum/leaderboard/', views.leaderboard, name='leaderboard'),
    path('videos/', views_videos.videos, name='videos'),
    path('videos/<str:media_id>/', views_videos.video_watch, name='video_watch'),
    path('forum/post/<str:post_id>/', views.forum_post, name='forum_post'),
    path('forum/create/', views.create_post, name='create_post'),
    path('forum/reply/<str:post_id>/', views.reply_post, name='reply_post'),
    path('reader/<str:resource_id>/', views.reader, name='reader'),
    path('resource/<str:resource_id>/', RedirectView.as_view(pattern_name='web:reader', permanent=True), name='resource_redirect'),
    path('resource/<str:resource_id>/edit/', views.edit_resource, name='edit_resource'),
    path('resource/<str:resource_id>/submit-payment/', views.submit_payment_proof, name='submit_payment_proof'),
    path('ajax/withdrawal/request/', views.ajax_request_withdrawal, name='ajax_request_withdrawal'),
    path('upload/', views.upload_resource, name='upload_resource'),
    path('upload/success/', views.upload_success, name='upload_success'),
    path('requests/', views.resource_requests_page, name='resource_requests'),

    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('credits/', views.credits_page, name='credits'),
    path('settings/', views.settings_page, name='settings'),
    path('my-avatar/', views_avatar.my_avatar, name='my_avatar'),
    path('avatar/', views_avatar.avatar_svg_index, name='avatar_index'),
    path('avatar/<str:name>/', views_avatar.avatar_svg, name='avatar_svg'),
    path('ajax/avatar/change-username/', views_avatar.ajax_avatar_change_username, name='ajax_avatar_change_username'),
    path('ajax/avatar/customize/', views_avatar.ajax_avatar_customize, name='ajax_avatar_customize'),
    path('settings/delete-account/', views.delete_account_page, name='delete_account'),
    path('analytics/', views.analytics, name='analytics'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('profile/<str:username>/card.png', views.profile_card_image, name='profile_card_image'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/achievements/', views.profile_achievements, name='profile_achievements'),
    path('ajax/profile/<str:username>/activity/', views.ajax_profile_activity, name='ajax_profile_activity'),
    path('ajax/profile/<str:username>/replies/', views.ajax_profile_replies, name='ajax_profile_replies'),
    path('ajax/profile/<str:username>/resources/', views.ajax_profile_resources, name='ajax_profile_resources'),
    path('login/', views.login_page, name='login'),
    path('auth/token-login/', views.token_login, name='token_login'),
    path('auth/google/', views.google_auth, name='google_auth'),
    path('auth/google/login/', views.google_login, name='google_login'),
    path('auth/google/callback/', views.google_oauth_callback, name='google_oauth_callback'),
    path('auth/github/login/', views.github_login, name='github_login'),
    path('auth/github/callback/', views.github_callback, name='github_callback'),
    path('auth/email/signup/', views.email_signup_page, name='email_signup'),
    path('auth/email/login/', views.email_login_page, name='email_login'),
    path('auth/email/verify/', views.email_verify_page, name='email_verify'),
    path('auth/email/forgot/', views.email_forgot_page, name='email_forgot'),
    path('auth/password/', views.password_page, name='password'),
    path('auth/change-password/', views.change_password_page, name='change_password'),
    path('logout/', views.logout, name='logout'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('terms/', views.terms_of_service, name='terms_of_service'),
    path('copyright-takedown/', views.copyright_takedown, name='copyright_takedown'),
    path('ajax/like/post/<str:post_id>/', views.ajax_like_post, name='ajax_like_post'),
    path('ajax/like/reply/<str:reply_id>/', views.ajax_like_reply, name='ajax_like_reply'),
    path('ajax/like/resource/<str:resource_id>/', views.ajax_like_resource, name='ajax_like_resource'),
    path('ajax/like/resource-comment/<str:comment_id>/', views.ajax_like_resource_comment, name='ajax_like_resource_comment'),
    path('ajax/resource-comment/<str:resource_id>/', views.ajax_resource_comment, name='ajax_resource_comment'),
    path('ajax/resource-comment/<str:comment_id>/delete/', views.ajax_delete_resource_comment, name='ajax_delete_resource_comment'),
    path('ajax/like/blog-comment/<str:comment_id>/', views.ajax_like_blog_comment, name='ajax_like_blog_comment'),
    path('ajax/blog-comment/<str:comment_id>/delete/', views.ajax_delete_blog_comment, name='ajax_delete_blog_comment'),
    path('ajax/reply/<str:post_id>/', views.ajax_create_reply, name='ajax_create_reply'),
    path('ajax/post/', views.ajax_create_post, name='ajax_create_post'),
    path('ajax/post/upload-image/', views.ajax_upload_post_image, name='ajax_upload_post_image'),
    path('ajax/inline-image/upload/', views_content_images.ajax_upload_inline_image, name='ajax_upload_inline_image'),
    path('ajax/poll/<str:poll_id>/vote/', views.ajax_poll_vote, name='ajax_poll_vote'),
    path('ajax/delete/post/<str:post_id>/', views.ajax_delete_post, name='ajax_delete_post'),
    path('ajax/edit/post/<str:post_id>/', views.ajax_edit_post, name='ajax_edit_post'),
    path('ajax/archive/post/<str:post_id>/', views.ajax_archive_post, name='ajax_archive_post'),
    path('ajax/archive/reply/<str:reply_id>/', views.ajax_archive_reply, name='ajax_archive_reply'),
    path('ajax/edit/reply/<str:reply_id>/', views.ajax_edit_reply, name='ajax_edit_reply'),
    path('ajax/delete/reply/<str:reply_id>/', views.ajax_delete_reply, name='ajax_delete_reply'),
    path('ajax/bookmark/toggle/', views.ajax_bookmark_toggle, name='ajax_bookmark_toggle'),
    path('ajax/bookmark/check/', views.ajax_bookmark_check, name='ajax_bookmark_check'),
    path('ajax/report/', views.ajax_report, name='ajax_report'),
    path('ajax/ai-feedback/', views.ajax_ai_feedback, name='ajax_ai_feedback'),
    path('ajax/edit-history/<str:target_type>/<str:target_id>/', views.ajax_edit_history, name='ajax_edit_history'),
    path('ajax/reply-thread/<str:reply_id>/', views.ajax_reply_thread, name='ajax_reply_thread'),
    path('ajax/user-popup/<str:username>/', views.ajax_user_popup, name='ajax_user_popup'),
    path('ajax/user-search/', views.ajax_user_search, name='ajax_user_search'),
    path('ajax/check-username/', views.ajax_check_username, name='ajax_check_username'),
    path('ajax/theme/', views.ajax_set_theme, name='ajax_set_theme'),
    path('ajax/follow/<str:user_id>/', views.ajax_follow_user, name='ajax_follow_user'),
    path('ajax/follow-requests/<str:request_id>/accept/', views.ajax_accept_follow_request, name='ajax_accept_follow_request'),
    path('ajax/follow-requests/<str:request_id>/reject/', views.ajax_reject_follow_request, name='ajax_reject_follow_request'),
    path('ajax/photos/', views.ajax_user_photos, name='ajax_user_photos'),
    path('ajax/photos/<int:photo_id>/activate/', views.ajax_activate_photo, name='ajax_activate_photo'),

    # Social Links
    path('ajax/social-links/', views.ajax_social_links_list, name='ajax_social_links_list'),
    path('ajax/social-links/create/', views.ajax_social_links_create, name='ajax_social_links_create'),
    path('ajax/social-links/<str:link_id>/update/', views.ajax_social_links_update, name='ajax_social_links_update'),
    path('ajax/social-links/<str:link_id>/delete/', views.ajax_social_links_delete, name='ajax_social_links_delete'),
    path('ajax/social-links/reorder/', views.ajax_social_links_reorder, name='ajax_social_links_reorder'),
    path('ajax/social-links/track-click/', views.ajax_social_links_track_click, name='ajax_social_links_track_click'),
    path('ajax/set-password/', views.ajax_set_password, name='ajax_set_password'),
    path('ajax/change-password/', views.ajax_change_password, name='ajax_change_password'),
    path('ajax/settings/toggle-visibility/', views.ajax_toggle_profile_visibility, name='ajax_toggle_profile_visibility'),

    path('ajax/neby-arena/sessions/', views.ajax_arena_sessions, name='ajax_arena_sessions'),
    path('ajax/neby-arena/sessions/<str:session_id>/', views.ajax_arena_session_detail, name='ajax_arena_session_detail'),
    path('ajax/neby-arena/sessions/<str:session_id>/messages/', views.ajax_arena_send_message, name='ajax_arena_send_message'),
    path('ajax/neby-arena/messages/<str:message_id>/regenerate/', views.ajax_arena_regenerate, name='ajax_arena_regenerate'),
    path('ajax/neby-arena/qwen/sessions/', views.ajax_arena_create_qwen_session, name='ajax_arena_create_qwen_session'),
    path('ajax/neby-arena/qwen/sessions/<str:session_id>/messages/', views.ajax_arena_send_message_qwen, name='ajax_arena_send_message_qwen'),

    # eGov Chat AI (Philippine government AI, file uploads)
    path('ajax/neby-arena/egov/models/', views.ajax_arena_egov_models, name='ajax_arena_egov_models'),
    path('ajax/neby-arena/egov/sessions/', views.ajax_arena_create_egov_session, name='ajax_arena_create_egov_session'),
    path('ajax/neby-arena/egov/sessions/<str:session_id>/messages/', views.ajax_arena_send_message_egov, name='ajax_arena_send_message_egov'),

    # DeepAI (multi-model chat, file uploads)
    path('ajax/neby-arena/deepai/models/', views.ajax_arena_deepai_models, name='ajax_arena_deepai_models'),
    path('ajax/neby-arena/deepai/sessions/', views.ajax_arena_create_deepai_session, name='ajax_arena_create_deepai_session'),
    path('ajax/neby-arena/deepai/sessions/<str:session_id>/messages/', views.ajax_arena_send_message_deepai, name='ajax_arena_send_message_deepai'),

    path('notifications/', views.notifications, name='notifications'),
    path('ajax/notifications/', views.ajax_notifications, name='ajax_notifications'),
    path('ajax/notifications/mark-read/', views.ajax_notifications_mark_read, name='ajax_notifications_mark_read'),
    path('ajax/notifications/unread-count/', views.ajax_notifications_unread_count, name='ajax_notifications_unread_count'),

    path('admin/', views.admin_login, name='admin_login'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/analytics/', views.admin_analytics, name='admin_analytics'),
    path('admin/analytics/online-users/', views.admin_analytics_online_users, name='admin_analytics_online_users'),
    path('admin/analytics/refresh/', views.admin_analytics_refresh, name='admin_analytics_refresh'),
    path('admin/analytics/export/csv/', views.admin_analytics_export_csv, name='admin_analytics_export_csv'),
    path('admin/push-notifications/', views.admin_push_notifications, name='admin_push_notifications'),
    path('admin/logout/', views.admin_logout, name='admin_logout'),
    path('admin/users/', views.admin_users, name='admin_users'),
    path('admin/deletions/', views.admin_deletions, name='admin_deletions'),
    path('admin/deletions/<str:request_id>/process/', views.admin_process_deletion, name='admin_process_deletion'),
    path('admin/users/<str:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/resources/', views.admin_resources, name='admin_resources'),
    path('admin/resources/new/', views.admin_resource_create, name='admin_resource_create'),
    path('admin/resources/pending/', views.admin_pending_resources, name='admin_pending_resources'),
    path('admin/resources/<str:resource_id>/', views.admin_resource_edit, name='admin_resource_edit'),
    path('admin/resources/<str:resource_id>/delete/', views.admin_resource_delete, name='admin_resource_delete'),
    path('admin/payments/pending/', views.admin_pending_payments, name='admin_pending_payments'),
    path('admin/withdrawals/', views.admin_withdrawals, name='admin_withdrawals'),
    path('admin/syllabus/', views.admin_syllabus_list, name='admin_syllabus_list'),
    path('admin/syllabus/new/', views.admin_syllabus_create, name='admin_syllabus_create'),
    path('admin/syllabus/import/', views.admin_syllabus_import, name='admin_syllabus_import'),
    path('admin/syllabus/export/', views.admin_syllabus_export, name='admin_syllabus_export'),
    path('admin/syllabus/<str:entry_id>/edit/', views.admin_syllabus_edit, name='admin_syllabus_edit'),
    path('admin/syllabus/<str:entry_id>/preview/', views.admin_syllabus_preview, name='admin_syllabus_preview'),
    path('admin/syllabus/<str:entry_id>/delete/', views.admin_syllabus_delete, name='admin_syllabus_delete'),
    path('admin/resource-requests/', views.admin_resource_requests, name='admin_resource_requests'),
    path('admin/reports/', views.admin_reports, name='admin_reports'),
    path('admin/reports/<str:report_id>/', views.admin_report_detail, name='admin_report_detail'),
    path('admin/posts/', views.admin_posts, name='admin_posts'),
    path('admin/posts/<str:post_id>/', views.admin_post_detail, name='admin_post_detail'),
    path('admin/posts/<str:post_id>/delete/', views.admin_post_delete, name='admin_post_delete'),
    path('admin/replies/<str:reply_id>/delete/', views.admin_reply_delete, name='admin_reply_delete'),
    path('admin/bots/', views.admin_bots, name='admin_bots'),
    path('admin/bots/new/', views.admin_bot_edit, name='admin_bot_new'),
    path('admin/bots/<int:bot_id>/', views.admin_bot_edit, name='admin_bot_edit'),
    path('admin/bots/<int:bot_id>/create-user/', views.admin_bot_create_user, name='admin_bot_create_user'),
    path('admin/study-spaces/', views.admin_study_spaces, name='admin_study_spaces'),
    path('admin/study-spaces/<str:space_id>/delete/', views.admin_study_space_delete, name='admin_study_space_delete'),
    path('admin/announcements/', views.admin_announcements, name='admin_announcements'),
    path('admin/announcements/new/', views.admin_announcement_edit, name='admin_announcement_new'),
    path('admin/announcements/<str:announcement_id>/', views.admin_announcement_edit, name='admin_announcement_edit'),
    path('admin/chat/', views_admin_chat.admin_chat, name='admin_chat'),
    path('admin/chat/send/', views_admin_chat.ajax_admin_chat_send, name='admin_chat_send'),
    path('admin/hero-backgrounds/', views.admin_hero_backgrounds, name='admin_hero_backgrounds'),

    # Study Lab
    path('study-lab/', views.study_lab, name='study_lab'),
    path('study-lab/shared/<str:token>/', views.study_lab_shared, name='study_lab_shared'),
    path('study-space/<str:space_id>/', views.study_space_page, name='study_space_page'),
    path('study-space/shared/<str:token>/', views.study_space_shared, name='study_space_shared'),
    path('ajax/study-lab/upload/', views.ajax_study_upload, name='ajax_study_upload'),
    path('ajax/study-lab/documents/', views.ajax_study_documents, name='ajax_study_documents'),
    path('ajax/study-lab/document/<str:doc_id>/', views.ajax_study_document_detail, name='ajax_study_document_detail'),
    path('ajax/study-lab/document/<str:doc_id>/delete/', views.ajax_study_delete_document, name='ajax_study_delete_document'),
    path('ajax/study-lab/document/<str:doc_id>/share/', views.ajax_study_share_settings, name='ajax_study_share_settings'),
    path('ajax/study-lab/document/<str:doc_id>/parse-status/', views.ajax_study_parse_status, name='ajax_study_parse_status'),
    path('ajax/study-lab/document/<str:doc_id>/reparse/', views.ajax_study_reparse, name='ajax_study_reparse'),
    path('ajax/study-lab/document/<str:doc_id>/summary/', views.ajax_study_generate_summary, name='ajax_study_generate_summary'),
    path('ajax/study-lab/document/<str:doc_id>/summary/edit/', views.ajax_study_update_summary, name='ajax_study_update_summary'),
    path('ajax/study-lab/document/<str:doc_id>/mindmap/', views.ajax_study_generate_mindmap, name='ajax_study_generate_mindmap'),
    path('ajax/study-lab/document/<str:doc_id>/quiz/', views.ajax_study_generate_quiz, name='ajax_study_generate_quiz'),
    path('ajax/study-lab/document/<str:doc_id>/flashcards/', views.ajax_study_generate_flashcards, name='ajax_study_generate_flashcards'),
    path('ajax/study-lab/quiz/<str:quiz_id>/', views.ajax_study_quiz_detail, name='ajax_study_quiz_detail'),
    path('ajax/study-lab/quiz/<str:quiz_id>/submit/', views.ajax_study_quiz_submit, name='ajax_study_quiz_submit'),
    path('ajax/study-lab/flashcard/<str:card_id>/review/', views.ajax_study_flashcard_review, name='ajax_study_flashcard_review'),

    # Study Space AJAX
    path('ajax/study-space/list/', views.ajax_space_list, name='ajax_space_list'),
    path('ajax/study-space/public/', views.ajax_space_public_list, name='ajax_space_public_list'),
    path('ajax/study-space/join-code/', views.ajax_space_join_code, name='ajax_space_join_code'),
    path('ajax/study-space/shared/<str:token>/join/', views.ajax_space_join_shared, name='ajax_space_join_shared'),
    path('ajax/study-space/create/', views.ajax_space_create, name='ajax_space_create'),
    path('ajax/study-space/<str:space_id>/', views.ajax_space_detail, name='ajax_space_detail'),
    path('ajax/study-space/<str:space_id>/update/', views.ajax_space_update, name='ajax_space_update'),
    path('ajax/study-space/<str:space_id>/delete/', views.ajax_space_delete, name='ajax_space_delete'),
    path('ajax/study-space/<str:space_id>/share/', views.ajax_space_share, name='ajax_space_share'),
    path('ajax/study-space/<str:space_id>/settings/', views.ajax_space_settings, name='ajax_space_settings'),
    path('ajax/study-space/<str:space_id>/presence/', views.ajax_space_presence, name='ajax_space_presence'),
    path('ajax/study-space/<str:space_id>/notes/', views.ajax_space_notes, name='ajax_space_notes'),
    path('ajax/study-space/<str:space_id>/tutor/', views.ajax_space_tutor, name='ajax_space_tutor'),
    path('ajax/study-space/<str:space_id>/canvas-ai/', views.ajax_space_canvas_ai, name='ajax_space_canvas_ai'),
    path('ajax/llm/models/', views.ajax_llm_models, name='ajax_llm_models'),
    path('ajax/study-space/<str:space_id>/learning-path/', views.ajax_space_learning_path, name='ajax_space_learning_path'),
    path('ajax/study-space/<str:space_id>/members/<str:member_user_id>/role/', views.ajax_space_member_role, name='ajax_space_member_role'),
    path('ajax/study-space/<str:space_id>/members/<str:member_user_id>/remove/', views.ajax_space_member_remove, name='ajax_space_member_remove'),
    path('ajax/study-space/<str:space_id>/document/add/', views.ajax_space_add_document, name='ajax_space_add_document'),
    path('ajax/study-space/<str:space_id>/document/list/', views.ajax_space_list_available_docs, name='ajax_space_list_available_docs'),
    path('ajax/study-space/<str:space_id>/resource/list/', views.ajax_space_list_resources, name='ajax_space_list_resources'),
    path('ajax/study-space/<str:space_id>/resource/add/', views.ajax_space_add_resource, name='ajax_space_add_resource'),
    path('ajax/study-space/<str:space_id>/document/<str:doc_id>/remove/', views.ajax_space_remove_document, name='ajax_space_remove_document'),
    path('ajax/study-space/<str:space_id>/document/<str:doc_id>/parse-status/', views.ajax_space_parse_status, name='ajax_space_parse_status'),
    path('ajax/study-space/<str:space_id>/document/<str:doc_id>/reparse/', views.ajax_space_reparse, name='ajax_space_reparse'),
    path('ajax/study-space/<str:space_id>/upload/', views.ajax_space_upload, name='ajax_space_upload'),
path('ajax/study-space/<str:space_id>/summary/', views.ajax_space_generate_summary, name='ajax_space_generate_summary'),
    path('ajax/study-space/<str:space_id>/summary/edit/', views.ajax_space_update_summary, name='ajax_space_update_summary'),
    path('ajax/study-space/<str:space_id>/mindmap/', views.ajax_space_generate_mindmap, name='ajax_space_generate_mindmap'),
    path('ajax/study-space/<str:space_id>/quiz/', views.ajax_space_generate_quiz, name='ajax_space_generate_quiz'),
    path('ajax/study-space/<str:space_id>/quizzes/', views.ajax_space_quiz_history, name='ajax_space_quiz_history'),
    path('ajax/study-space/<str:space_id>/flashcards/', views.ajax_space_generate_flashcards, name='ajax_space_generate_flashcards'),
    path('ajax/study-space/generation/<str:job_id>/', views.ajax_generation_status, name='ajax_generation_status'),
    path('ajax/study-space/quiz/<str:quiz_id>/', views.ajax_space_quiz_detail, name='ajax_space_quiz_detail'),
    path('ajax/study-space/quiz/<str:quiz_id>/submit/', views.ajax_space_quiz_submit, name='ajax_space_quiz_submit'),
    path('ajax/study-space/flashcard/<str:card_id>/review/', views.ajax_space_flashcard_review, name='ajax_space_flashcard_review'),
    # Background Agent (standalone, not admin-panel)
    path('backgroundagent/login/', ba_views.background_agent_login, name='background_agent_login'),
    path('backgroundagent/logout/', ba_views.background_agent_logout, name='background_agent_logout'),
    path('backgroundagent/', ba_views.background_agent_page, name='background_agent'),
    path('backgroundagent/session/<str:session_id>/', ba_views.background_agent_session_page, name='background_agent_session_page'),
    path('backgroundagent/github/connect/', ba_views.background_agent_github_connect, name='background_agent_github_connect'),
    path('backgroundagent/github/disconnect/', ba_views.background_agent_github_disconnect, name='background_agent_github_disconnect'),
    path('backgroundagent/mobile/authorize/', ba_mobile_views.background_agent_mobile_authorize, name='background_agent_mobile_authorize'),
    path('backgroundagent/api/state/', ba_views.background_agent_state, name='background_agent_state'),
    path('backgroundagent/api/repositories/', ba_views.background_agent_repositories, name='background_agent_repositories'),
    path('backgroundagent/api/branches/', ba_views.background_agent_branches, name='background_agent_branches'),
    path('backgroundagent/api/projects/', ba_views.background_agent_create_project, name='background_agent_create_project'),
    path('backgroundagent/api/sessions/', ba_views.background_agent_create_session, name='background_agent_create_session'),
    path('backgroundagent/api/sessions/<str:session_id>/', ba_views.background_agent_session_detail, name='background_agent_session_detail'),
    path('backgroundagent/api/sessions/<str:session_id>/events/', ba_views.background_agent_session_events, name='background_agent_session_events'),
    path('backgroundagent/api/sessions/<str:session_id>/stream/', ba_views.background_agent_session_stream, name='background_agent_session_stream'),
    path('backgroundagent/api/sessions/<str:session_id>/messages/', ba_views.background_agent_session_message, name='background_agent_session_message'),
    path('backgroundagent/api/sessions/<str:session_id>/files/', ba_views.background_agent_session_files, name='background_agent_session_files'),
    path('backgroundagent/api/sessions/<str:session_id>/file/', ba_views.background_agent_session_file, name='background_agent_session_file'),
    path('backgroundagent/api/sessions/<str:session_id>/preview/', ba_views.background_agent_session_preview, name='background_agent_session_preview'),
    path('backgroundagent/api/sessions/<str:session_id>/control/', ba_views.background_agent_session_control, name='background_agent_session_control'),
    path('backgroundagent/api/sessions/<str:session_id>/actions/', ba_views.background_agent_session_action, name='background_agent_session_action'),
    path('backgroundagent/api/sessions/<str:session_id>/lifecycle/', ba_lifecycle_views.background_agent_session_lifecycle, name='background_agent_session_lifecycle'),
    path('backgroundagent/api/llm/providers/', ba_llm_views.background_agent_llm_providers, name='background_agent_llm_providers'),
    path('backgroundagent/api/llm/providers/<str:provider_id>/', ba_llm_views.background_agent_llm_provider_detail, name='background_agent_llm_provider_detail'),
    path('backgroundagent/api/llm/test/', ba_llm_views.background_agent_llm_test, name='background_agent_llm_test'),
    path('backgroundagent/api/sessions/<str:session_id>/export/', ba_views.background_agent_session_export, name='background_agent_session_export'),
    path('backgroundagent/api/sessions/<str:session_id>/artifacts/<str:kind>/', ba_views.background_agent_download_artifact, name='background_agent_download_artifact'),
]
