COURSES = [
    {
        'slug': 'solar-system-journey',
        'title': 'Solar System Journey',
        'category': 'space',
        'age_range': '8-12',
        'level': 'Beginner',
        'icon': 'wb_sunny',
        'color': '#8B5CF6',
        'tagline': 'Fly past the Sun, eight planets, the Moon and even an eclipse — all in 3D.',
        'description': 'Take a guided tour of our cosmic neighbourhood. You will fly around a living 3D solar system, watch the Earth spin through day and night, drag the Moon through its phases and line up your very own eclipse. Every lesson is a simulation you can touch.',
        'skills': ['Names and order of the 8 planets', 'Why we have day, night and seasons', 'Reading Moon phases like a calendar', 'How solar and lunar eclipses happen', 'Thinking in 3D space'],
        'lessons': [
            {
                'slug': 'tour-the-solar-system',
                'title': 'Tour the Solar System',
                'icon': 'travel_explore',
                'minutes': 15,
                'sim': 'space/solar-system',
                'sim_type': '3d',
                'summary': 'Fly around a 3D model of the Sun and all eight planets, and tap each one to meet it.',
                'objectives': [
                    'Name the eight planets in order from the Sun',
                    'Tell the difference between rocky inner planets and giant outer planets',
                    'Explain why a year is shorter on Mercury than on Neptune',
                    'Find Earth and its Moon in the big family picture',
                ],
                'knowledge': [
                    {'heading': 'One star, eight planets', 'body': 'Our solar system is a family of worlds travelling around one star — the Sun. The Sun is so huge that it holds 99.8% of all the mass in the solar system, and its gravity keeps everything else circling around it.\n\nIn order from the Sun, the planets are Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune. A fun way to remember them: "My Very Excellent Mother Just Served Us Noodles."'},
                    {'heading': 'Rocky worlds and gas giants', 'body': 'The four planets closest to the Sun — Mercury, Venus, Earth and Mars — are small, rocky worlds with solid ground you could stand on. They are called the inner planets.\n\nThe four outer planets are completely different. Jupiter and Saturn are gas giants, enormous balls of hydrogen and helium with no surface at all. Uranus and Neptune are ice giants, cold and blue. Jupiter alone is so big that more than 1,300 Earths could fit inside it.'},
                    {'heading': 'A year is a lap around the Sun', 'body': 'A "year" simply means one full trip around the Sun. Planets close to the Sun move faster and have a shorter path, so their years fly by — Mercury finishes a lap in just 88 Earth days.\n\nFar-away planets crawl along huge orbits. Neptune needs about 165 Earth years for one lap, which means nobody could ever celebrate their first Neptune birthday! Earth takes 365.25 days, and that extra quarter day is why we add 29 Falgun... sorry, 29 February, every four years.'},
                    {'heading': 'Try it in the simulation', 'body': 'In the 3D model, drag with one finger to orbit around the Sun, and pinch or scroll to zoom. Use the "Fly to" menu to visit each planet up close, then tap a planet to read its story.\n\nSpeed up time with the slider and watch how Mercury whizzes around while Neptune barely moves. The distances and sizes are squeezed so everything fits on screen — the real solar system is almost all empty space!'},
                ],
                'fun_fact': 'If the Sun were the size of a football in Kathmandu, Earth would be a peppercorn about 26 metres away — and Neptune would be a small bead nearly 800 metres down the road.',
                'quiz': [
                    {'q': 'Which planet is closest to the Sun?', 'options': ['Venus', 'Mercury', 'Mars', 'Earth'], 'answer': 1, 'explain': 'Mercury is the innermost planet, racing around the Sun in only 88 Earth days.'},
                    {'q': 'Which of these is a gas giant?', 'options': ['Mars', 'Venus', 'Jupiter', 'Mercury'], 'answer': 2, 'explain': 'Jupiter is the biggest gas giant — a ball of hydrogen and helium with no solid surface.'},
                    {'q': 'What do we call one full trip of a planet around the Sun?', 'options': ['A day', 'A month', 'A season', 'A year'], 'answer': 3, 'explain': 'One orbit around the Sun is one year. For Earth that takes 365.25 days.'},
                    {'q': 'Why does Neptune have such a long year?', 'options': ['It spins very slowly', 'Its orbit is huge and it moves slower', 'The Sun pulls it faster', 'It keeps stopping'], 'answer': 1, 'explain': 'Neptune is about 30 times farther from the Sun than Earth, so its path is enormous and gravity moves it more slowly — one lap takes about 165 Earth years.'},
                ],
            },
            {
                'slug': 'earth-moon-and-sun',
                'title': 'Earth, Moon and Sun',
                'icon': 'public',
                'minutes': 15,
                'sim': 'space/earth-moon-sun',
                'sim_type': '3d',
                'summary': 'Watch the tilted, spinning Earth circle the Sun and discover where day, night, years and seasons come from.',
                'objectives': [
                    'Explain why we have day and night',
                    'Connect one orbit of the Sun to one year',
                    'Show how Earth\u2019s 23.5\u00b0 tilt creates the seasons',
                    'Spot the day\u2013night line (terminator) on the 3D Earth',
                ],
                'knowledge': [
                    {'heading': 'Day and night: Earth spins', 'body': 'The Sun never switches off — Earth just turns. Our planet spins once every 24 hours, so each place takes a turn facing the Sun (daytime) and facing away into space (night).\n\nIn the simulation you can see the terminator, the soft line between the bright day side and the dark night side. When it is midday in Nepal, it is the middle of the night in faraway places like Peru, on the opposite side of the globe.'},
                    {'heading': 'A year: Earth orbits', 'body': 'While it spins, Earth is also racing around the Sun at about 107,000 km/h. One complete orbit takes 365.25 days — one year.\n\nWatch the month badge in the simulation as Earth moves along its orbit. Notice that the orbit is almost a perfect circle, so our distance from the Sun barely changes during the year. That means distance is NOT the reason for summer and winter — the real reason is the tilt.'},
                    {'heading': 'Seasons come from the tilt', 'body': 'Earth\u2019s spin axis is tilted by 23.5 degrees, and it keeps pointing the same way in space all year, like a leaning spinning top. For part of the orbit the northern half leans toward the Sun — sunlight hits it more directly and days are longer, giving Nepal its hot summer.\n\nSix months later the north leans away. Sunlight arrives at a low slant and spreads thin, days get short, and winter settles over the Himalaya. Turn on the axis line in the sim and watch this happen.'},
                    {'heading': 'The Moon tags along', 'body': 'As Earth orbits the Sun, the Moon orbits Earth about once every 27.3 days, held by Earth\u2019s gravity. It is our only natural satellite and our constant travelling companion.\n\nUse the "Follow Earth" view to ride alongside our planet and watch the Moon loop around it while both of them sweep around the Sun. Three motions at once — spin, Moon orbit and Earth orbit — all happening right now while you read this.'},
                ],
                'fun_fact': 'Because Earth\u2019s orbit is slightly oval, Earth is actually closest to the Sun in early January — in the middle of Nepal\u2019s winter! That proves seasons come from the tilt, not the distance.',
                'quiz': [
                    {'q': 'Why do we have day and night?', 'options': ['The Sun goes around Earth', 'Earth spins on its axis', 'The Moon blocks the Sun', 'The Sun turns off at night'], 'answer': 1, 'explain': 'Earth rotates once every 24 hours, so each side takes turns facing the Sun.'},
                    {'q': 'How long does Earth take to orbit the Sun once?', 'options': ['24 hours', '27.3 days', '365.25 days', '12 years'], 'answer': 2, 'explain': 'One full orbit takes 365.25 days — that is exactly what we call a year.'},
                    {'q': 'What causes the seasons?', 'options': ['Earth moving closer and farther from the Sun', 'Earth\u2019s tilted axis', 'Clouds covering the Sun', 'The Moon\u2019s shadow'], 'answer': 1, 'explain': 'The 23.5\u00b0 tilt means each hemisphere leans toward the Sun for part of the year (summer) and away for another part (winter).'},
                    {'q': 'When Nepal has summer, what is happening?', 'options': ['Earth is closest to the Sun', 'The northern hemisphere leans toward the Sun', 'The Sun burns hotter', 'Earth spins faster'], 'answer': 1, 'explain': 'Summer in the north happens when the northern hemisphere is tilted sunward, so sunlight strikes it more directly and days are longer.'},
                ],
            },
            {
                'slug': 'phases-of-the-moon',
                'title': 'Phases of the Moon',
                'icon': 'dark_mode',
                'minutes': 12,
                'sim': 'space/moon-phases',
                'sim_type': '3d',
                'summary': 'Drag the Moon around its orbit and watch its shape change in the "view from Earth" window — from aunsi to purnima.',
                'objectives': [
                    'Explain why the Moon seems to change shape',
                    'Name the eight Moon phases in order',
                    'Bust the myth that phases are Earth\u2019s shadow',
                    'Connect purnima and aunsi to Full Moon and New Moon',
                ],
                'knowledge': [
                    {'heading': 'Half the Moon is always lit', 'body': 'The Moon makes no light of its own — it only reflects sunlight. At every moment, the half of the Moon facing the Sun is bright and the other half is dark, exactly like Earth\u2019s day and night sides.\n\nWhat changes during the month is not the lighting, but our viewpoint. As the Moon travels around Earth, we see different amounts of its lit half. That changing view is what we call the phases.'},
                    {'heading': 'Not Earth\u2019s shadow!', 'body': 'Many people think the Moon\u2019s phases are caused by Earth\u2019s shadow falling on it. That is a myth! Earth\u2019s shadow only touches the Moon during a lunar eclipse, which is rare.\n\nProve it in the simulation: drag the Moon to the first-quarter position. Earth is not between the Sun and Moon at all, yet we still see only half a bright Moon. The dark part is simply the Moon\u2019s own night side turned toward us.'},
                    {'heading': 'The eight phases', 'body': 'Starting from New Moon (the Moon sits between us and the Sun, its dark side faces us), the lit part grows — waxing. We see Waxing Crescent, First Quarter, Waxing Gibbous and then Full Moon, when Earth is between... no wait, when the Moon\u2019s lit side fully faces us.\n\nThen the light shrinks — waning: Waning Gibbous, Last Quarter, Waning Crescent and back to New Moon. The whole cycle takes about 29.5 days, which is why "month" and "Moon" are related words.'},
                    {'heading': 'The Moon in the Nepali calendar', 'body': 'Nepali life follows the Moon closely. Purnima is the Full Moon and aunsi is the New Moon, and the lunar fortnights between them set the dates of festivals: Buddha Jayanti on Baisakh Purnima, Janai Purnima, and Laxmi Puja near Kartik aunsi.\n\nSo when you drag the Moon to the "Full" position in this simulation, you are looking at a purnima night — the same Moon that lights up festival nights across Nepal every month.'},
                ],
                'fun_fact': 'The Moon always shows Earth the same face! It spins exactly once per orbit, so the "far side" of the Moon was a total mystery until a spacecraft photographed it in 1959.',
                'quiz': [
                    {'q': 'Why does the Moon appear to change shape?', 'options': ['Earth\u2019s shadow covers it', 'Clouds block parts of it', 'We see different amounts of its sunlit half', 'The Moon really changes shape'], 'answer': 2, 'explain': 'Half the Moon is always lit by the Sun. As the Moon orbits Earth, our view of that lit half changes — those are the phases.'},
                    {'q': 'What is a purnima in Moon-phase language?', 'options': ['New Moon', 'Full Moon', 'First Quarter', 'Waning Crescent'], 'answer': 1, 'explain': 'Purnima is the Full Moon night, when the Moon\u2019s entire lit side faces Earth. Aunsi is the New Moon.'},
                    {'q': 'Where is the Moon during New Moon (aunsi)?', 'options': ['Behind Earth, opposite the Sun', 'Between Earth and the Sun', 'Above the North Pole', 'Farthest from Earth'], 'answer': 1, 'explain': 'At New Moon the Moon sits roughly between Earth and the Sun, so its dark night side faces us and we see almost nothing.'},
                    {'q': 'How long is one full cycle of Moon phases?', 'options': ['About 7 days', 'About 29.5 days', 'Exactly 365 days', 'About 88 days'], 'answer': 1, 'explain': 'From one New Moon to the next takes about 29.5 days — the original meaning of a "month".'},
                ],
            },
            {
                'slug': 'eclipses',
                'title': 'Eclipses',
                'icon': 'brightness_3',
                'minutes': 14,
                'sim': 'space/eclipses',
                'sim_type': '3d',
                'summary': 'Line up the Sun, Earth and Moon yourself, watch the shadow cones, and discover why eclipses are rare.',
                'objectives': [
                    'Describe what happens during a solar eclipse',
                    'Describe what happens during a lunar eclipse',
                    'Explain why eclipses don\u2019t happen every month',
                    'Know the safety rule: never look directly at the Sun',
                ],
                'knowledge': [
                    {'heading': 'Solar eclipse: the Moon\u2019s shadow', 'body': 'A solar eclipse happens when the Moon slides exactly between the Sun and Earth. The Moon\u2019s shadow — a long dark cone — sweeps across part of Earth, and people standing inside it see the Sun covered up, sometimes completely.\n\nBy amazing coincidence, the Sun is about 400 times wider than the Moon but also about 400 times farther away, so they look the same size in our sky. That is why the Moon can cover the Sun so perfectly.'},
                    {'heading': 'Lunar eclipse: Earth\u2019s shadow', 'body': 'A lunar eclipse is the opposite line-up: Earth sits between the Sun and the Moon, and the Moon glides through Earth\u2019s huge shadow cone.\n\nInstead of going totally black, the eclipsed Moon usually glows a deep coppery red — sometimes called a "blood moon". Earth\u2019s atmosphere bends a little red sunlight around the planet and into the shadow, like the light of every sunrise and sunset on Earth shining on the Moon at once.'},
                    {'heading': 'Why not every month?', 'body': 'If the Moon orbited in exactly the same flat plane as Earth\u2019s orbit, we would get a solar eclipse every New Moon and a lunar eclipse every Full Moon. But the Moon\u2019s orbit is tilted by about 5 degrees.\n\nMost months, the Moon passes a little above or below the perfect line, and its shadow misses Earth (or it misses Earth\u2019s shadow). Try the tilt slider in the simulation: even a small tilt makes the shadows miss. Only when the line-up is perfect — a few times a year — do we get an eclipse somewhere on Earth.'},
                    {'heading': 'Watch safely!', 'body': 'Never look directly at the Sun — during an eclipse or any other time. Even when 99% of the Sun is covered, the remaining sliver can permanently damage your eyes, and sunglasses are NOT enough protection.\n\nSafe ways to enjoy a solar eclipse: certified eclipse glasses (ISO 12312-2), or a simple pinhole projector — poke a small hole in cardboard and project the Sun\u2019s image onto the ground. Lunar eclipses, on the other hand, are completely safe to watch with bare eyes. Enjoy the red Moon!'},
                ],
                'fun_fact': 'The Moon is slowly drifting away from Earth — about 3.8 cm per year, the speed your fingernails grow. In several hundred million years it will look too small to fully cover the Sun, and total solar eclipses will end forever.',
                'quiz': [
                    {'q': 'During a solar eclipse, what is the correct order?', 'options': ['Sun \u2013 Earth \u2013 Moon', 'Sun \u2013 Moon \u2013 Earth', 'Moon \u2013 Sun \u2013 Earth', 'Earth \u2013 Sun \u2013 Moon'], 'answer': 1, 'explain': 'In a solar eclipse the Moon is in the middle, casting its shadow onto Earth and blocking the Sun.'},
                    {'q': 'Why does the eclipsed Moon turn red during a lunar eclipse?', 'options': ['The Moon heats up', 'Earth\u2019s atmosphere bends red sunlight into the shadow', 'Mars shines on it', 'The Moon has red rocks'], 'answer': 1, 'explain': 'Earth\u2019s air filters and bends red light around the planet into its shadow — the glow of all Earth\u2019s sunsets falling on the Moon.'},
                    {'q': 'Why don\u2019t eclipses happen every month?', 'options': ['The Moon is too small', 'The Moon\u2019s orbit is tilted about 5\u00b0', 'The Sun moves away', 'Clouds block them'], 'answer': 1, 'explain': 'Because of the 5\u00b0 tilt, the Moon usually passes above or below the exact Sun\u2013Earth line, so the shadows miss.'},
                    {'q': 'Which is safe to look at with bare eyes?', 'options': ['A partial solar eclipse', 'A total lunar eclipse', 'The Sun through sunglasses', 'The Sun through a telescope'], 'answer': 1, 'explain': 'A lunar eclipse is just the Moon in shadow — totally safe. Never look at the Sun directly, even with sunglasses.'},
                ],
            },
        ],
    },
    {
        'slug': 'gravity-and-orbits',
        'title': 'Gravity & Orbits',
        'category': 'space',
        'age_range': '12-16',
        'level': 'Intermediate',
        'icon': 'orbit',
        'color': '#7C3AED',
        'tagline': 'Launch planets, fly rockets and bend space around a star — real physics, your hands.',
        'description': 'Gravity is the invisible sculptor of the universe. In this course you will fling planets around a star in a gravity sandbox, launch a rocket and feel the fight between thrust and weight, prove Kepler\u2019s laws with your own eyes, and find out what you would weigh on Jupiter.',
        'skills': ['Newtonian gravity intuition', 'Orbit = falling sideways', 'Thrust, fuel and rocket staging', 'Kepler\u2019s three laws', 'Mass vs weight'],
        'lessons': [
            {
                'slug': 'orbital-sandbox',
                'title': 'Orbital Sandbox',
                'icon': 'gesture',
                'minutes': 18,
                'sim': 'space/orbital-sandbox',
                'sim_type': '2d',
                'summary': 'Drag and release to launch planets around a star — find the perfect speed for a stable orbit before they crash or escape.',
                'objectives': [
                    'Launch a body into a stable orbit by hand',
                    'Explain an orbit as "falling sideways forever"',
                    'Predict what happens when speed is too low or too high',
                    'Observe how star mass changes the needed orbital speed',
                ],
                'knowledge': [
                    {'heading': 'Gravity never switches off', 'body': 'Every object with mass pulls on every other object. The pull grows with mass and weakens with distance — double the distance and the force drops to a quarter. This is Newton\u2019s law of universal gravitation, and it rules everything in this sandbox.\n\nThe star in the centre pulls on each planet you launch, every single frame, always pointing toward the star. The planet\u2019s path is just the running total of "keep moving" plus "keep falling".'},
                    {'heading': 'An orbit is falling sideways', 'body': 'Here is the secret of every satellite and planet: it is falling the whole time — it just moves sideways fast enough to keep missing the thing it is falling toward.\n\nThrow a ball: it curves down and hits the ground. Throw it impossibly fast — about 7.8 km/s near Earth — and the ground curves away beneath it exactly as fast as it falls. It falls forever in a circle. That is what astronauts on the ISS are doing: not floating away from gravity, but falling around the Earth.'},
                    {'heading': 'Too slow, too fast, just right', 'body': 'In the sandbox, a short drag gives a slow launch: gravity wins, the path bends sharply and the body spirals into the star. A huge drag gives a fast launch: gravity can\u2019t bend the path enough and the body escapes into space.\n\nBetween those is the sweet spot — an ellipse or circle that repeats forever. Try launching at a right angle to the line toward the star. Then crank up the star\u2019s mass and notice that the same throw now crashes: stronger gravity demands more sideways speed.'},
                    {'heading': 'Comets: stretched orbits', 'body': 'Press "Add comet" and watch its motion. A comet on a long, stretched ellipse races fastest when it whips around the star and crawls when far away. Nothing pushes or brakes it — gravity simply steals speed on the way out and pays it back on the way in. Energy is conserved.\n\nReal comets do exactly this: Halley\u2019s comet sprints past the Sun, then drifts out beyond Neptune for decades before falling back. You will meet this speed-up/slow-down pattern again in the Kepler lesson.'},
                ],
                'fun_fact': 'Isaac Newton explained orbits in 1687 with a thought experiment: a cannon on a tall mountain firing faster and faster, until the cannonball falls all the way around the Earth. You are running that exact experiment in this sandbox.',
                'quiz': [
                    {'q': 'What keeps a planet in orbit around a star?', 'options': ['Air pushing it', 'The star\u2019s gravity bending its path', 'Magnetism', 'Nothing — space is empty'], 'answer': 1, 'explain': 'Gravity constantly pulls the planet toward the star while its sideways speed keeps it missing — the combination is an orbit.'},
                    {'q': 'You launch a planet too slowly. What happens?', 'options': ['It escapes to infinity', 'It orbits faster', 'It falls in and hits the star', 'It stops in place'], 'answer': 2, 'explain': 'With too little sideways speed, gravity bends the path inward more than the motion can resist, and the body spirals into the star.'},
                    {'q': 'Astronauts float on the ISS because...', 'options': ['There is no gravity in space', 'They are constantly falling around Earth', 'The station\u2019s engines hold it up', 'They are too far from Earth to feel gravity'], 'answer': 1, 'explain': 'At ISS altitude gravity is still about 90% as strong as on the ground. The crew floats because the station and everyone in it are in continuous free fall around the planet.'},
                    {'q': 'If you double the star\u2019s mass, a stable orbit at the same distance needs...', 'options': ['Less speed', 'The same speed', 'More speed', 'No speed'], 'answer': 2, 'explain': 'Stronger gravity bends paths harder, so the body must move sideways faster to keep missing the star.'},
                ],
            },
            {
                'slug': 'rocket-launch',
                'title': 'Rocket Launch',
                'icon': 'rocket_launch',
                'minutes': 16,
                'sim': 'space/rocket-launch',
                'sim_type': '2d',
                'summary': 'Set your thrust and fuel, hit IGNITE, and fight gravity all the way to the edge of space at 100 km.',
                'objectives': [
                    'Use Newton\u2019s third law to explain how rockets push',
                    'Balance thrust against weight to lift off',
                    'See why a rocket accelerates harder as fuel burns away',
                    'Understand escape velocity (~11.2 km/s) as an energy idea',
                ],
                'knowledge': [
                    {'heading': 'Rockets push on their own exhaust', 'body': 'A rocket does not push against the air or the ground. It throws hot gas downward at enormous speed, and by Newton\u2019s third law — every action has an equal and opposite reaction — the gas pushes the rocket up just as hard.\n\nThat is why rockets work perfectly in empty space where there is nothing else to push on. The "thrust" you set in the simulation is exactly this reaction force, measured in kilonewtons.'},
                    {'heading': 'The tug of war: thrust vs weight', 'body': 'At the launch pad, two forces fight: thrust pushing up and weight (mass \u00d7 gravity) pulling down. If thrust is smaller than weight, the rocket just sits there burning fuel — try it!\n\nThe net acceleration is (thrust \u2212 weight) \u00f7 mass. Engineers call thrust \u00f7 weight the thrust-to-weight ratio, and it must be greater than 1 to lift off. Real launchers leave the pad with a ratio of only about 1.2 to 1.5 — a surprisingly gentle start.'},
                    {'heading': 'Lighter every second', 'body': 'Here is the beautiful trick: as the engine burns, the rocket throws its own mass away. A lighter rocket with the same thrust accelerates harder, so rockets speed up faster and faster — watch your velocity graph curve upward.\n\nThis is also why rockets use stages. When a fuel tank empties, it is dead weight, so the rocket drops it. Shedding the empty first stage lets the remaining engine push a much lighter ship. Look for the stage falling away in the simulation.'},
                    {'heading': 'The edge of space and escape velocity', 'body': 'Space officially begins at the K\u00e1rm\u00e1n line, 100 km up — that is your target altitude. But reaching space and staying there are different: to orbit you must also gain about 7.8 km/s of sideways speed.\n\nTo leave Earth completely and never fall back, you need escape velocity: about 11.2 km/s, more than 30 times the speed of sound. It is not a speed you must have at launch — it measures the total energy needed to climb out of Earth\u2019s gravity well.'},
                ],
                'fun_fact': 'The Saturn V Moon rocket burned about 13,000 kg of fuel every second at lift-off — roughly the mass of three adult elephants per second — yet it left the pad slower than a city bus pulls away from a stop.',
                'quiz': [
                    {'q': 'A rocket moves forward by...', 'options': ['Pushing against the air', 'Throwing exhaust gas backward', 'Magnetic repulsion from Earth', 'Pushing on the launch pad'], 'answer': 1, 'explain': 'Newton\u2019s third law: the rocket hurls gas one way, the gas pushes the rocket the other way. No air needed.'},
                    {'q': 'For lift-off, thrust must be...', 'options': ['Equal to the rocket\u2019s weight', 'Greater than the rocket\u2019s weight', 'Less than the rocket\u2019s weight', 'Exactly double the weight'], 'answer': 1, 'explain': 'Only when thrust exceeds weight is there a net upward force to accelerate the rocket off the pad.'},
                    {'q': 'Why does a rocket accelerate harder as it climbs?', 'options': ['Gravity disappears', 'Its engines grow stronger', 'It gets lighter as fuel burns away', 'The air pushes it up'], 'answer': 2, 'explain': 'Same thrust, shrinking mass: acceleration = force \u00f7 mass, so burning off fuel makes the rocket livelier every second.'},
                    {'q': 'Earth\u2019s escape velocity is about...', 'options': ['340 m/s', '7.8 km/s', '11.2 km/s', '300,000 km/s'], 'answer': 2, 'explain': 'About 11.2 km/s of total speed-equivalent energy lets an object leave Earth\u2019s gravity entirely. 7.8 km/s is low-orbit speed.'},
                ],
            },
            {
                'slug': 'kepler-laws',
                'title': 'Kepler\u2019s Laws',
                'icon': 'animation',
                'minutes': 15,
                'sim': 'space/kepler-orbits',
                'sim_type': '2d',
                'summary': 'Stretch an orbit\u2019s eccentricity and watch the planet sweep equal areas in equal times — Kepler\u2019s laws live on your screen.',
                'objectives': [
                    'State Kepler\u2019s three laws in plain language',
                    'Locate the Sun at one focus of an elliptical orbit',
                    'See equal areas swept in equal times as speed changes',
                    'Connect orbit size to orbital period (third law)',
                ],
                'knowledge': [
                    {'heading': 'Law 1: Orbits are ellipses', 'body': 'Johannes Kepler, studying Tycho Brahe\u2019s precise measurements of Mars in the early 1600s, discovered that planets do not move in perfect circles. Every orbit is an ellipse — a stretched circle — with the Sun sitting at one focus, off to the side of the centre.\n\nThe eccentricity slider controls the stretch: e = 0 is a perfect circle, and higher values make longer, thinner ellipses. Earth\u2019s orbit has e = 0.017 (nearly circular); comets can exceed 0.9.'},
                    {'heading': 'Law 2: Equal areas in equal times', 'body': 'A planet does not travel at constant speed. It moves fastest at perihelion (closest to the Sun) and slowest at aphelion (farthest away).\n\nKepler found the exact rule: the line from the Sun to the planet sweeps out equal areas in equal times. Near the Sun the line is short, so it must sweep a wide, fast arc; far away the line is long and a slow crawl covers the same area. Switch on "show swept area" and compare the shaded slices — different shapes, identical areas.'},
                    {'heading': 'Law 3: Bigger orbits, much longer years', 'body': 'Kepler\u2019s third law links size and time: the square of the orbital period is proportional to the cube of the orbit\u2019s average radius (T\u00b2 \u221d a\u00b3).\n\nIn numbers: an orbit 4 times wider takes 8 times longer to complete. This is why Mercury (0.39 AU) laps the Sun in 88 days while Neptune (30 AU) needs 165 years. The law is so reliable that astronomers use it backwards — measuring a moon\u2019s period to calculate the mass of its planet.'},
                    {'heading': 'Why the laws work', 'body': 'Kepler described the patterns but never knew why they held. Seventy years later Newton showed that all three laws fall straight out of his law of gravitation: an inverse-square pull from a single body produces exactly elliptical orbits, conserves angular momentum (which is the equal-area law in disguise), and yields the T\u00b2 \u221d a\u00b3 relationship.\n\nThe same mathematics guides Nepal\u2019s communication satellites, the ISS and every interplanetary probe ever launched. Four-hundred-year-old laws, still steering spacecraft today.'},
                ],
                'fun_fact': 'Kepler spent six years and roughly 900 pages of hand calculations wrestling with an 8-arcminute discrepancy in Mars\u2019 position — an error smaller than the width of your finger at arm\u2019s length. His refusal to ignore it gave us the laws of planetary motion.',
                'quiz': [
                    {'q': 'What shape is a planetary orbit?', 'options': ['A perfect circle', 'An ellipse with the Sun at one focus', 'A spiral', 'A square with rounded corners'], 'answer': 1, 'explain': 'Kepler\u2019s first law: orbits are ellipses, and the Sun sits at one focus — not at the centre.'},
                    {'q': 'Where does a planet move fastest?', 'options': ['At aphelion (farthest)', 'At perihelion (closest)', 'Speed never changes', 'Halfway between'], 'answer': 1, 'explain': 'Closest to the Sun the gravitational pull has sped the planet up the most — it whips through perihelion at maximum speed.'},
                    {'q': 'Kepler\u2019s second law says the Sun\u2013planet line sweeps...', 'options': ['Equal angles in equal times', 'Equal areas in equal times', 'Equal distances in equal times', 'Nothing measurable'], 'answer': 1, 'explain': 'Equal areas in equal times — fast wide arcs near the Sun, slow narrow arcs far away, same swept area either way.'},
                    {'q': 'An orbit 4 times wider than Earth\u2019s takes about how long?', 'options': ['4 years', '8 years', '16 years', '2 years'], 'answer': 1, 'explain': 'Third law: T\u00b2 = a\u00b3, so T = \u221a(4\u00b3) = \u221a64 = 8 years.'},
                ],
            },
            {
                'slug': 'weight-on-other-worlds',
                'title': 'Weight on Other Worlds',
                'icon': 'fitness_center',
                'minutes': 12,
                'sim': 'space/gravity-worlds',
                'sim_type': '2d',
                'summary': 'Pick a world, drop a ball from 10 metres, and see what your weight would be on the Moon, Mars, Jupiter — even the Sun.',
                'objectives': [
                    'Tell the difference between mass and weight',
                    'Compare surface gravity (g) across the solar system',
                    'Predict fall times from different g values',
                    'Calculate your weight on another world',
                ],
                'knowledge': [
                    {'heading': 'Mass is not weight', 'body': 'Mass is the amount of matter in you, measured in kilograms. It is the same everywhere in the universe — on Earth, on the Moon, floating in deep space.\n\nWeight is the force gravity exerts on that mass: weight = mass \u00d7 g, where g is the local gravitational acceleration. Your mass never changes when you travel, but your weight changes on every world, because each world has its own g. On a bathroom scale you are really measuring force, not matter.'},
                    {'heading': 'Every world has its own g', 'body': 'Earth\u2019s surface gravity is g = 9.8 m/s\u00b2. The Moon, small and light, manages only 1.6 m/s\u00b2 — one sixth of Earth — which is why Apollo astronauts bounced like kangaroos in slow motion.\n\nMars gives you 3.7 m/s\u00b2, just over a third of home. Giant Jupiter has no surface, but at its cloud tops you would feel about 24.8 m/s\u00b2, two and a half times Earth. And the Sun? A crushing 274 m/s\u00b2 — 28 times your normal weight (you would have bigger problems than weight there).'},
                    {'heading': 'Falling on other worlds', 'body': 'Drop a ball from 10 metres and the fall time depends only on g: time = \u221a(2h \u00f7 g). On Earth that is 1.4 seconds. On the Moon the same drop takes a dreamy 3.5 seconds; on Jupiter, a snappy 0.9 seconds.\n\nNotice what does NOT matter: the ball\u2019s mass. Heavy and light objects fall together when there is no air resistance — Galileo argued it four centuries ago, and Apollo 15 proved it on the Moon by dropping a hammer and a falcon feather side by side. They landed together.'},
                    {'heading': 'Do the maths for yourself', 'body': 'Converting your weight is one division and one multiplication: take your Earth weight, divide by 9.8 to get your mass-equivalent, then multiply by the other world\u2019s g. Or simply multiply by the ratio g_world \u00f7 9.8.\n\nIf you weigh 50 kg-force on Earth, you weigh about 8 on the Moon, 19 on Mars, 126 on Jupiter\u2019s cloud tops, and over 1,400 on the Sun. Set the slider to your own weight in the simulation and tour the solar system\u2019s bathroom scales.'},
                ],
                'fun_fact': 'On Pluto you would weigh about 6% of your Earth weight — a 50 kg person would weigh just 3 kg-force. You could slam-dunk over a two-storey building... wearing a spacesuit at \u2212230\u00b0C.',
                'quiz': [
                    {'q': 'You travel from Earth to the Moon. What happens?', 'options': ['Mass and weight both drop', 'Mass drops, weight stays', 'Mass stays, weight drops', 'Nothing changes'], 'answer': 2, 'explain': 'Mass is the amount of matter — unchanged by travel. Weight = mass \u00d7 g, and the Moon\u2019s g is six times smaller, so weight drops.'},
                    {'q': 'The Moon\u2019s surface gravity is about...', 'options': ['Half of Earth\u2019s', 'One sixth of Earth\u2019s', 'The same as Earth\u2019s', 'Twice Earth\u2019s'], 'answer': 1, 'explain': 'g on the Moon is about 1.6 m/s\u00b2, roughly 1/6 of Earth\u2019s 9.8 m/s\u00b2 — hence the famous astronaut bounce.'},
                    {'q': 'Where would a 10 m drop take the LEAST time?', 'options': ['The Moon', 'Mars', 'Earth', 'Jupiter\u2019s cloud tops'], 'answer': 3, 'explain': 'Jupiter has the highest g of the four (about 24.8 m/s\u00b2), so the ball accelerates hardest and lands soonest.'},
                    {'q': 'A hammer and a feather are dropped together on the airless Moon. What happens?', 'options': ['The hammer lands first', 'The feather lands first', 'They land together', 'The feather floats away'], 'answer': 2, 'explain': 'Without air resistance, all objects fall with the same acceleration regardless of mass. Apollo 15 demonstrated exactly this in 1971.'},
                ],
            },
        ],
    },
    {
        'slug': 'galaxies-and-the-universe',
        'title': 'Galaxies & the Universe',
        'category': 'space',
        'age_range': '14-19',
        'level': 'Advanced',
        'icon': 'auto_awesome',
        'color': '#6D28D9',
        'tagline': 'Zoom from Everest to the edge of the observable universe — via the life and death of stars.',
        'description': 'Leave the solar system behind. Spin a 3D Milky Way and find our Sun among its hundreds of billions of stars, evolve stars from nebula to black hole, and ride a powers-of-ten zoom from the summit of Everest to the cosmic horizon 93 billion light-years wide.',
        'skills': ['Galaxy structure and our place in it', 'Light-years and cosmic distances', 'Stellar evolution and fusion', 'Supernovae, neutron stars, black holes', 'Powers-of-ten thinking'],
        'lessons': [
            {
                'slug': 'milky-way-galaxy',
                'title': 'The Milky Way Galaxy',
                'icon': 'flare',
                'minutes': 14,
                'sim': 'space/milky-way',
                'sim_type': '3d',
                'summary': 'Orbit a 3D spiral galaxy of thousands of stars and find the tiny "You are here" marker — our Sun, 26,000 light-years from the core.',
                'objectives': [
                    'Describe the structure of a spiral galaxy: bulge, disk, arms, halo',
                    'Locate the Sun\u2019s position in the Milky Way',
                    'Use light-years to express galactic distances',
                    'Grasp the scale: 100\u2013400 billion stars',
                ],
                'knowledge': [
                    {'heading': 'Our city of stars', 'body': 'The Milky Way is our home galaxy: a vast rotating disk of stars, gas and dust about 100,000 light-years across. Astronomers estimate it contains between 100 and 400 billion stars — counting them at one per second would take more than 3,000 years.\n\nFrom a dark Himalayan sky, the Milky Way appears as a glowing band across the night: you are looking along the plane of the disk, through millions of stars too faint and far to separate by eye.'},
                    {'heading': 'Bulge, arms and halo', 'body': 'The galaxy has architecture. At the centre sits the bulge, a dense, golden crowd of mostly old stars wrapped around a supermassive black hole called Sagittarius A* — four million times the Sun\u2019s mass.\n\nSpread around it is the thin disk, where bright young blue stars trace sweeping spiral arms — the galaxy\u2019s star factories, rich in gas and glowing nebulae. Surrounding everything is a sparse spherical halo of ancient stars and globular clusters, plus a vast envelope of invisible dark matter that outweighs all the stars combined.'},
                    {'heading': 'You are here', 'body': 'Find the marker in the simulation: our Sun lives about 26,000 light-years from the galactic centre, on a minor arm called the Orion Spur — comfortably suburban, far from the crowded, radiation-soaked core.\n\nThe whole solar system orbits the galaxy at about 230 km/s, completing one revolution — a "galactic year" — every 225 to 250 million years. The last time we were on this side of the galaxy, dinosaurs had not yet evolved. Earth has made roughly 20 galactic laps in its entire history.'},
                    {'heading': 'The light-year ruler', 'body': 'Galactic distances make kilometres useless, so astronomers use the light-year: the distance light travels in one year, about 9.46 trillion km. Even light, the fastest thing in the universe, needs 100,000 years to cross our galaxy.\n\nA light-year ruler also makes telescopes time machines. The core\u2019s light left 26,000 years ago, when humans were painting cave walls. Look at the Andromeda galaxy and you see light that left 2.5 million years before you were born — you are literally looking into the past.'},
                ],
                'fun_fact': 'The Milky Way and the Andromeda galaxy are approaching each other at about 110 km/s and will merge in roughly 4.5 billion years. Yet the stars are so spread out that almost no two stars are expected to collide.',
                'quiz': [
                    {'q': 'Roughly how many stars are in the Milky Way?', 'options': ['About a million', 'About 100\u2013400 billion', 'Exactly 9 billion', 'A few thousand'], 'answer': 1, 'explain': 'Best estimates put the count between 100 and 400 billion stars — too many to ever count one by one.'},
                    {'q': 'Where is our Sun located?', 'options': ['At the exact centre', 'In the halo above the disk', 'About 26,000 light-years out, on a spiral arm spur', 'Just outside the galaxy'], 'answer': 2, 'explain': 'We live on the Orion Spur, roughly 26,000 light-years from the centre — a quiet neighbourhood about halfway out.'},
                    {'q': 'What sits at the centre of the Milky Way?', 'options': ['A giant star', 'A supermassive black hole', 'The Sun', 'Empty space'], 'answer': 1, 'explain': 'Sagittarius A*, a black hole of about 4 million solar masses, anchors the galactic centre. Stars orbiting it won astronomers the 2020 Nobel Prize.'},
                    {'q': 'A light-year measures...', 'options': ['Time', 'Distance', 'Brightness', 'Speed'], 'answer': 1, 'explain': 'A light-year is the distance light covers in one year — about 9.46 trillion kilometres. It measures distance, not time.'},
                ],
            },
            {
                'slug': 'lifecycle-of-stars',
                'title': 'Lifecycle of Stars',
                'icon': 'local_fire_department',
                'minutes': 16,
                'sim': 'space/star-lifecycle',
                'sim_type': '2d',
                'summary': 'Choose a star\u2019s starting mass and evolve it — will it end as a quiet white dwarf, a neutron star, or a black hole?',
                'objectives': [
                    'Trace a star\u2019s life from nebula to final remnant',
                    'Explain fusion as the balance against gravity',
                    'Predict a star\u2019s fate from its starting mass',
                    'Compare white dwarfs, neutron stars and black holes',
                ],
                'knowledge': [
                    {'heading': 'Born in clouds, lit by fusion', 'body': 'Stars begin inside nebulae — cold clouds of hydrogen gas and dust light-years wide. Gravity slowly gathers clumps; as a clump collapses it heats up, until the core reaches about 10 million degrees and hydrogen nuclei begin fusing into helium.\n\nFusion converts a little mass into a lot of energy (Einstein\u2019s E = mc\u00b2), and the outward push of that energy balances gravity\u2019s inward crush. This stable tug-of-war is called the main sequence — the long adulthood where our Sun sits today, about halfway through its 10-billion-year supply.'},
                    {'heading': 'Mass writes the script', 'body': 'A star\u2019s starting mass decides everything: its colour, its lifespan, and its death. Counter-intuitively, bigger means shorter-lived. A red dwarf of half a solar mass sips fuel for trillions of years; a 20-solar-mass blue giant squanders its huge supply in just a few million.\n\nMassive cores are hotter and denser, so fusion runs ferociously faster — burning a bigger candle at thousands of times the rate. Set the mass slider low and high in the simulation and compare the timelines.'},
                    {'heading': 'Swelling into giants', 'body': 'When the core\u2019s hydrogen runs out, fusion falters and gravity squeezes the core tighter and hotter, igniting hydrogen in a shell and, later, helium fusing into carbon. The outer layers respond by swelling enormously: the star becomes a red giant.\n\nOur Sun will do this in about 5 billion years, ballooning past Mercury and Venus and roasting Earth. Stars above roughly 8 solar masses inflate into even vaster red supergiants — Betelgeuse, on Orion\u2019s shoulder, would swallow every planet out to Jupiter if it replaced our Sun.'},
                    {'heading': 'Three endings', 'body': 'Sun-like stars die gently: the outer layers drift off as a glowing planetary nebula, leaving the bare core as a white dwarf — an Earth-sized ember where a teaspoon weighs about five tonnes — that cools for eternity.\n\nStars above ~8 solar masses go out violently. The core collapses in under a second and the star detonates as a supernova, briefly outshining its whole galaxy and forging elements heavier than iron. The crushed core becomes a neutron star — a city-sized sphere of nuclear matter — or, above roughly 20\u201325 solar masses, a black hole, from which not even light escapes.'},
                ],
                'fun_fact': 'You are literally made of stardust: the calcium in your bones and the iron in your blood were forged inside ancient stars and scattered by supernovae billions of years before Earth existed.',
                'quiz': [
                    {'q': 'What powers a main-sequence star?', 'options': ['Burning coal', 'Hydrogen fusing into helium', 'Radioactive decay', 'Friction from spinning'], 'answer': 1, 'explain': 'Nuclear fusion in the core converts hydrogen to helium, releasing energy that holds the star up against gravity.'},
                    {'q': 'Which star lives LONGEST?', 'options': ['A 20-solar-mass blue giant', 'A 1-solar-mass star like the Sun', 'A 0.5-solar-mass red dwarf', 'They all live equally long'], 'answer': 2, 'explain': 'Small stars fuse fuel slowly and frugally. Red dwarfs can shine for trillions of years — longer than the universe is old so far.'},
                    {'q': 'What will our Sun eventually become?', 'options': ['A black hole', 'A neutron star', 'A white dwarf', 'A supernova remnant'], 'answer': 2, 'explain': 'The Sun is far below the ~8-solar-mass supernova threshold. It will shed its outer layers and settle down as a white dwarf.'},
                    {'q': 'A star of 25 solar masses most likely ends as...', 'options': ['A white dwarf', 'A planetary nebula', 'A red dwarf', 'A black hole'], 'answer': 3, 'explain': 'After its supernova, a core that massive collapses past the neutron-star limit into a black hole.'},
                ],
            },
            {
                'slug': 'scale-of-the-universe',
                'title': 'Scale of the Universe',
                'icon': 'zoom_out_map',
                'minutes': 15,
                'sim': 'space/cosmic-scale',
                'sim_type': '2d',
                'summary': 'Start at the summit of Everest and zoom out through 23 powers of ten to the edge of the observable universe.',
                'objectives': [
                    'Use powers of ten to compare wildly different sizes',
                    'Order cosmic structures from Earth to the observable universe',
                    'Convert between metres and light-years at each scale',
                    'Appreciate how much of the universe is empty space',
                ],
                'knowledge': [
                    {'heading': 'Counting zeros instead of metres', 'body': 'When sizes range from mountains to galaxies, ordinary numbers fail. Scientists use powers of ten: 10\u00b3 m is a kilometre, 10\u2077 m spans the Earth, 10\u00b9\u2076 m reaches the nearest star. Each step multiplies by ten, so a few dozen steps cover the entire universe.\n\nOur zoom starts at home: Mount Everest, 8,849 m — call it 10\u2074 m. Sagarmatha is the tallest thing on Earth, yet it is about to vanish into a pixel within the first three steps of the journey.'},
                    {'heading': 'From Everest to the Sun', 'body': 'Zoom out: Earth is 1.27 \u00d7 10\u2077 m across — about 1,400 Everests laid end to end. The Moon orbits 3.8 \u00d7 10\u2078 m away; all the other planets could fit side by side in that gap.\n\nThe Sun spans 1.4 \u00d7 10\u2079 m, over a hundred Earths wide, and sits 1.5 \u00d7 10\u00b9\u00b9 m from us — a distance defined as 1 astronomical unit (AU). Neptune orbits 30 AU out, and the whole planetary system spans roughly 10\u00b9\u00b3 m. Light crosses it in about eight hours.'},
                    {'heading': 'The great emptiness between stars', 'body': 'Now comes the shock. The next landmark after the solar system is Proxima Centauri, the nearest star — 4 \u00d7 10\u00b9\u2076 m away, 4.2 light-years. That is a gap several thousand times wider than the entire solar system, containing almost nothing.\n\nIf the Sun were a marble in Kathmandu, Proxima would be another marble near Delhi. Voyager 1, the fastest-travelling human object, would need over 70,000 years to cover such a distance. Interstellar space is emptiness on a scale our minds never evolved to picture.'},
                    {'heading': 'Galaxies, clusters, horizon', 'body': 'Keep zooming. The Milky Way\u2019s disk spans about 10\u00b2\u00b9 m (100,000 light-years). It belongs to the Local Group — dozens of galaxies including Andromeda — about 10\u00b2\u00b3 m across, which in turn sits within superclusters and cosmic filaments.\n\nThe journey ends at the observable universe: 8.8 \u00d7 10\u00b2\u2076 m, about 93 billion light-years across, holding an estimated two trillion galaxies. That is not the whole universe — only the part whose light has had 13.8 billion years to reach us. Beyond the horizon, the cosmos continues... farther than we can ever see.'},
                ],
                'fun_fact': 'There are roughly 10 times more stars in the observable universe than grains of sand on every beach and desert on Earth — yet atoms are so small that a single glass of water holds more molecules than there are stars.',
                'quiz': [
                    {'q': 'Each step in a powers-of-ten zoom multiplies the scale by...', 'options': ['2', '10', '100', '1,000'], 'answer': 1, 'explain': 'One power of ten = one factor of 10. From 10\u2074 m to 10\u2075 m, everything is ten times wider.'},
                    {'q': 'Which is the correct order, smallest to largest?', 'options': ['Sun, Earth, Milky Way, solar system', 'Earth, Sun, solar system, Milky Way', 'Earth, solar system, Sun, Milky Way', 'Solar system, Earth, Sun, Milky Way'], 'answer': 1, 'explain': 'Earth (10\u2077 m) < Sun (10\u2079 m) < solar system (10\u00b9\u00b3 m) < Milky Way (10\u00b2\u00b9 m).'},
                    {'q': 'How far is the nearest star beyond the Sun?', 'options': ['About 4.2 light-minutes', 'About 4.2 light-years', 'About 42 light-years', 'About 4,200 light-years'], 'answer': 1, 'explain': 'Proxima Centauri lies about 4.2 light-years away — roughly 40 trillion kilometres of almost completely empty space.'},
                    {'q': 'The observable universe is about...', 'options': ['93 million km wide', '93 light-years wide', '93 billion light-years wide', 'Infinite — we can see all of it'], 'answer': 2, 'explain': 'About 93 billion light-years across — and that is only the portion whose light has reached us in 13.8 billion years.'},
                ],
            },
        ],
    },
]
