COURSES = [
    {
        'slug': 'block-coding-adventure',
        'title': 'Block Coding Adventure',
        'category': 'coding',
        'age_range': '8-12',
        'level': 'Beginner',
        'icon': 'extension',
        'color': '#EC4899',
        'tagline': 'Guide a cute robot through mazes by snapping colourful code blocks together — no typing needed!',
        'description': 'The friendliest possible start to programming. Drag and snap blocks to command a robot through maze puzzles, and along the way absorb the three big ideas behind every program ever written: sequences, loops and conditionals. Each lesson is a game with levels, a guide character named Neby, and celebrations when you win. By the end you will think like a programmer — before ever typing a line of code.',
        'skills': ['Sequencing instructions', 'Loops and repetition', 'If-conditions and decisions', 'Debugging step by step', 'Computational thinking'],
        'lessons': [
            {
                'slug': 'first-steps',
                'title': 'First Steps: Robot on a Mission',
                'icon': 'smart_toy',
                'minutes': 15,
                'sim': 'coding/lesson-first-steps',
                'sim_type': 'coding',
                'summary': 'Snap move and turn blocks into a program and guide the robot to the star across 3 maze levels.',
                'objectives': [
                    'Build a program by snapping blocks into a sequence',
                    'Predict where the robot will end up before pressing Run',
                    'Fix a buggy program by checking each step in order',
                    'Use the Step button to watch one instruction at a time',
                ],
                'knowledge': [
                    {'heading': 'A program is a recipe', 'body': 'A computer program is simply a list of instructions, followed one at a time, from top to bottom. It works exactly like a recipe: first crack the egg, then beat it, then pour it in the pan. Swap two steps and you get a mess! In this lesson each block is one instruction, and your robot follows your list exactly. Computers never guess, never skip ahead, and never "know what you meant" — that is both their superpower and the reason programming feels tricky at first.'},
                    {'heading': 'The order matters', 'body': 'Programmers call an ordered list of instructions a sequence. If the robot must walk two squares and then turn, the blocks must appear in exactly that order. When your robot bumps a wall, it almost always means one instruction is wrong or out of order. Reading your program from top to bottom while imagining the robot moving — programmers call this tracing — is the single most useful skill you will learn today, and professionals do it every single day.'},
                    {'heading': 'Bugs are normal', 'body': 'When a program does the wrong thing, the mistake is called a bug. The name became popular in 1947 when engineers found an actual moth stuck inside the Harvard Mark II computer! Every programmer on Earth writes bugs every day — beginners and experts alike. What makes someone a good programmer is not avoiding bugs, but calmly finding them. Use the Step button to run your blocks one at a time and watch exactly where the robot goes wrong. That is real debugging.'},
                ],
                'fun_fact': 'The first ever computer programmer was Ada Lovelace, who wrote an algorithm in 1843 — about a century before any computer existed to run it!',
                'quiz': [
                    {'q': 'What is a computer program?', 'options': ['A magic spell the computer understands', 'An ordered list of instructions the computer follows exactly', 'A type of computer game', 'A drawing of a robot'], 'answer': 1, 'explain': 'A program is a sequence of instructions executed one at a time, in order — just like a recipe.'},
                    {'q': 'Your robot needs to go forward 2 squares then turn left. Which program works?', 'options': ['turn left, move, move', 'move, turn left, move', 'move, move, turn left', 'turn left, turn left, move'], 'answer': 2, 'explain': 'Sequences run top to bottom, so both moves must come before the turn.'},
                    {'q': 'What is the best first step when your program has a bug?', 'options': ['Delete everything and give up', 'Run it again hoping it fixes itself', 'Step through the instructions one at a time to find where it goes wrong', 'Add more random blocks'], 'answer': 2, 'explain': 'Tracing the program step by step shows exactly which instruction sends the robot the wrong way.'},
                ],
            },
            {
                'slug': 'loop-the-loop',
                'title': 'Loop the Loop',
                'icon': 'repeat',
                'minutes': 20,
                'sim': 'coding/lesson-loops',
                'sim_type': 'coding',
                'summary': 'Discover the repeat block and solve long mazes with tiny programs — can you beat each level\'s block-count challenge?',
                'objectives': [
                    'Spot repeating patterns in a path before coding it',
                    'Use the repeat block to run other blocks many times',
                    'Solve each maze using the fewest blocks possible',
                    'Nest moves and turns inside one loop to walk a staircase',
                ],
                'knowledge': [
                    {'heading': 'Why loops exist', 'body': 'Imagine telling the robot to walk 100 squares by stacking 100 move blocks — exhausting! Programmers are proudly lazy in a clever way: when work repeats, they wrap it in a loop and let the computer do the repeating. The repeat block runs everything inside it a chosen number of times. Six moves becomes "repeat 6: move" — two blocks instead of six. Real programs use loops constantly: drawing every pixel on your screen, checking every message in your inbox, playing every frame of a video.'},
                    {'heading': 'Find the pattern first', 'body': 'The secret to using loops well is spotting the repeating pattern before you build anything. Look at the staircase maze: the robot does move, turn, move, turn... the same little dance over and over. Once you can say the pattern out loud — "move then turn left then move then turn right, three times" — translating it into a repeat block is easy. Pattern-spotting is a deep skill: scientists, mathematicians and programmers all hunt for patterns because one small rule can describe something huge.'},
                    {'heading': 'Smaller programs are better programs', 'body': 'Each level shows a block-count challenge like "solve with 5 blocks or fewer". Why care, if a long program also works? Because shorter programs have fewer places for bugs to hide, are faster to read, and are easier to change later. Professional programmers spend much of their time making working code shorter and clearer — they call it refactoring. If your solution uses 12 blocks, ask yourself: what is repeating? Wrap it in a loop and watch your program shrink.'},
                ],
                'fun_fact': 'The word "loop" survives from the earliest days of computing, when programs were stored on punched paper tape — to repeat a section, operators literally taped the ends together into a physical loop!',
                'quiz': [
                    {'q': 'The robot must move forward 8 squares. What is the shortest program?', 'options': ['8 move blocks in a row', 'repeat 8 containing 1 move block', 'repeat 4 containing 4 move blocks', '1 move block'], 'answer': 1, 'explain': 'Repeat 8 with a single move inside does all 8 steps using only 2 blocks.'},
                    {'q': 'What does a repeat-3 block containing [move, turn right] do?', 'options': ['Moves 3 times then turns 3 times', 'Moves once and turns once', 'Does move, turn right, move, turn right, move, turn right', 'Turns right 3 times then moves 3 times'], 'answer': 2, 'explain': 'A loop runs its whole inside, in order, each time around — the full pattern repeats 3 times.'},
                    {'q': 'Why do programmers prefer shorter programs that use loops?', 'options': ['Long programs are illegal', 'Fewer blocks means fewer places for bugs and easier changes', 'Loops make the robot walk faster', 'Computers cannot run more than 10 blocks'], 'answer': 1, 'explain': 'Shorter, pattern-based code is easier to read, debug and modify — that is why loops matter.'},
                ],
            },
            {
                'slug': 'smart-choices',
                'title': 'Smart Choices',
                'icon': 'alt_route',
                'minutes': 20,
                'sim': 'coding/lesson-conditionals',
                'sim_type': 'coding',
                'summary': 'Give your robot a brain! The if-path-ahead block lets the robot check before it moves — combine it with loops to crack a giant spiral maze.',
                'objectives': [
                    'Use the if-path-ahead block to run blocks only when the way is clear',
                    'Protect the robot from crashes with a conditional safety check',
                    'Combine repeat and if blocks into one smart pattern',
                    'Solve a maze your blocks were never measured for',
                ],
                'knowledge': [
                    {'heading': 'Programs that decide', 'body': 'So far your robot has been brave but blind — it moves even when a wall is in the way. The if-path-ahead block changes everything: blocks inside it only run when the path in front of the robot is clear. This is called a conditional, and it is how programs make decisions. Your phone uses conditionals millions of times a day: IF the battery is low, dim the screen. IF the password matches, unlock. IF a message arrives, buzz.'},
                    {'heading': 'Look before you leap', 'body': 'Put a move block inside an if-path-ahead block and the robot becomes crash-proof: it checks the square ahead, moves when it is open, and calmly does nothing when it is blocked. That means a loop can safely run "too many" times — extra rounds simply do nothing once the robot reaches a wall. This is a real engineering idea called a guard: code that checks conditions before acting. Guards are why a well-built app refuses to crash even when something unexpected happens.'},
                    {'heading': 'One pattern, any maze', 'body': 'Here is the magic of combining your three powers. The pattern "repeat: walk while the path is clear, then turn right" follows walls around corners without knowing the maze in advance! Sequences, loops and conditionals are the three building blocks of all software — from games to rockets. Computer scientists proved that any program, no matter how complex, can be built from just these three structures. Master them and you understand the skeleton of every app you have ever used.'},
                ],
                'fun_fact': 'Maze-solving robots are a real sport! In Micromouse competitions, palm-sized robots explore an unknown maze, then race to the centre — the fastest do it in under 5 seconds.',
                'quiz': [
                    {'q': 'What does the if-path-ahead block do?', 'options': ['Always moves the robot forward', 'Runs its inside blocks only when the square ahead is clear', 'Turns the robot toward the star', 'Deletes walls from the maze'], 'answer': 1, 'explain': 'It is a conditional: the blocks inside run only if the condition "path ahead is clear" is true.'},
                    {'q': 'A move block sits inside if-path-ahead, and a wall is directly ahead. What happens?', 'options': ['The robot crashes into the wall', 'The robot moves through the wall', 'Nothing — the move is safely skipped', 'The program stops with an error'], 'answer': 2, 'explain': 'When the condition is false, the inside blocks are skipped — that is what makes the robot crash-proof.'},
                    {'q': 'Which three structures can build any program ever written?', 'options': ['Sequences, loops and conditionals', 'Robots, mazes and stars', 'Keyboards, mice and screens', 'Numbers, letters and emoji'], 'answer': 0, 'explain': 'Computer science\'s structured program theorem says all programs can be built from just these three.'},
                ],
            },
        ],
    },
    {
        'slug': 'web-wizard',
        'title': 'Web Wizard: HTML & CSS',
        'category': 'coding',
        'age_range': '10-16',
        'level': 'Beginner',
        'icon': 'language',
        'color': '#DB2777',
        'tagline': 'Write real HTML and CSS in a live editor and watch your own webpage appear instantly.',
        'description': 'Every website you have ever visited — Google, YouTube, your school\'s site — is built from HTML and CSS. In this course you type real code into a live editor and see your page update the moment you press Run. Learn the essential tags, style them with colours and layouts, then build a complete About Me page that is one hundred percent yours. Neby checks your goals automatically and celebrates every win.',
        'skills': ['HTML tags and structure', 'CSS selectors and properties', 'Colours, backgrounds and borders', 'Page layout basics', 'Building a complete webpage'],
        'lessons': [
            {
                'slug': 'html-building-blocks',
                'title': 'HTML Building Blocks',
                'icon': 'code',
                'minutes': 20,
                'sim': 'coding/lesson-html-basics',
                'sim_type': 'coding',
                'summary': 'Write your first real HTML: headings, paragraphs, images and lists, with a live preview that updates as you go.',
                'objectives': [
                    'Write opening and closing tags that wrap content',
                    'Add a heading, paragraph, image and list to a page',
                    'Understand what the browser does with your tags',
                    'Use attributes like src and alt inside a tag',
                ],
                'knowledge': [
                    {'heading': 'Tags are labelled containers', 'body': 'HTML — HyperText Markup Language — describes what each piece of a page IS. You wrap content in tags: <h1>Hello</h1> says "this is a top-level heading", <p> marks a paragraph, <ul> with <li> items makes a bullet list. Most tags come in pairs: an opening tag and a closing tag with a slash. Think of them as labelled boxes — the browser reads the label and displays the contents the right way. Forget a closing tag and the browser has to guess where your box ends!'},
                    {'heading': 'Some tags stand alone', 'body': 'A few tags do not wrap anything, so they have no closing partner. The image tag is the famous one: <img src="picture.png" alt="my photo"> places a picture. The extra pieces inside the tag are attributes — settings written as name="value". The src attribute says where the picture lives, and alt provides words that screen readers speak aloud for blind users, and that appear if the image fails to load. Good alt text makes the web work for everyone — accessibility is a real superpower.'},
                    {'heading': 'The browser is your translator', 'body': 'When you press Run, the browser reads your HTML from top to bottom and builds the page — big bold text for headings, spaced blocks for paragraphs, bullets for list items. Notice what HTML does NOT control: colours, fonts and fancy layouts. HTML is purely about meaning and structure. The decoration comes from CSS, which you will meet in the next lesson. Keeping structure (HTML) separate from style (CSS) is exactly how professional websites are organised.'},
                ],
                'fun_fact': 'The very first website ever made, created by Tim Berners-Lee in 1991, is still online at its original address — and it is written in the same HTML you are learning right now.',
                'quiz': [
                    {'q': 'What does <h1> mean in HTML?', 'options': ['A hyperlink', 'The most important heading on the page', 'A hidden element', 'A horizontal line'], 'answer': 1, 'explain': 'h1 is the top-level heading; h2 to h6 are smaller sub-headings.'},
                    {'q': 'Which is the correct way to write a paragraph?', 'options': ['<p>Hello</p>', '<paragraph>Hello', 'p: Hello', '(p) Hello (p)'], 'answer': 0, 'explain': 'Content goes between an opening <p> and a closing </p> tag.'},
                    {'q': 'What is the alt attribute on an image for?', 'options': ['Making the image bigger', 'Describing the image for screen readers and when it fails to load', 'Adding a colourful border', 'Making the image clickable'], 'answer': 1, 'explain': 'alt text keeps pages usable for blind visitors and when images cannot load — it is essential for accessibility.'},
                ],
            },
            {
                'slug': 'css-magic',
                'title': 'CSS Magic',
                'icon': 'palette',
                'minutes': 20,
                'sim': 'coding/lesson-css-basics',
                'sim_type': 'coding',
                'summary': 'Bring a plain page to life with CSS: colours, backgrounds, rounded corners and centred text — instantly visible in the preview.',
                'objectives': [
                    'Write CSS rules with selectors, properties and values',
                    'Colour text and backgrounds on real elements',
                    'Round corners with border-radius and centre text',
                    'Target elements by tag name and by class',
                ],
                'knowledge': [
                    {'heading': 'Selectors are name tags', 'body': 'A CSS rule has two parts: a selector that picks WHICH elements to style, and declarations that say HOW. Writing h1 { color: hotpink; } means "find every h1 and paint its text hot pink". The selector is like calling a name in a classroom — everyone with that name stands up. Tag selectors like h1 or p choose every element of that kind, while a class selector like .card chooses only elements you have labelled with class="card". One rule can restyle a hundred elements at once.'},
                    {'heading': 'Properties and values', 'body': 'Inside the curly braces go declarations: property, colon, value, semicolon. color changes text colour, background-color fills behind an element, border-radius rounds the corners, and text-align: center centres the content. Colours can be names like tomato, or hex codes like #EC4899 — six digits describing red, green and blue light. Miss a semicolon and the browser may quietly ignore the next line, so when a style mysteriously fails, check your punctuation first!'},
                    {'heading': 'The cascade', 'body': 'The C in CSS stands for cascading: rules flow together, and when two rules disagree, the more specific one — or the one written later — wins. Style every paragraph grey, then give one special paragraph a class with red text, and that paragraph follows the red rule because a class beats a plain tag selector. Designers use the cascade deliberately: broad rules set the general look of a site, then a handful of specific rules handle the exceptions.'},
                ],
                'fun_fact': 'CSS can do animation, 3D transforms and even some game logic — people have built entire playable games (and a working flight simulator instrument panel!) using only CSS, with zero JavaScript.',
                'quiz': [
                    {'q': 'In h1 { color: blue; }, what is h1 called?', 'options': ['The property', 'The value', 'The selector', 'The attribute'], 'answer': 2, 'explain': 'The selector chooses which elements get the style — here, every h1 on the page.'},
                    {'q': 'Which property makes corners round?', 'options': ['corner-style', 'border-radius', 'round-corners', 'circle'], 'answer': 1, 'explain': 'border-radius curves the corners — a big value can even turn a square into a circle.'},
                    {'q': 'Two rules give the same paragraph different colours. Which generally wins?', 'options': ['The first one written', 'The one with red in it', 'The more specific selector, or the later rule if they tie', 'Neither — the page crashes'], 'answer': 2, 'explain': 'That is the cascade: specificity first, then order. A class selector beats a plain tag selector.'},
                ],
            },
            {
                'slug': 'my-first-webpage',
                'title': 'My First Webpage',
                'icon': 'web',
                'minutes': 25,
                'sim': 'coding/lesson-webpage-project',
                'sim_type': 'coding',
                'summary': 'Project time: combine HTML and CSS to design a complete About Me page — your content, your colours, your style.',
                'objectives': [
                    'Plan and structure a page with headings, paragraphs and lists',
                    'Write at least three CSS rules that style your content',
                    'Choose a colour scheme and apply it consistently',
                    'Personalise a project until it feels truly yours',
                ],
                'knowledge': [
                    {'heading': 'Structure first, style second', 'body': 'Professional web developers build pages in two passes. First comes the HTML skeleton: what sections exist and in what order — a heading for your name, a paragraph introducing you, a list of things you love. Only then comes CSS to make it beautiful. Working this way keeps you organised and mirrors how real teams split work between structure and design. Sketching your page on paper for thirty seconds before typing is a trick even senior developers still use.'},
                    {'heading': 'Make it readable', 'body': 'A few design rules instantly make any page look better. Use contrast: dark text on light backgrounds (or the reverse) so words are easy to read. Use spacing: padding inside boxes and margins between them give content room to breathe. Stick to two or three colours that work together rather than a rainbow. And keep text sizes sensible — one big heading, medium sub-headings, comfortable body text. Designers call this visual hierarchy: the most important thing should look the most important.'},
                    {'heading': 'Personalising is real development', 'body': 'The goals checklist makes sure your page has the essential parts, but everything beyond that is yours: favourite colours, more sections, emoji, borders, a quote you love. This is exactly how real developers grow — start from working code, then change one thing at a time and observe what happens. Experimenting cannot break anything here, and the Start Over button is always there. The best way to learn CSS is to be curious and slightly reckless with it.'},
                ],
                'fun_fact': 'There are over one billion websites on the internet, and every single one — including the page you are reading right now — is built on the same HTML and CSS you just used.',
                'quiz': [
                    {'q': 'What is the recommended order for building a webpage?', 'options': ['CSS first, HTML later', 'HTML structure first, then CSS styling', 'JavaScript first', 'Pick colours first, content last'], 'answer': 1, 'explain': 'Structure first, style second keeps work organised — exactly how professional teams build.'},
                    {'q': 'Why should text contrast strongly with its background?', 'options': ['It uses less electricity', 'It makes the page load faster', 'It keeps the text easy to read for everyone', 'Browsers require it'], 'answer': 2, 'explain': 'Contrast is a core accessibility and design rule — low-contrast text is hard or impossible to read.'},
                    {'q': 'What is the best way to keep learning CSS after this lesson?', 'options': ['Memorise every property in alphabetical order', 'Change one thing at a time and watch what happens', 'Never touch working code', 'Only copy other people\'s pages without reading them'], 'answer': 1, 'explain': 'Experimenting with one change at a time builds real understanding — and you can always start over.'},
                ],
            },
        ],
    },
    {
        'slug': 'javascript-quest',
        'title': 'JavaScript Quest',
        'category': 'coding',
        'age_range': '12-19',
        'level': 'Intermediate',
        'icon': 'bolt',
        'color': '#BE185D',
        'tagline': 'Learn the language of interactivity — variables, functions and DOM magic, with live tests checking your code.',
        'description': 'JavaScript is the programming language that runs in every browser on Earth — it powers games, chat apps, animations and every button that does something. This quest takes you from your first console.log to writing functions that pass hidden tests, and finally to wiring up a real interactive page where your code reacts to clicks. Neby secretly tests your functions with surprise values, so only genuinely working code wins.',
        'skills': ['Variables and expressions', 'Writing and calling functions', 'Console debugging', 'DOM events and listeners', 'Making pages interactive'],
        'lessons': [
            {
                'slug': 'variables-and-numbers',
                'title': 'Variables & Numbers',
                'icon': 'calculate',
                'minutes': 20,
                'sim': 'coding/lesson-js-variables',
                'sim_type': 'coding',
                'summary': 'Meet the console, store values in variables and let JavaScript do your maths — goal checks watch your output live.',
                'objectives': [
                    'Print values to the console with console.log()',
                    'Declare variables with let and const',
                    'Use arithmetic operators on numbers and variables',
                    'Read console output to understand what your code did',
                ],
                'knowledge': [
                    {'heading': 'The console is your laboratory', 'body': 'Every browser hides a programmer\'s playground called the console. console.log() prints anything you give it — text, numbers, calculations — into that panel. It may look humble, but the console is the number one debugging tool in the world: when professionals wonder what their code is doing, they log values and look. In this lesson the console is your whole world. Type an instruction, press Run, read the output. That tight loop — write, run, read — is how all programming works.'},
                    {'heading': 'Variables are labelled boxes', 'body': 'A variable stores a value under a name: let score = 100 creates a box labelled score holding 100. Use the name anywhere and JavaScript opens the box: console.log(score + 25) prints 125. Use let for values that will change and const for ones that never should — the browser will actually stop you from overwriting a const, which catches bugs early. Choose names that say what they hold: playerScore beats x when you read your code next week.'},
                    {'heading': 'JavaScript is a calculator with memory', 'body': 'The operators + - * / work like your maths class, with * for times and / for divide. The percent sign % is the remainder operator: 10 % 3 gives 1, the leftover after dividing — surprisingly useful for things like "is this number even?" Combine operators with variables and you get living formulas: price * quantity, seconds / 60. Unlike a pocket calculator, JavaScript remembers every result you store, so calculations can build on each other line after line.'},
                ],
                'fun_fact': 'JavaScript was created in just 10 days in 1995 by Brendan Eich — and despite the name, it has no relation to the Java language. It was named that purely for marketing!',
                'quiz': [
                    {'q': 'What does console.log(6 * 7) print?', 'options': ['6 * 7', '42', 'Nothing', 'An error'], 'answer': 1, 'explain': 'JavaScript evaluates the expression first, then logs the result: 42.'},
                    {'q': 'Which line correctly creates a variable?', 'options': ['variable score = 10', 'let score = 10', 'score := 10', 'make score 10'], 'answer': 1, 'explain': 'let (or const for unchanging values) followed by a name and = value declares a variable.'},
                    {'q': 'What is 10 % 3?', 'options': ['3.33', '30', '1', '0.3'], 'answer': 2, 'explain': '% gives the remainder after division: 10 divided by 3 is 3 remainder 1.'},
                ],
            },
            {
                'slug': 'functions-in-action',
                'title': 'Functions in Action',
                'icon': 'function',
                'minutes': 20,
                'sim': 'coding/lesson-js-functions',
                'sim_type': 'coding',
                'summary': 'Write reusable functions like double(n) and greet(name) — then watch Neby secretly test them with surprise values.',
                'objectives': [
                    'Define functions with parameters and return values',
                    'Understand the difference between returning and printing',
                    'Write code that passes hidden automated tests',
                    'Reuse one function for many different inputs',
                ],
                'knowledge': [
                    {'heading': 'Functions are machines you build', 'body': 'A function is a reusable machine: values go in through parameters, something comes out through return. function double(n) { return n * 2; } builds a machine named double; calling double(4) feeds in 4 and gets back 8. Define once, use forever — with any input. This is the heart of programming: instead of repeating logic everywhere, you build a well-named machine and call it. Big apps are thousands of small functions calling each other, each doing one job well.'},
                    {'heading': 'Return is not print', 'body': 'console.log shows a value to humans; return hands a value back to the code that called the function. Only return lets results flow onward: console.log(double(5) + 1) works because double returns 10, which becomes 11. A function that only logs is a dead end — nothing can use what it computed. The hidden tests in this lesson call your functions and inspect the returned values, so a function that prints instead of returning will fail even though the right number appears on screen!'},
                    {'heading': 'Tests prove code works', 'body': 'When you press Run, Neby quietly appends extra calls to your code — double(4), double(9.5), greet("Mina"), greet("Ramesh") — and checks the answers. This is automated testing, and it is how serious software is built: every major app runs thousands of automatic tests before each update ships. Notice the trick of testing with several different inputs: code that only works for one special value is not really working. If a hidden test fails, ask: what input might my function handle wrongly?'},
                ],
                'fun_fact': 'Big tech companies run millions of automated tests every day. Google\'s testing systems execute several billion test cases per week — no human could ever check that much by hand.',
                'quiz': [
                    {'q': 'What does function double(n) { return n * 2; } then double(8) give?', 'options': ['n * 2', '16', 'double', 'Nothing'], 'answer': 1, 'explain': 'The argument 8 becomes n, and the function returns 8 * 2 = 16.'},
                    {'q': 'Why is return better than console.log inside a function?', 'options': ['It prints in nicer colours', 'It hands the result back so other code can use it', 'It runs faster', 'It is shorter to type'], 'answer': 1, 'explain': 'Returned values can flow into calculations, other functions and tests; logged values can only be read by humans.'},
                    {'q': 'Why do tests try your function with several different values?', 'options': ['To slow your program down', 'Because code that works for only one value is not really correct', 'To fill up the console', 'Tests are required by law'], 'answer': 1, 'explain': 'Multiple varied inputs — including tricky ones — prove the function genuinely works in general.'},
                ],
            },
            {
                'slug': 'make-it-interactive',
                'title': 'Make It Interactive',
                'icon': 'touch_app',
                'minutes': 25,
                'sim': 'coding/lesson-js-dom',
                'sim_type': 'coding',
                'summary': 'Connect JavaScript to a real page: listen for button clicks, change text and colours, and count every click.',
                'objectives': [
                    'Find page elements with document.getElementById',
                    'React to clicks using addEventListener',
                    'Change text and styles from inside event code',
                    'Keep state with a counter variable across clicks',
                ],
                'knowledge': [
                    {'heading': 'The DOM: your page as objects', 'body': 'When the browser loads HTML it builds the DOM — the Document Object Model — a live structure where every tag becomes an object JavaScript can grab and change. document.getElementById("magic-btn") fetches the element whose id is magic-btn; then msg.textContent = "Hi!" rewrites its text instantly, no reload needed. Every like-button animation, every chat message appearing, every dark-mode toggle you have ever seen is JavaScript editing the DOM exactly like this.'},
                    {'heading': 'Events: giving your page ears', 'body': 'Pages sit still until something happens: a click, a key press, a finger scroll. These are events, and addEventListener lets your code listen for them: btn.addEventListener("click", function () { ... }) means "when this button is clicked, run this code". The function you hand over is called a callback — it waits patiently and fires every time the event occurs. This style is event-driven programming, and it is how every interactive interface on Earth is wired together.'},
                    {'heading': 'Remembering with state', 'body': 'How does a page count clicks? With a variable declared OUTSIDE the event function: let clicks = 0. Each click runs clicks++ and writes the new number into the page. Because the variable lives outside, it survives between clicks — programmers call this state. Get the placement wrong (declare it inside the callback) and it resets to zero every click, stuck forever at 1. From game scores to shopping carts, managing state is one of the central challenges of real app development.'},
                ],
                'fun_fact': 'The average modern webpage runs hundreds of event listeners at once — tracking clicks, scrolls, key presses and touches simultaneously. Your browser juggles them all without breaking a sweat.',
                'quiz': [
                    {'q': 'What does addEventListener("click", myFunction) do?', 'options': ['Clicks the button automatically', 'Runs myFunction immediately', 'Runs myFunction every time the element is clicked', 'Deletes the button'], 'answer': 2, 'explain': 'It registers a callback: the function waits and fires on each click event.'},
                    {'q': 'Which line changes the words inside an element?', 'options': ['element.textContent = "New text"', 'element.words("New text")', 'element = "New text"', 'text(element, "New")'], 'answer': 0, 'explain': 'Setting textContent replaces the element\'s text instantly in the live page.'},
                    {'q': 'For a click counter, where must let clicks = 0 go?', 'options': ['Inside the click function', 'Outside the click function', 'In the HTML', 'Nowhere — counters are automatic'], 'answer': 1, 'explain': 'Declared outside, the variable persists between clicks; inside, it would reset to 0 on every click.'},
                ],
            },
        ],
    },
    {
        'slug': 'python-playground',
        'title': 'Python Playground',
        'category': 'coding',
        'age_range': '12-19',
        'level': 'Intermediate',
        'icon': 'data_object',
        'color': '#9D174D',
        'tagline': 'Write and run real Python in your browser — from your first print() to a working NEB grade calculator.',
        'description': 'Python is the world\'s most popular programming language — the one behind AI, data science, and the tools at NASA and Google. This course runs real Python right in your browser: type code, press Run, see output instantly. Learn printing and f-strings, master loops and logic, build functions that pass Neby\'s secret tests, and finish with a real project: a NEB marks-to-grade calculator. Friendly error messages point you at the exact line whenever something goes wrong.',
        'skills': ['Python syntax and printing', 'Variables and f-strings', 'Loops, conditions and logic', 'Lists and functions', 'Building a complete program'],
        'lessons': [
            {
                'slug': 'hello-python',
                'title': 'Hello, Python!',
                'icon': 'waving_hand',
                'minutes': 15,
                'sim': 'coding/lesson-py-hello',
                'sim_type': 'coding',
                'summary': 'Your first real Python: print messages, store values in variables, and weave them into sentences with f-strings.',
                'objectives': [
                    'Run Python code and read its output',
                    'Print text and numbers with print()',
                    'Store text and numbers in variables',
                    'Build sentences with f-strings and {curly} slots',
                ],
                'knowledge': [
                    {'heading': 'Python reads like English', 'body': 'Python was designed to be the most readable programming language ever, and it shows: print("Namaste") does exactly what it says. There are no semicolons to forget and no curly braces to balance — Python uses plain indentation to organise code. That friendliness is why Python is the most taught first language in the world, yet the same language drives YouTube\'s backend, Instagram\'s servers and most of modern artificial intelligence research. Easy to start, almost impossible to outgrow.'},
                    {'heading': 'Variables without ceremony', 'body': 'Creating a variable in Python is one line: name = "Mina" or age = 16. No special keyword needed — the equals sign means "store the right side under the left side\'s name". Text values, called strings, must sit inside quotes; numbers stand bare. The difference matters: "16" in quotes is text, while 16 is a number you can do maths with. If Python complains it cannot add text and numbers, wrap the number in str() to convert it first.'},
                    {'heading': 'f-strings: fill-in-the-blank sentences', 'body': 'The slickest way to mix variables into text is the f-string: put an f before the opening quote, then write {variable} wherever a value should appear. print(f"My name is {name} and I am {age}") fills both slots automatically. The braces can even hold maths: f"{6 * 7}" becomes 42. Compared with gluing strings together using plus signs, f-strings are shorter, cleaner and much harder to get wrong — modern Python code uses them everywhere.'},
                ],
                'fun_fact': 'Python is not named after the snake! Creator Guido van Rossum named it after the British comedy group Monty Python — which is why Python examples are full of jokes and silly names.',
                'quiz': [
                    {'q': 'What does print("Hello" ) do?', 'options': ['Sends Hello to a printer', 'Shows Hello in the output', 'Saves Hello to a file', 'Nothing'], 'answer': 1, 'explain': 'print() writes its value to the program\'s output so you can see it.'},
                    {'q': 'Which creates a text variable correctly?', 'options': ['name = Mina', 'name = "Mina"', 'text name: Mina', 'let name = "Mina"'], 'answer': 1, 'explain': 'Strings need quotes, and Python needs no special keyword — just name = "value".'},
                    {'q': 'With city = "Pokhara", what does print(f"I live in {city}") show?', 'options': ['I live in {city}', 'I live in city', 'I live in Pokhara', 'An error'], 'answer': 2, 'explain': 'The f-string replaces {city} with the variable\'s value: Pokhara.'},
                ],
            },
            {
                'slug': 'loops-and-logic',
                'title': 'Loops & Logic',
                'icon': 'all_inclusive',
                'minutes': 20,
                'sim': 'coding/lesson-py-loops',
                'sim_type': 'coding',
                'summary': 'Count with for and range, decide with if/elif/else, repeat with while — then beat the Fizz boss challenge.',
                'objectives': [
                    'Repeat code with for loops and range()',
                    'Branch with if, elif and else',
                    'Use while for loops that run until a condition changes',
                    'Combine a loop and a condition to solve Fizz',
                ],
                'knowledge': [
                    {'heading': 'for and the range trick', 'body': 'Python\'s for loop walks through a sequence of values: for i in range(1, 11): runs its indented body ten times with i counting 1, 2, 3... up to 10. Watch the famous catch: range stops just BEFORE its end number, so range(1, 11) is needed to reach 10. A third value sets the step — range(10, 0, -1) counts backwards. Everything indented under the for line belongs to the loop; the indentation IS the grammar in Python.'},
                    {'heading': 'Decisions with if, elif, else', 'body': 'if checks a condition: when true, its indented block runs. elif (short for else-if) offers more checks in order, and else catches everything left over. Python tests them top to bottom and runs only the FIRST match, so order matters: check the biggest mark band first when grading. Conditions use comparisons — ==, !=, <, >=, plus % for remainders. n % 2 == 0 asks "does n divide evenly by 2?" — the classic even-number test you will use in this lesson.'},
                    {'heading': 'while: loop until', 'body': 'A while loop repeats as long as its condition stays true: countdown = 5, then while countdown > 0: print it and subtract one. Something inside the loop must move toward making the condition false — forget the subtraction and you have an infinite loop that never ends! (Try it here: this playground stops runaway programs automatically and tells you.) Use for when you know how many times to repeat; use while when you only know the stopping condition.'},
                ],
                'fun_fact': 'FizzBuzz, the challenge at the end of this lesson, is a real interview question used by software companies — and famously, a surprising number of professional applicants get it wrong. You won\'t!',
                'quiz': [
                    {'q': 'What numbers does for i in range(1, 5) give?', 'options': ['1, 2, 3, 4, 5', '1, 2, 3, 4', '0, 1, 2, 3, 4', '5, 4, 3, 2, 1'], 'answer': 1, 'explain': 'range stops just before its end value, so range(1, 5) produces 1 through 4.'},
                    {'q': 'How do you check whether n is even?', 'options': ['n / 2 == 0', 'n % 2 == 0', 'n * 2 == 0', 'n == even'], 'answer': 1, 'explain': 'n % 2 is the remainder after dividing by 2 — zero remainder means even.'},
                    {'q': 'What happens if a while loop\'s condition never becomes false?', 'options': ['Python fixes it automatically', 'The loop runs forever — an infinite loop', 'The loop runs exactly once', 'The computer prints a warning and continues'], 'answer': 1, 'explain': 'Nothing stops it, so it loops forever — which is why something inside must change the condition.'},
                ],
            },
            {
                'slug': 'lists-and-functions',
                'title': 'Lists & Functions',
                'icon': 'list_alt',
                'minutes': 20,
                'sim': 'coding/lesson-py-functions',
                'sim_type': 'coding',
                'summary': 'Store collections in lists, grow them with append, and write functions that survive Neby\'s secret tests — including biggest().',
                'objectives': [
                    'Create lists and read items by index',
                    'Grow lists with append() and measure them with len()',
                    'Define functions with def, parameters and return',
                    'Write a biggest() function that works on any list',
                ],
                'knowledge': [
                    {'heading': 'Lists: many values, one name', 'body': 'A list holds many values in order: scores = [72, 95, 88]. Each item has a position called an index, counting from ZERO: scores[0] is 72 and scores[2] is 88. Negative indexes count from the end — scores[-1] is the last item, a beloved Python shortcut. Add new items with scores.append(100), count them with len(scores), and loop through them with for s in scores:. Lists are Python\'s workhorse — marks, players, messages, sensor readings — anything plural lives in a list.'},
                    {'heading': 'def: building your own commands', 'body': 'You have used built-in functions like print() and len(); def lets you create your own. Write def biggest(numbers): then an indented body, and end with return to send the answer back. Parameters make functions flexible — biggest works on ANY list you pass it, not one specific list. The classic pattern for finding a maximum: start with best = numbers[0], loop through the list, and whenever an item beats best, replace it. Three lines that feel like magic the first time they work.'},
                    {'heading': 'Surviving the secret tests', 'body': 'Neby checks your functions by secretly running extra code: print(biggest([3, 41, 7])) must say 41, and print(biggest([-9, -2, -7])) must say -2. That negative test catches a sneaky classic bug: starting best = 0 works for positive lists but fails when every number is below zero — the correct start is the list\'s own first item. Thinking about edge cases like this is precisely what separates code that seems to work from code that truly works.'},
                ],
                'fun_fact': 'Python\'s len() function is one of the most-called functions in the world — it is used billions of times daily across data science notebooks, web servers and AI training pipelines.',
                'quiz': [
                    {'q': 'With scores = [10, 20, 30], what is scores[1]?', 'options': ['10', '20', '30', 'An error'], 'answer': 1, 'explain': 'Indexes start at 0, so index 1 is the second item: 20.'},
                    {'q': 'Why should biggest() start with best = numbers[0] instead of best = 0?', 'options': ['It runs faster', 'Zero is unlucky', 'With all-negative lists, 0 would wrongly win', 'numbers[0] is always the biggest'], 'answer': 2, 'explain': 'If every number is negative, none beats 0 — starting from the first real item handles all cases.'},
                    {'q': 'What does scores.append(50) do?', 'options': ['Replaces the whole list with 50', 'Adds 50 to the end of the list', 'Removes the number 50', 'Sorts the list'], 'answer': 1, 'explain': 'append() grows the list by one item, added at the end.'},
                ],
            },
            {
                'slug': 'final-quest',
                'title': 'Final Quest: Grade Calculator',
                'icon': 'workspace_premium',
                'minutes': 25,
                'sim': 'coding/lesson-py-project',
                'sim_type': 'coding',
                'summary': 'The graduation project: build a real NEB marks-to-grade calculator with grade bands, averages and a formatted report.',
                'objectives': [
                    'Translate a real grading table into if/elif logic',
                    'Compute an average with sum-style accumulation',
                    'Loop over a list to print a formatted report',
                    'Assemble functions, loops and lists into one program',
                ],
                'knowledge': [
                    {'heading': 'From real rules to code', 'body': 'Real programs start as human rules. The NEB grading table — 90 and above is A+, 80 to 89 is A, 70 to 79 is B+, and so on — translates almost word-for-word into an if/elif chain. The elegant trick: check from the TOP band downward. Once you know m is not 90+, testing m >= 80 alone is enough for an A — no upper bound needed, because earlier checks already caught higher marks. Order your conditions carefully and the logic becomes short and bulletproof.'},
                    {'heading': 'Averages and accumulators', 'body': 'To average a list, add everything up and divide by the count. The adding-up uses a pattern you will reuse forever: the accumulator. Start total = 0, loop for n in nums:, add each with total += n, and after the loop divide by len(nums). (Python\'s built-in sum() does the same job in one call — using it is absolutely allowed!) Accumulators appear everywhere: totalling a shopping cart, counting votes, summing rainfall. Learn the shape once, use it for life.'},
                    {'heading': 'Programs are assembled, not written', 'body': 'Notice how the final program snaps together from pieces you already own: a grade() function from if/elif, an average() from a loop, a report from for plus f-strings. This is the deepest lesson in the whole course — big software is never written in one heroic effort. It is assembled from small, tested parts. Build a piece, run it, watch it work, then build the next. Every app on your phone, including this one, was built exactly this way.'},
                ],
                'fun_fact': 'Nepal\'s NEB switched to letter grading in 2072 BS (2015/16 AD) — and the conversion logic schools use is essentially the same if/elif chain you are writing in this very lesson.',
                'quiz': [
                    {'q': 'Why check m >= 90 before m >= 80 in the grade function?', 'options': ['Alphabetical order', 'Python requires biggest numbers first', 'elif runs only the first true branch, so higher bands must be caught first', 'It makes the code run faster'], 'answer': 2, 'explain': 'If m >= 80 came first, a mark of 95 would wrongly stop there and get an A instead of A+.'},
                    {'q': 'What is the accumulator pattern for summing a list?', 'options': ['total = 0, then total += n inside a loop', 'print every number and add by hand', 'total = nums[0] * len(nums)', 'Lists sum themselves automatically'], 'answer': 0, 'explain': 'Start at zero, add each item as the loop visits it — the universal totalling pattern.'},
                    {'q': 'What is the professional way to build a bigger program?', 'options': ['Write all of it, then run it once at the end', 'Build and test one small piece at a time', 'Copy code until something works', 'Avoid functions to keep it simple'], 'answer': 1, 'explain': 'Assembling tested pieces step by step is how all real software is built — and how you built this quest.'},
                ],
            },
        ],
    },
    {
        'slug': 'code-master-challenges',
        'title': 'Code Master Challenges',
        'category': 'coding',
        'age_range': '14-19',
        'level': 'Advanced',
        'icon': 'military_tech',
        'color': '#831843',
        'tagline': 'Four boss-level builds — a real stopwatch, generative canvas art, a data analyser and a word game engine.',
        'description': 'You know the pieces; now build the machines. Code Master Challenges hands you four open-ended engineering problems and a live editor: a stopwatch driven by timers and state, generative art painted onto a canvas with loops and colour maths, a Python data analyser that turns raw exam scores into a report, and the complete logic core of a word-guessing game. Neby checks your goals automatically, but the design decisions are yours — exactly like real software work.',
        'skills': ['Timers and asynchronous events', 'Canvas drawing and colour maths', 'Aggregating data with loops', 'Membership tests and game logic', 'Decomposing problems into steps', 'Debugging multi-part programs'],
        'lessons': [
            {
                'slug': 'build-a-stopwatch',
                'title': 'Build a Stopwatch',
                'icon': 'timer',
                'minutes': 15,
                'sim': 'coding/lesson-js-stopwatch',
                'sim_type': 'coding',
                'summary': 'Engineer a working stopwatch with start, stop and reset buttons — powered by setInterval, state variables and live DOM updates.',
                'objectives': [
                    'Schedule repeating code with setInterval and a delay',
                    'Stop a running timer with clearInterval and its id',
                    'Keep elapsed time in state variables that survive between ticks',
                    'Wire three buttons to start, stop and reset behaviours',
                ],
                'knowledge': [
                    {'heading': 'Timers: code that runs later', 'body': 'Everything you have written so far runs top to bottom and finishes instantly. setInterval(fn, 100) is different: it asks the browser to run your function every 100 milliseconds, forever, until told to stop. Your script ends, but the ticking continues — the browser keeps the function and fires it on schedule. This is asynchronous programming: code scheduled for the future instead of executed now. Animations, clocks, autosave, the blinking cursor in your editor — all of them are timers firing quietly in the background.'},
                    {'heading': 'The event loop, briefly', 'body': 'How can a browser run your timer, listen for clicks and scroll the page all at once? Through the event loop: an endless cycle that checks a queue of waiting jobs — a timer is due, a button was clicked — and runs them one at a time, extremely fast. setInterval does not interrupt running code; it places your function into that queue each time the delay elapses. That is also why setInterval(fn, 100) means "at most every 100ms, not earlier" — if the browser is busy, your tick waits its turn in the queue.'},
                    {'heading': 'Stopping needs a handle', 'body': 'setInterval returns an id — a number identifying that particular timer. Store it: timer = setInterval(...). To stop, call clearInterval(timer). Forget to store the id and the timer becomes unstoppable! There is a classic bug lurking here too: press Start twice without guarding and you create TWO timers updating the same display, making time run double-speed — and your stored id can only cancel one of them. A simple guard like if (timer) return; keeps your stopwatch honest. Professional code is full of small guards like this.'},
                    {'heading': 'State + display = an app', 'body': 'Your stopwatch splits cleanly into state (the elapsed variable holding the truth) and display (the #display element showing it). Every tick updates state first, then renders it into the DOM with textContent. Reset means: set state back to zero, render again. This state-then-render pattern is the architecture behind almost every interface — game loops redraw the world from game state, and frameworks like React exist purely to keep state and screen in sync. You are building the same idea with your bare hands.'},
                ],
                'fun_fact': 'JavaScript timers are never perfectly precise — a setInterval of 100ms can drift by several milliseconds per tick. Serious stopwatches store the real start time with Date.now() and compute the difference, so the display self-corrects every tick.',
                'quiz': [
                    {'q': 'What does setInterval(tick, 100) do?', 'options': ['Runs tick once after 100 seconds', 'Runs tick repeatedly, about every 100 milliseconds', 'Pauses the page for 100 milliseconds', 'Runs tick 100 times immediately'], 'answer': 1, 'explain': 'setInterval schedules the function to fire over and over, with the given delay in milliseconds between runs.'},
                    {'q': 'Why must you store the value returned by setInterval?', 'options': ['It holds the current time', 'It is the timer id needed by clearInterval to stop it', 'It makes the timer more accurate', 'JavaScript requires every value to be stored'], 'answer': 1, 'explain': 'The returned id identifies that timer — clearInterval(id) is the only way to cancel it later.'},
                    {'q': 'Pressing Start twice without a guard makes the display count double-speed. Why?', 'options': ['The browser doubles the clock rate', 'Two intervals are now both updating the same elapsed variable', 'setInterval halves its delay each call', 'The display element duplicates itself'], 'answer': 1, 'explain': 'Each unguarded Start creates another independent interval; both tick and both add to elapsed, so it grows twice as fast.'},
                ],
            },
            {
                'slug': 'paint-with-code',
                'title': 'Paint with Code',
                'icon': 'brush',
                'minutes': 15,
                'sim': 'coding/lesson-js-canvas-art',
                'sim_type': 'coding',
                'summary': 'Turn a loop into a paintbrush: draw dozens of circles and squares on a canvas, with hsl() colours that shift on every pass.',
                'objectives': [
                    'Get a canvas drawing context with getContext("2d")',
                    'Draw circles with beginPath, arc and fill',
                    'Drive position, size and colour from a loop variable',
                    'Use hsl() colour values to sweep through the rainbow',
                ],
                'knowledge': [
                    {'heading': 'The canvas: a pixel playground', 'body': 'The <canvas> element is a rectangle of raw pixels that JavaScript paints directly — no tags, no CSS layout, just coordinates. You draw through a context object: ctx = canvas.getContext("2d"). Its coordinate system starts at (0,0) in the TOP-left corner, with y growing downward — the opposite of maths class! ctx.fillRect(x, y, w, h) paints a rectangle; circles take three steps: ctx.beginPath(), ctx.arc(x, y, radius, 0, Math.PI * 2), then ctx.fill(). Games, charts and drawing apps all render through exactly this API.'},
                    {'heading': 'Loops are paintbrushes', 'body': 'Drawing one circle is a demo; drawing fifty is art — and the difference is a loop. Put your draw calls inside for (let i = 0; i < 50; i++) and use i in the maths: x position 15 + i * 14 marches shapes across the screen, radius 5 + i makes them grow, and Math.sin(i) * 60 makes them wave up and down. One rule, executed many times with a changing input, produces patterns too intricate to draw by hand. That technique has a name — generative art — and galleries exhibit work made exactly this way.'},
                    {'heading': 'hsl(): colour you can compute', 'body': 'Hex codes like #EC4899 are awkward to vary inside a loop. hsl(hue, saturation%, lightness%) is built for it: hue is an angle around the colour wheel from 0 to 360 — red at 0, green at 120, blue at 240, back to red at 360. Set ctx.fillStyle = "hsl(" + (i * 15) + ", 80%, 60%)" and every pass of the loop paints with the next colour of the rainbow. One multiplication gives you a smooth gradient across all your shapes — colour as arithmetic, not guesswork.'},
                ],
                'fun_fact': 'Generative art made with code sells in serious galleries — and the artist often cannot predict the exact output! Pioneer Vera Molnár began making algorithmic art with computers in 1968, decades before the web existed.',
                'quiz': [
                    {'q': 'What does canvas.getContext("2d") give you?', 'options': ['A second canvas element', 'The drawing object whose methods paint onto the canvas', 'A 2-pixel drawing area', 'The CSS styles of the canvas'], 'answer': 1, 'explain': 'The context object carries all drawing methods — fillRect, arc, fill — and settings like fillStyle.'},
                    {'q': 'On a canvas, where is the point (0, 0)?', 'options': ['The centre', 'The bottom-left corner', 'The top-left corner', 'Wherever the last shape was drawn'], 'answer': 2, 'explain': 'Canvas coordinates start at the top-left, and y increases downward — opposite to graphs in maths.'},
                    {'q': 'Inside a loop, ctx.fillStyle = "hsl(" + i * 15 + ", 80%, 60%)" makes the shapes...', 'options': ['All the same colour', 'Invisible', 'Step through different hues as i grows', 'Flash randomly'], 'answer': 2, 'explain': 'The hue angle changes with i each pass, walking around the colour wheel — a computed rainbow.'},
                ],
            },
            {
                'slug': 'python-data-detective',
                'title': 'Python Data Detective',
                'icon': 'query_stats',
                'minutes': 15,
                'sim': 'coding/lesson-py-data',
                'sim_type': 'coding',
                'summary': 'Investigate a list of exam scores with Python: count, average, highest, lowest and pass rate — printed as a clean report.',
                'objectives': [
                    'Total a list with the accumulator pattern',
                    'Count items matching a condition inside a loop',
                    'Use len(), max() and min() on real data',
                    'Compute a percentage and format a report with f-strings',
                ],
                'knowledge': [
                    {'heading': 'From numbers to answers', 'body': 'A list like [78, 45, 92, ...] is data; "the average is 64 and 80% passed" is information. Turning one into the other is data analysis, and its core moves are tiny: count things, add things up, find extremes, compute ratios. Every dashboard, every report card and every "students improved 12% this year" headline comes from exactly these operations run on bigger lists. Master them on ten scores and you have the same toolkit analysts use on ten million rows.'},
                    {'heading': 'One loop, several jobs', 'body': 'You could loop once to total the scores and loop again to count passes — but one loop can do both. Keep two accumulators: total += s on every item, and passed += 1 only inside if s >= PASS_MARK. Each variable accumulates a different fact during the same pass over the data. This is how real data pipelines stay fast: one sweep through the data, collecting everything needed at once, instead of re-reading it for every question.'},
                    {'heading': 'Rates: counts becoming percentages', 'body': 'A pass count of 8 means little until you know there were 10 students; 8 out of 10 is the insight. That is a rate: passed / count gives 0.8, and multiplying by 100 turns it into 80 — a percentage. Rates let you compare fairly across groups of different sizes: a class of 10 and a school of 1000 can both score "80% passed". Watch the order of operations: passed / count * 100 works left to right, dividing first, exactly as intended.'},
                    {'heading': 'Built-ins are tested tools', 'body': 'Python ships with len(), max(), min() and sum() because counting and extremes are needed in nearly every program ever written. Could you find the maximum with your own loop and a best-so-far variable? Absolutely — you did it in JavaScript Quest. Should you, when max() exists? Usually not: built-ins are shorter, faster and already debugged by thousands of users. A professional rule of thumb: write the manual version once to understand it, then reach for the built-in forever after.'},
                ],
                'fun_fact': 'The job title "data scientist" barely existed before 2008 — today it is one of the most in-demand careers on Earth, and the day-to-day work is largely Python running loops and aggregations like the ones in this lesson.',
                'quiz': [
                    {'q': 'What is the accumulator pattern for totalling a list?', 'options': ['total = 0 before the loop, total += item inside it', 'Print every item and add mentally', 'total = scores[0] * len(scores)', 'Lists total themselves with .total()'], 'answer': 0, 'explain': 'Start at zero, add each item as the loop visits it — the universal summing pattern.'},
                    {'q': '8 of 10 students passed. Which expression gives the pass rate as a percentage?', 'options': ['8 * 10 / 100', '8 / 10 * 100', '10 / 8 * 100', '8 + 10 * 100'], 'answer': 1, 'explain': 'Divide the part by the whole (0.8), then multiply by 100 to express it as a percentage: 80.'},
                    {'q': 'Why count passes inside the same loop that totals the scores?', 'options': ['Python only allows one loop per program', 'One pass over the data collects both facts — efficient and tidy', 'It changes the average', 'Two loops would give a different pass count'], 'answer': 1, 'explain': 'Multiple accumulators can ride the same loop, gathering different statistics in a single sweep.'},
                ],
            },
            {
                'slug': 'python-word-game',
                'title': 'Python Word Game',
                'icon': 'sports_esports',
                'minutes': 18,
                'sim': 'coding/lesson-py-wordgame',
                'sim_type': 'coding',
                'summary': 'Build the brain of a hangman game: test guesses with "in", track wrong letters in a list, and reveal the masked word.',
                'objectives': [
                    'Test membership with the in operator on strings and lists',
                    'Sort guesses into found and wrong lists as the game runs',
                    'Build a masked word character by character with a loop',
                    'Decide the round with an if/else on the final state',
                ],
                'knowledge': [
                    {'heading': 'in: the one-word search engine', 'body': 'Python\'s in operator answers "is this inside that?" in a single word: "a" in "planet" is True, "z" in "planet" is False, and it works on lists too — guess in found. Behind the scenes Python walks through the string or list checking each element, but you get to write it as plain English. Membership tests are everywhere in real software: is this username taken? is this word in the dictionary? is this card already played? Your game engine runs on exactly this question.'},
                    {'heading': 'Game state is just lists', 'body': 'A running game feels alive, but its memory is ordinary data. Your word game needs to remember two things: letters found and letters wrong — so it keeps two lists and appends to one or the other as each guess is judged. That pair of lists IS the game state. Snapshot them and you could save the game; print them and you can debug it. Every game you have played — chess apps, Wordle, massive online worlds — is state being updated by rules, exactly like your two append calls.'},
                    {'heading': 'Building strings letter by letter', 'body': 'The masked word p_a__t comes from a classic pattern: start with an empty string masked = "", loop over each letter of the secret, and grow the string with masked += letter when the letter is found, or masked += "_" when it is hidden. Strings in the loop act like an accumulator — the same idea as totalling numbers, but concatenating text. The result reveals exactly what the player knows and hides the rest: one loop producing the game\'s entire display.'},
                    {'heading': 'Think in phases', 'body': 'Notice the shape of your program: phase one judges all the guesses, phase two builds the masked word, phase three reports and declares the verdict. Decomposing a problem into ordered phases — each small enough to write and test alone — is the heart of algorithmic thinking, and it is the skill interviewers actually probe for. The full game loop (ask, judge, redraw, repeat until won or out of lives) is just these phases wrapped in a while loop; you have already built the hard part.'},
                ],
                'fun_fact': 'Wordle — the word game that 300,000 people played daily within months of launch — runs on the same core logic you just wrote: membership tests against a secret word and a masked display of what the player knows.',
                'quiz': [
                    {'q': 'What does "e" in "planet" evaluate to?', 'options': ['"e"', 'True', 'False', 'An error'], 'answer': 1, 'explain': 'The in operator checks membership: "planet" contains the letter e, so the result is True.'},
                    {'q': 'A guess is wrong. What should the engine do with it?', 'options': ['Crash the program', 'Ignore it completely', 'Append it to the wrong list so the game remembers it', 'Remove a letter from the secret word'], 'answer': 2, 'explain': 'Wrong guesses are game state: storing them in a list lets you count lives used and avoid repeats.'},
                    {'q': 'How is the masked word like p_a__t built?', 'options': ['By deleting letters from the secret', 'By looping over the secret, adding the letter if found, else an underscore', 'With a special mask() built-in', 'By sorting the guesses alphabetically'], 'answer': 1, 'explain': 'It is the string-accumulator pattern: one loop over the secret, growing the masked string one character per letter.'},
                    {'q': 'Why split the program into judge, build and verdict phases?', 'options': ['Python requires three sections', 'Small phases can be written and tested one at a time', 'It makes the program run three times faster', 'Loops only work inside phases'], 'answer': 1, 'explain': 'Decomposition is the master skill: each phase is simple alone, and together they form the full game engine.'},
                ],
            },
        ],
    },
]
