COURSES = [
    {
        'slug': 'neb-chemistry-practical-12',
        'title': 'NEB Chemistry Practicals — Class 12',
        'category': 'chemistry',
        'age_range': '17-18',
        'level': 'Advanced',
        'icon': 'science',
        'color': '#047857',
        'tagline': 'Master the Class 12 NEB practical exam — redox titration, full salt analysis, electrolysis, organic tests and more.',
        'description': 'The complete Class 12 NEB chemistry practical syllabus as realistic virtual experiments. Standardise potassium permanganate with a hot oxalic acid flask, work through the full Group I-VI cation analysis scheme on genuinely unknown salts, verify Faraday\'s law by electroplating copper, measure pH with four different tools, identify organic functional groups, determine the heat of neutralisation in a live calorimeter, and run Lassaigne\'s sodium fusion test for N, S and halogens. Every simulation enforces real procedure — skip the heating, use a cold flask or test out of order and you will see exactly why it fails.',
        'skills': [
            'Redox titration with a self-indicating endpoint',
            'Systematic qualitative analysis (Group I-VI cation scheme)',
            'Electrolysis and Faraday\'s laws quantitatively',
            'pH measurement and buffer behaviour',
            'Organic functional group identification',
            'Thermochemical measurement and ΔH calculation',
            'Detection of N, S and halogens in organic compounds',
        ],
        'lessons': [
            {
                'slug': 'redox-titration-kmno4',
                'title': 'Redox Titration with KMnO₄',
                'icon': 'water_drop',
                'minutes': 20,
                'sim': 'nebchemistry/redox-titration',
                'sim_type': '3d',
                'summary': 'Standardise potassium permanganate against oxalic acid: heat the flask to 60-70 °C (skip it and watch the trial fail), titrate to the first permanent pink, and calculate the molarity from the 2:5 mole ratio.',
                'objectives': [
                    'Explain why KMnO₄ needs no separate indicator',
                    'State why the oxalic acid flask must be heated to 60-70 °C before titrating',
                    'Titrate to the correct self-indicating endpoint: the first permanent pale pink',
                    'Use the 2:5 mole ratio of MnO₄⁻ to C₂O₄²⁻ in the calculation',
                    'Identify procedure errors that invalidate a redox trial',
                ],
                'knowledge': [
                    {
                        'heading': 'A titration that indicates itself',
                        'body': 'Potassium permanganate is intensely purple; its reduction product Mn²⁺ is virtually colourless at titration concentrations. So as KMnO₄ runs into the oxalic acid flask, each addition decolourises instantly while oxalate remains — the purple simply vanishes into the solution. The moment all the oxalate is consumed, the very next drop has nothing left to react with and tints the whole flask a permanent pale pink.\n\nThat first permanent pink, persisting through 30 seconds of swirling, is the endpoint — KMnO₄ is its own indicator. Adding phenolphthalein or methyl orange would be wrong twice over: they are unnecessary, and KMnO₄ being a powerful oxidiser would destroy them anyway. The full ionic equation: 2MnO₄⁻ + 5C₂O₄²⁻ + 16H⁺ → 2Mn²⁺ + 10CO₂ + 8H₂O.',
                    },
                    {
                        'heading': 'Why the flask must be hot (and acidic)',
                        'body': 'The permanganate-oxalate reaction is surprisingly slow at room temperature. Titrate a cold flask and each purple drop lingers unreacted for many seconds, so the solution looks pink long before the true endpoint — you stop early and your titre is badly wrong. Heating the flask to 60-70 °C before starting speeds the reaction so each drop decolourises promptly. Above 70 °C, though, oxalic acid itself starts decomposing, so the window matters: 60-70 °C, checked with a thermometer.\n\n(The reaction is also autocatalytic — the Mn²⁺ product catalyses further reaction, which is why the first few additions of a titration decolourise sluggishly and later ones instantly.) The acid matters too: the medium is made acidic with dilute H₂SO₄, never HCl — permanganate would oxidise chloride to chlorine, consuming extra titrant and faking a high titre. And never with HNO₃, itself an oxidiser.',
                    },
                    {
                        'heading': 'The calculation: mind the 2:5 ratio',
                        'body': 'Unlike the 1:1 acid-base case, this redox reaction consumes 2 mol of MnO₄⁻ per 5 mol of C₂O₄²⁻. From the balanced equation: moles KMnO₄ = (2/5) × moles oxalic acid. With 25.0 mL of 0.050 M oxalic acid in the flask and a mean titre V mL: M(KMnO₄) = (2/5) × 0.050 × 25.0 / V.\n\nIn the older normality language still used in many Nepali practical books, the arithmetic hides the ratio: equivalent weight of KMnO₄ in acidic medium is M/5 (5 electrons gained per Mn) and of oxalic acid dihydrate M/2 (2 electrons lost), so N₁V₁ = N₂V₂ applies directly. Both routes give the same answer — but state which one you are using. One more practical point: read the purple KMnO₄ meniscus at its top edge, not the bottom, because the dark solution hides the lower meniscus completely.',
                    },
                ],
                'fun_fact': 'Dilute KMnO₄ — "pinky" or Condy\'s crystals — is used across Nepal as an antiseptic for washing wounds and vegetables; the same oxidising power that destroys indicators destroys bacteria.',
                'quiz': [
                    {
                        'q': 'No indicator is added in the KMnO₄-oxalic acid titration because…',
                        'options': ['The reaction has no endpoint', 'KMnO₄ acts as its own indicator', 'Oxalic acid is coloured', 'Indicators only work for acids'],
                        'answer': 1,
                        'explain': 'Purple MnO₄⁻ becomes colourless Mn²⁺ while reactant remains; the first persistent pink of excess KMnO₄ marks the endpoint.',
                    },
                    {
                        'q': 'The oxalic acid flask is heated to 60-70 °C because…',
                        'options': ['Oxalic acid only dissolves when hot', 'The reaction is too slow when cold, giving a false early endpoint', 'KMnO₄ freezes otherwise', 'Heat changes the mole ratio'],
                        'answer': 1,
                        'explain': 'Cold, the redox reaction is sluggish: unreacted purple accumulates and looks like an endpoint far too early.',
                    },
                    {
                        'q': 'The medium is acidified with H₂SO₄ rather than HCl because…',
                        'options': ['HCl is too weak', 'KMnO₄ would oxidise Cl⁻ to Cl₂, consuming extra titrant', 'H₂SO₄ is cheaper', 'HCl evaporates when heated'],
                        'answer': 1,
                        'explain': 'Chloride is oxidisable; permanganate spent on Cl⁻ → Cl₂ inflates the titre. Sulphate cannot be oxidised further, so H₂SO₄ is safe.',
                    },
                    {
                        'q': '25.0 mL of 0.050 M oxalic acid needed 20.0 mL of KMnO₄. The KMnO₄ molarity is…',
                        'options': ['0.0625 M', '0.025 M', '0.125 M', '0.010 M'],
                        'answer': 1,
                        'explain': 'Moles oxalate = 0.00125; moles MnO₄⁻ = (2/5)(0.00125) = 0.0005; M = 0.0005/0.020 L = 0.025 M.',
                    },
                ],
            },
            {
                'slug': 'salt-analysis-scheme',
                'title': 'Full Salt Analysis Scheme',
                'icon': 'account_tree',
                'minutes': 20,
                'sim': 'nebchemistry/salt-analysis',
                'sim_type': '3d',
                'summary': 'A genuinely unknown salt, the full systematic scheme: preliminary observations, dry heating, flame test, then group reagents I to VI in strict order until a precipitate betrays the cation — finish with the confirmatory test.',
                'objectives': [
                    'Use preliminary observations (colour, dry heating, flame) to shortlist cations',
                    'Apply the group reagents in the correct order and explain what each separates',
                    'Interpret the colour and form of each group precipitate',
                    'Confirm a cation with its specific confirmatory test',
                    'Explain why skipping a group can give a completely wrong conclusion',
                ],
                'knowledge': [
                    {
                        'heading': 'The logic of the group scheme',
                        'body': 'Dozens of cations cannot each be tested individually — so qualitative analysis sorts them into groups by solubility, using one group reagent at a time. Group I: dilute HCl precipitates the insoluble chlorides (Pb²⁺ as white PbCl₂). Group II: H₂S in acidic medium precipitates the least soluble sulphides (Cu²⁺ as black CuS). Group III: NH₄OH in presence of NH₄Cl precipitates the hydroxides (Fe³⁺ as reddish-brown Fe(OH)₃). Group IV: H₂S in ammoniacal medium gets the more soluble sulphides (Zn²⁺ as dirty-white ZnS). Group V: (NH₄)₂CO₃ precipitates the alkaline-earth carbonates (Ca²⁺ as white CaCO₃). What remains — Na⁺, K⁺, NH₄⁺, Mg²⁺ — is Group VI.\n\nThe order is everything. Each reagent is chosen so that it precipitates its own group but leaves later groups in solution. Test out of order and the logic collapses: add ammoniacal H₂S to a solution still containing Cu²⁺ and you get a Group II precipitate while believing you are testing Group IV.',
                    },
                    {
                        'heading': 'Preliminary tests: free information',
                        'body': 'Before any wet chemistry, the salt itself talks. Colour: blue or blue-green suggests Cu²⁺, yellow-brown suggests Fe³⁺, pale green Fe²⁺, and a white salt rules them all out. Dry heating in a clean tube is rich in clues: CuSO₄·5H₂O turns from blue to white; zinc salts leave a residue that is yellow hot and white cold (ZnO); lead nitrate decrepitates (crackles) and gives brown NO₂ fumes; ammonium salts sublime entirely or release ammonia; calcium carbonate releases CO₂ on strong heating.\n\nThe flame test adds another column: brick-red points at calcium, blue-green at copper. None of this is proof — preliminary tests only shortlist. Their real value is telling you where in the group scheme to expect the hit, so a contradiction (flame says calcium, but a precipitate appears in Group II) warns you immediately that something is wrong.',
                    },
                    {
                        'heading': 'Confirmation: the second, independent witness',
                        'body': 'A group precipitate identifies the group, not the ion — Group III contains Fe³⁺, Al³⁺ and Cr³⁺ alike. So every analysis ends with a confirmatory test specific to one cation. Pb²⁺: potassium iodide gives a brilliant yellow PbI₂ precipitate (the "golden shower" when recrystallised). Cu²⁺: excess ammonia gives the deep royal-blue [Cu(NH₃)₄]²⁺. Fe³⁺: potassium ferrocyanide gives Prussian blue, or KSCN gives blood-red. Zn²⁺: NaOH gives a white Zn(OH)₂ precipitate that redissolves in excess — the amphoteric signature. Ca²⁺: ammonium oxalate gives a white precipitate insoluble in acetic acid. NH₄⁺: warming with NaOH releases ammonia that turns moist red litmus blue, confirmed by Nessler\'s reagent turning brown.\n\nThe pattern to internalise: group test to locate, confirmatory test to convict. Reporting a cation on the group precipitate alone is the classic way to lose marks — and to be wrong.',
                    },
                ],
                'fun_fact': 'Prussian blue, the confirmatory colour for iron, was the first modern synthetic pigment (Berlin, 1706) — it coloured Hokusai\'s Great Wave, and in megadose form it is a WHO-listed antidote for thallium poisoning.',
                'quiz': [
                    {
                        'q': 'The Group I reagent in cation analysis is…',
                        'options': ['H₂S gas', 'Dilute HCl', 'NH₄OH', '(NH₄)₂CO₃'],
                        'answer': 1,
                        'explain': 'Dilute HCl precipitates the insoluble chlorides — PbCl₂ (and AgCl, Hg₂Cl₂ in the full scheme) — as Group I.',
                    },
                    {
                        'q': 'A reddish-brown gelatinous precipitate with NH₄OH/NH₄Cl indicates…',
                        'options': ['Cu²⁺', 'Zn²⁺', 'Fe³⁺', 'Ca²⁺'],
                        'answer': 2,
                        'explain': 'Group III: Fe(OH)₃ is the characteristic reddish-brown gelatinous hydroxide. Al(OH)₃ in the same group is white.',
                    },
                    {
                        'q': 'White Zn(OH)₂ dissolving in EXCESS NaOH shows that zinc hydroxide is…',
                        'options': ['Unstable', 'Amphoteric — reacting with both acids and bases', 'A strong base', 'Insoluble in everything'],
                        'answer': 1,
                        'explain': 'Zn(OH)₂ reacts with acids as a base and with excess strong base to form soluble zincate — the defining amphoteric behaviour.',
                    },
                    {
                        'q': 'Groups must be tested strictly in order I → VI because…',
                        'options': ['The reagents expire quickly', 'Each group reagent also precipitates cations of EARLIER groups, so skipping causes misidentification', 'Later reagents are more dangerous', 'It saves chemicals'],
                        'answer': 1,
                        'explain': 'A Cu²⁺ ion still in solution would precipitate with the Group IV reagent too. Removing earlier groups first keeps each result unambiguous.',
                    },
                ],
            },
            {
                'slug': 'electrolysis-cuso4',
                'title': 'Electrolysis of CuSO₄',
                'icon': 'bolt',
                'minutes': 16,
                'sim': 'nebchemistry/electrolysis',
                'sim_type': '3d',
                'summary': 'Pass a measured current through copper sulphate solution between copper electrodes, watch Cu²⁺ ions migrate, weigh the cathode before and after, and verify Faraday\'s first law: m = ZIt.',
                'objectives': [
                    'Describe the electrode reactions at copper anode and cathode',
                    'Explain why the solution\'s blue colour stays constant with copper electrodes',
                    'Measure mass deposited and verify m = ZIt quantitatively',
                    'Define the electrochemical equivalent Z and calculate it from M and F',
                    'Predict the effect of doubling current or time on the deposit',
                ],
                'knowledge': [
                    {
                        'heading': 'What happens at each electrode',
                        'body': 'Copper sulphate solution contains mobile Cu²⁺ and SO₄²⁻ ions. Connect copper electrodes to a DC supply and the ions drift: Cu²⁺ toward the negative cathode, SO₄²⁻ toward the positive anode. At the cathode, copper ions gain electrons and deposit as fresh pink-brown metal: Cu²⁺ + 2e⁻ → Cu. At the copper anode, the easiest oxidation is the copper of the electrode itself dissolving: Cu → Cu²⁺ + 2e⁻.\n\nThe net effect is elegant: copper transfers from anode to cathode while the solution composition stays exactly constant — every Cu²⁺ removed at the cathode is replaced at the anode, which is why the blue colour never fades. (With inert platinum or carbon electrodes the story changes: oxygen gas evolves at the anode instead, Cu²⁺ is genuinely consumed, and the blue fades.) This anode-dissolves arrangement is exactly how industrial copper refining and all electroplating work.',
                    },
                    {
                        'heading': "Faraday's first law",
                        'body': 'Faraday\'s first law of electrolysis (1833): the mass liberated at an electrode is directly proportional to the quantity of charge passed. Charge Q = I × t (amperes × seconds), so m = Z·I·t, where Z is the electrochemical equivalent — the mass deposited per coulomb.\n\nZ follows from atomic bookkeeping. One mole of electrons carries F = 96,500 C (the Faraday constant). Depositing one Cu atom needs 2 electrons, so one mole of copper (63.5 g) needs 2 × 96,500 C. Hence Z(Cu) = 63.5 / (2 × 96,500) = 0.000329 g/C. Run 1.0 A for 30 minutes: m = 0.000329 × 1.0 × 1800 = 0.59 g — a gain you can weigh easily. The law is beautifully linear: double the current or double the time, and exactly double the copper lands on the cathode. Test it in the simulation.',
                    },
                    {
                        'heading': 'Doing it accurately',
                        'body': 'The measurement is a sandwich: weigh the clean, dry cathode; electrolyse at a steady, gentle current for a known time; rinse the cathode with distilled water, dry it carefully, and reweigh. The mass gain is your m. Keep current density low — around 1 A with small electrodes — because forcing current too fast deposits copper as a spongy, poorly-adherent layer that flakes off during rinsing and undercuts your result.\n\nOther error sources: a fluctuating current (use a rheostat and watch the ammeter — the I in ZIt must be the average), timing sloppiness, weighing the cathode wet, and rubbing the deposit off while drying (blot, don\'t wipe). A neat check on your whole experiment: the anode\'s mass loss should equal the cathode\'s gain. If they differ much, some copper ended up as sludge instead of plate. As a bonus check of Faraday\'s second law, the same charge would deposit silver in the ratio of its equivalent weight — 108/1 versus copper\'s 63.5/2.',
                    },
                ],
                'fun_fact': 'Every "gold-plated" trophy, chrome bumper and the pure copper in Nepal\'s electrical wiring passed through exactly this experiment scaled up — world copper refineries deposit millions of tonnes a year onto cathodes, governed by m = ZIt.',
                'quiz': [
                    {
                        'q': 'During electrolysis of CuSO₄ with copper electrodes, the blue colour…',
                        'options': ['Fades steadily', 'Deepens steadily', 'Stays constant, because the anode replaces every ion the cathode removes', 'Turns green'],
                        'answer': 2,
                        'explain': 'Cathode: Cu²⁺ + 2e⁻ → Cu. Anode: Cu → Cu²⁺ + 2e⁻. The Cu²⁺ concentration is unchanged, so the colour holds.',
                    },
                    {
                        'q': 'The electrochemical equivalent of copper, Z = M/(2F), equals about…',
                        'options': ['0.000329 g/C', '0.0329 g/C', '63.5 g/C', '96500 g/C'],
                        'answer': 0,
                        'explain': 'Z = 63.5 / (2 × 96500) ≈ 0.000329 g per coulomb — each coulomb plates a third of a milligram of copper.',
                    },
                    {
                        'q': 'If both the current and the time are doubled, the mass deposited becomes…',
                        'options': ['Double', 'Half', 'Four times', 'Unchanged'],
                        'answer': 2,
                        'explain': 'm = ZIt is proportional to both I and t: doubling each multiplies the deposit by 2 × 2 = 4.',
                    },
                    {
                        'q': 'A current of 2.0 A flows for 965 s. The copper deposited is about… (Z = 0.000329 g/C)',
                        'options': ['0.32 g', '0.64 g', '1.27 g', '0.16 g'],
                        'answer': 1,
                        'explain': 'm = 0.000329 × 2.0 × 965 ≈ 0.635 g.',
                    },
                ],
            },
            {
                'slug': 'ph-and-indicators',
                'title': 'pH & Indicators',
                'icon': 'palette',
                'minutes': 15,
                'sim': 'nebchemistry/ph-indicators',
                'sim_type': '3d',
                'summary': 'Measure the pH of eleven solutions from dilute HCl to NaOH using litmus, universal indicator, pH paper and a digital meter — then add acid drops to blood and discover what a buffer really does.',
                'objectives': [
                    'Rank common household and lab solutions on the pH scale',
                    'Choose the right pH tool for the job and state each one\'s precision',
                    'Explain the logarithmic nature of the pH scale',
                    'Demonstrate buffer action and explain it with the H₂CO₃/HCO₃⁻ pair',
                    'Interpret universal indicator colours across the full 0-14 range',
                ],
                'knowledge': [
                    {
                        'heading': 'Four tools, four levels of precision',
                        'body': 'Litmus is the coarsest tool: red below about pH 5, blue above about 8 — it answers only "acid or base?" and says nothing in between. pH paper is litmus\'s educated cousin, impregnated with a mixture of dyes: match the strip\'s colour to the chart and you read pH to roughly the nearest whole number. Universal indicator is the same dye mixture in solution, painting the whole range — red (strong acid) through orange, yellow, green (neutral), blue, to violet (strong alkali).\n\nThe digital pH meter is the precision instrument: a glass electrode develops a voltage proportional to H⁺ concentration, displayed to 0.01 pH units. But precision needs care — the meter must first be calibrated against standard buffer solutions (pH 4.0, 7.0, 9.2), the bulb kept wet, and readings taken at a known temperature. An uncalibrated meter is confidently, precisely wrong.',
                    },
                    {
                        'heading': 'The scale is logarithmic',
                        'body': 'pH = −log₁₀[H⁺], so each pH unit is a factor of ten in hydrogen-ion concentration. Lemon juice at pH 2.4 is not "a bit" more acidic than milk at 6.6 — it has over ten thousand times the H⁺ concentration. This is why mixing equal volumes of pH 1 acid and pH 13 alkali gives a violent reaction while mixing pH 6 and pH 8 solutions barely warms.\n\nLandmarks worth memorising: dilute HCl (0.1 M) pH 1, lemon juice 2.4, vinegar 2.9, milk 6.6, pure water 7.0, blood 7.4, baking soda solution 8.4, soap 9-10, lime water 11, 0.1 M NaOH 13. Note that "neutral" is 7.0 only at 25 °C — pure water\'s pH drifts slightly with temperature because the ionisation of water itself is temperature-dependent.',
                    },
                    {
                        'heading': 'Buffers: solutions that fight back',
                        'body': 'Add a drop of strong acid to pure water and the pH crashes by several units. Add the same drop to blood and the pH barely twitches. Blood is a buffer — a mixture (here carbonic acid H₂CO₃ and hydrogencarbonate HCO₃⁻) containing both a weak acid and its conjugate base, each standing guard. Added H⁺ is absorbed by the base: H⁺ + HCO₃⁻ → H₂CO₃. Added OH⁻ is absorbed by the acid: OH⁻ + H₂CO₃ → HCO₃⁻ + H₂O. Either way, free H⁺ hardly changes.\n\nYour blood must hold pH 7.35-7.45; outside roughly 6.8-7.8 enzymes denature and cells die, so the buffer is life-critical — backed up by the lungs (exhaling CO₂) and kidneys. Buffers fill labs and industry too: calibration standards for pH meters, fermentation tanks, and the acetic acid/acetate buffer you will meet in volumetric analysis.',
                    },
                ],
                'fun_fact': 'The pH scale was invented in 1909 by Søren Sørensen at the Carlsberg brewery laboratory in Copenhagen — quality-controlling beer, where wild yeast and pH drift could ruin a whole batch.',
                'quiz': [
                    {
                        'q': 'Which tool gives pH to two decimal places?',
                        'options': ['Litmus paper', 'Universal indicator', 'A calibrated digital pH meter', 'Phenolphthalein'],
                        'answer': 2,
                        'explain': 'The glass-electrode meter reads to 0.01 units — provided it has been calibrated against standard buffers first.',
                    },
                    {
                        'q': 'A solution of pH 3 compared with one of pH 6 has…',
                        'options': ['Twice the H⁺ concentration', '3 times the H⁺', '1000 times the H⁺', 'Half the H⁺'],
                        'answer': 2,
                        'explain': 'Each pH unit is a tenfold change: 3 units = 10³ = 1000 times more hydrogen ions.',
                    },
                    {
                        'q': 'Adding a drop of HCl to a buffer barely changes its pH because…',
                        'options': ['The acid evaporates', 'The conjugate base component absorbs the added H⁺', 'Buffers are solid', 'HCl is a weak acid'],
                        'answer': 1,
                        'explain': 'In blood, HCO₃⁻ captures the added H⁺ to form H₂CO₃, so the free H⁺ concentration — and hence pH — hardly moves.',
                    },
                    {
                        'q': 'Universal indicator in a neutral solution appears…',
                        'options': ['Red', 'Green', 'Violet', 'Colourless'],
                        'answer': 1,
                        'explain': 'The dye mixture shows green at pH ≈ 7, shading to red in strong acid and violet in strong alkali.',
                    },
                ],
            },
            {
                'slug': 'organic-functional-groups',
                'title': 'Organic Functional Group Tests',
                'icon': 'hub',
                'minutes': 18,
                'sim': 'nebchemistry/functional-groups',
                'sim_type': '3d',
                'summary': 'Four unlabelled organic liquids — alcohol, aldehyde, carboxylic acid, phenol. Run sodium metal, Tollens\', Fehling\'s, NaHCO₃, FeCl₃ and ester tests in any order, cross-check the results and name the functional group.',
                'objectives': [
                    'Perform and interpret the sodium metal test for the −OH group',
                    'Distinguish aldehydes with Tollens\' silver mirror and Fehling\'s red precipitate',
                    'Use the NaHCO₃ test to separate carboxylic acids from phenol',
                    'Recognise phenol by the violet FeCl₃ colouration',
                    'Combine positive AND negative results into a logical identification',
                ],
                'knowledge': [
                    {
                        'heading': 'Hydroxyl-containing compounds: Na, NaHCO₃ and FeCl₃',
                        'body': 'Sodium metal fizzes with any acidic O−H hydrogen, releasing H₂: 2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂. Alcohols, phenol and carboxylic acids all give the effervescence, so a positive sodium test says "some −OH is here" without naming it. The discrimination comes from acidity strength. NaHCO₃ liberates CO₂ only from acids stronger than carbonic acid: carboxylic acids fizz briskly (CH₃COOH + NaHCO₃ → CH₃COONa + H₂O + CO₂), but phenol — about a hundred thousand times weaker — cannot displace CO₂ and gives nothing. That one negative cleanly separates phenol from the acids.\n\nNeutral FeCl₃ then names phenol directly: a striking violet complex, [Fe(OC₆H₅)₆]³⁻. (Acetate ions give a red colouration instead — a different positive worth knowing so you don\'t confuse them.) Logic chain: Na fizz + NaHCO₃ fizz = carboxylic acid; Na fizz + no NaHCO₃ fizz + violet FeCl₃ = phenol; Na fizz + both others negative = alcohol.',
                    },
                    {
                        'heading': 'Aldehydes: the two great reduction tests',
                        'body': 'Aldehydes are distinguished by being easily oxidised — so reagents containing reducible metal ions light up with them. Tollens\' reagent is ammoniacal silver nitrate, [Ag(NH₃)₂]⁺. Warm it gently with an aldehyde and the silver ions are reduced to metallic silver that deposits on the clean glass wall as a brilliant mirror: CH₃CHO + 2[Ag(NH₃)₂]⁺ + 3OH⁻ → CH₃COO⁻ + 2Ag↓ + 4NH₃ + 2H₂O.\n\nFehling\'s solution is alkaline copper(II) tartrate, deep blue. Boil it with an aldehyde and Cu²⁺ is reduced to red-brown Cu₂O precipitate. Ketones fail both tests (no easily-removed carbonyl hydrogen), which is precisely how aldehydes and ketones are told apart. Two cautions: Tollens\' reagent must be freshly prepared and discarded after use (on standing it can form explosive silver fulminate), and the tube must be scrupulously clean or the silver deposits as grey sludge instead of a mirror.',
                    },
                    {
                        'heading': 'Strategy: negatives are evidence too',
                        'body': 'In the exam you receive one unknown and limited time, so test economically and think in a grid. A fizzing NaHCO₃ test alone almost settles carboxylic acid; confirm with the ester test — warm the liquid with ethanol and a few drops of concentrated H₂SO₄, pour into water, and the fruity smell of ethyl ethanoate is unmistakable: CH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O.\n\nEqually, absences convict: a liquid that fizzes with sodium but ignores NaHCO₃, Tollens\' and FeCl₃ can only be an alcohol — three negatives plus one positive is a complete proof. Record every observation, positive or negative, in your table. The examiner marks the reasoning chain: observation → inference → conclusion. A correct answer with no recorded negative evidence earns less than a fully-argued one.',
                    },
                ],
                'fun_fact': 'The Tollens\' reaction was used industrially for 150 years to silver the insides of mirrors and vacuum flasks — a thin layer of chemistry-deposited silver is still the most reflective coating cheaply available.',
                'quiz': [
                    {
                        'q': 'A liquid fizzes with sodium metal but NOT with NaHCO₃, and gives violet with FeCl₃. It is…',
                        'options': ['Ethanol', 'Ethanoic acid', 'Phenol', 'Ethanal'],
                        'answer': 2,
                        'explain': 'The −OH reacts with Na, but phenol is too weak an acid for NaHCO₃; the violet iron-phenol complex confirms it.',
                    },
                    {
                        'q': 'Tollens\' test gives a positive result as…',
                        'options': ['A red precipitate', 'A silver mirror on the tube wall', 'Violet colouration', 'Brisk effervescence'],
                        'answer': 1,
                        'explain': 'Aldehydes reduce [Ag(NH₃)₂]⁺ to metallic silver, which coats clean glass as a mirror.',
                    },
                    {
                        'q': 'The NaHCO₃ test separates carboxylic acids from phenol because…',
                        'options': ['Phenol is insoluble', 'Only acids stronger than carbonic acid can liberate CO₂ from NaHCO₃', 'Phenol reacts explosively', 'Carboxylic acids are coloured'],
                        'answer': 1,
                        'explain': 'CH₃COOH is stronger than H₂CO₃ and displaces CO₂; phenol is far weaker and cannot — no fizz.',
                    },
                    {
                        'q': 'Boiling Fehling\'s solution with ethanal produces…',
                        'options': ['A silver mirror', 'A red-brown precipitate of Cu₂O', 'A blue precipitate', 'No change'],
                        'answer': 1,
                        'explain': 'The aldehyde reduces the blue Cu²⁺ complex to insoluble red Cu₂O — the classic Fehling\'s positive.',
                    },
                ],
            },
            {
                'slug': 'heat-of-neutralization',
                'title': 'Heat of Neutralization',
                'icon': 'device_thermostat',
                'minutes': 16,
                'sim': 'nebchemistry/thermochemistry',
                'sim_type': '3d',
                'summary': 'Mix measured HCl and NaOH in a polystyrene calorimeter, catch the temperature peak on a live graph, compute ΔH = −mcΔT/n, and discover why a weak acid releases measurably less heat.',
                'objectives': [
                    'Define heat (enthalpy) of neutralization and state its value for strong acid-strong base',
                    'Use a simple calorimeter correctly, recording T₁ before mixing and T₂ at the peak',
                    'Calculate ΔH from q = mcΔT and the moles of water formed',
                    'Explain why weak acids give a numerically smaller ΔH',
                    'Identify heat-loss errors and how the experiment minimises them',
                ],
                'knowledge': [
                    {
                        'heading': 'One reaction behind every strong pair',
                        'body': 'The heat of neutralization is the enthalpy change when one mole of water is formed by an acid neutralising a base in dilute solution. For any strong acid with any strong base the measured value is remarkably constant: about −57.3 kJ/mol. The reason is that strong acids and bases are fully ionised, so the spectator ions (Na⁺, Cl⁻) merely watch while the only real chemistry is identical every time: H⁺ + OH⁻ → H₂O.\n\nThat constancy is itself evidence for the ionic theory of acids and bases — HCl + NaOH, HNO₃ + KOH, H₂SO₄ + NaOH (per mole of water) all release the same heat because they are all literally the same reaction. The negative sign declares the reaction exothermic: chemical potential energy leaves the reacting ions and appears as the kinetic energy of the solution, which you observe as a temperature rise.',
                    },
                    {
                        'heading': 'The calorimeter and the calculation',
                        'body': 'The apparatus is humble: a polystyrene (thermocol) cup with a lid and a thermometer. Polystyrene is chosen because it is an excellent insulator with negligible heat capacity — nearly all the heat stays in the solution and gets counted. Procedure: measure equal volumes (say 50 mL each) of 1.0 M acid and 1.0 M NaOH, record the steady initial temperature T₁, mix quickly, stir, and record the maximum temperature T₂. The peak matters — after it, heat leaks to the room and the reading only falls.\n\nThe arithmetic: total solution mass m = 100 g (taking density ≈ 1 g/mL), specific heat c ≈ 4.18 J/g°C. Heat released q = m·c·(T₂−T₁). Moles of water formed n = 1.0 × 0.050 = 0.050 mol. ΔH = −q/n. With ΔT ≈ 6.8 °C: q ≈ 2840 J, ΔH ≈ −57 kJ/mol. Main error: heat escaping before you read T₂ — which always makes your |ΔH| too small, never too big.',
                    },
                    {
                        'heading': 'Why weak acids fall short',
                        'body': 'Repeat the experiment with ethanoic acid and the temperature rise is consistently smaller — ΔH around −55 kJ/mol instead of −57.3. A weak acid is only partly ionised: most CH₃COOH molecules are intact when mixing happens. Before their protons can neutralise OH⁻, those molecules must first ionise, and ionisation costs energy (it is endothermic for most weak acids).\n\nSo the measured heat is the full H⁺ + OH⁻ payout minus the ionisation tax: ΔH(neutralization, weak) = −57.3 + ΔH(ionisation). For ethanoic acid the tax is about +2 kJ/mol. The effect is even larger for weaker acids — HCN manages only about −12 kJ/mol because its ionisation is strongly endothermic. Measuring the shortfall is actually a clean indirect way to estimate an acid\'s enthalpy of ionisation: thermochemistry doing detective work, an application of Hess\'s law you can verify in this very simulation.',
                    },
                ],
                'fun_fact': 'Self-heating meal pouches and hand warmers used by trekkers in the Himalayas run on exothermic chemistry — some literally use acid-base or salt-hydration reactions, pocket-sized cousins of your calorimeter experiment.',
                'quiz': [
                    {
                        'q': 'The heat of neutralization for ANY strong acid + strong base is about −57.3 kJ/mol because…',
                        'options': ['All acids contain chlorine', 'The only real reaction is always H⁺ + OH⁻ → H₂O', 'Spectator ions release heat', 'All solutions have the same volume'],
                        'answer': 1,
                        'explain': 'Strong acids and bases are fully ionised, so whatever the spectator ions, the chemistry — and hence the heat — is identical.',
                    },
                    {
                        'q': 'A polystyrene cup is used as the calorimeter because it…',
                        'options': ['Conducts heat quickly', 'Is a good insulator with negligible heat capacity', 'Reacts with the acid', 'Is transparent'],
                        'answer': 1,
                        'explain': 'Insulation keeps the heat in the solution where the thermometer can count it; the cup itself absorbs almost none.',
                    },
                    {
                        'q': '50 mL of 1.0 M HCl + 50 mL of 1.0 M NaOH warms by 6.8 °C. q = mcΔT is about… (m = 100 g, c = 4.18)',
                        'options': ['284 J', '2842 J', '28 420 J', '684 J'],
                        'answer': 1,
                        'explain': 'q = 100 × 4.18 × 6.8 ≈ 2842 J. Divided by 0.050 mol of water formed: ΔH ≈ −57 kJ/mol.',
                    },
                    {
                        'q': 'Ethanoic acid gives a smaller temperature rise than HCl because…',
                        'options': ['It is more concentrated', 'Part of the energy is consumed ionising the weak acid\'s intact molecules', 'It contains no hydrogen', 'Its molecules are heavier'],
                        'answer': 1,
                        'explain': 'Weak acids are mostly un-ionised; the endothermic ionisation step subtracts from the −57.3 kJ/mol payout.',
                    },
                ],
            },
            {
                'slug': 'lassaigne-test',
                'title': "Lassaigne's Test: N, S & Halogens",
                'icon': 'join_inner',
                'minutes': 18,
                'sim': 'nebchemistry/lassaigne-test',
                'sim_type': '3d',
                'summary': 'Fuse an unknown organic compound with sodium metal, prepare the sodium extract, and run the classic detective tests — Prussian blue for nitrogen, violet nitroprusside for sulphur, silver halide precipitates for Cl and Br.',
                'objectives': [
                    'Explain why sodium fusion is needed before testing organic compounds for N, S and halogens',
                    'Describe the preparation of the sodium extract (fusion filtrate)',
                    'Perform and interpret the Prussian blue test for nitrogen',
                    'Perform the nitroprusside test for sulphur and the AgNO₃ test for halogens',
                    'Explain why the extract is boiled with HNO₃ before the halogen test',
                ],
                'knowledge': [
                    {
                        'heading': 'Why fusion first: covalent to ionic',
                        'body': 'Nitrogen, sulphur and halogens in organic compounds are bound covalently — locked inside molecules where ionic test reagents simply cannot see them. Add AgNO₃ to chloroform and nothing happens, despite three chlorines per molecule. Lassaigne\'s insight (1843): destroy the molecule and capture the elements as simple ions. A pea-sized piece of sodium is heated to red heat with the compound in a small ignition tube; the violent reduction converts nitrogen to NaCN, sulphur to Na₂S, halogens to NaX. If both N and S are present, NaSCN (sodium thiocyanate) can form too.\n\nThe red-hot tube is then plunged into distilled water in a china dish — it shatters, excess sodium is destroyed, and the ionic products dissolve. Boiling and filtering gives the clear sodium extract (fusion filtrate), the solution on which every subsequent test is run. The fusion must reach true red heat: incomplete fusion is the single commonest cause of false negatives.',
                    },
                    {
                        'heading': 'Prussian blue and the violet of sulphur',
                        'body': 'Nitrogen test: to a portion of the extract add freshly prepared FeSO₄ solution and boil — Fe²⁺ combines with cyanide to form sodium ferrocyanide: 6NaCN + FeSO₄ → Na₄[Fe(CN)₆] + Na₂SO₄. Cool, add a little FeCl₃ and acidify with concentrated HCl: ferric ions meet ferrocyanide and the deep Prussian blue of Fe₄[Fe(CN)₆]₃ appears. The acid dissolves the dirty iron hydroxides so the blue shows cleanly.\n\nSulphur test: to a fresh portion add a few drops of sodium nitroprusside solution. Sulphide ion converts the reagent into the intensely violet complex Na₄[Fe(CN)₅NOS] — instant and unmistakable. (A backup test: acidify with acetic acid and add lead acetate — a black precipitate of PbS also confirms sulphur.) If nitrogen and sulphur occur together, the extract may contain thiocyanate, which gives a blood-red colour with Fe³⁺ instead of Prussian blue — a famous interpretive trap.',
                    },
                    {
                        'heading': 'Halogens — after destroying the interference',
                        'body': 'The halogen test looks easy: add AgNO₃, look for the precipitate — white AgCl (soluble in NH₄OH) for chloride, pale-yellow AgBr (sparingly soluble) for bromide, yellow AgI (insoluble) for iodide. But if the compound also contained N or S, the extract holds CN⁻ and S²⁻, and both form silver precipitates of their own — false positives waiting to happen.\n\nThe fix: boil the extract with dilute HNO₃ first. Boiling expels the interfering ions as volatile gases: CN⁻ leaves as HCN, S²⁻ as H₂S. Only then is AgNO₃ added, and any precipitate that remains is a genuine halide. The colour plus the ammonia-solubility behaviour identifies which halogen. This boil-first step is precisely the kind of "why do we do this?" detail the practical viva loves — and in the simulation, the test result will warn you about interference when N or S is present.',
                    },
                ],
                'fun_fact': 'Lassaigne\'s test is sensitive enough to detect the nitrogen in a few milligrams of urea — a compound from urine whose synthesis by Wöhler in 1828, the year before Lassaigne\'s method, destroyed the idea that organic chemicals needed a "life force" to make.',
                'quiz': [
                    {
                        'q': 'The organic compound is fused with sodium in order to…',
                        'options': ['Burn away the carbon', 'Convert covalently bound N, S and halogens into ionic NaCN, Na₂S and NaX', 'Dry the compound', 'Make it dissolve in ether'],
                        'answer': 1,
                        'explain': 'Ionic reagent tests only see ions. Sodium fusion smashes the molecule and traps the elements as simple, testable sodium salts.',
                    },
                    {
                        'q': 'Prussian blue colour in the nitrogen test is the compound…',
                        'options': ['NaCN', 'Na₄[Fe(CN)₆]', 'Fe₄[Fe(CN)₆]₃', 'FeSO₄'],
                        'answer': 2,
                        'explain': 'CN⁻ first forms ferrocyanide with Fe²⁺; added Fe³⁺ then gives ferric ferrocyanide — Prussian blue.',
                    },
                    {
                        'q': 'Sodium nitroprusside added to the extract gives a violet colour when the compound contains…',
                        'options': ['Nitrogen', 'Sulphur', 'Chlorine', 'Oxygen'],
                        'answer': 1,
                        'explain': 'S²⁻ converts nitroprusside into the violet [Fe(CN)₅NOS]⁴⁻ complex — the signature sulphur positive.',
                    },
                    {
                        'q': 'Before the AgNO₃ halogen test, the extract is boiled with dilute HNO₃ to…',
                        'options': ['Make it more concentrated', 'Expel CN⁻ and S²⁻, which would give false silver precipitates', 'Dissolve the silver', 'Neutralise the sodium'],
                        'answer': 1,
                        'explain': 'Cyanide and sulphide leave as volatile HCN and H₂S on boiling, so any remaining precipitate with AgNO₃ is a genuine halide.',
                    },
                ],
            },
        ],
    },
]
