#!/usr/bin/env python3
"""Flatten the CSS `@import` entry points into single files.

`material3.css` and `app.css` used to be four hundred bytes of `@import` each.
That is a pleasant way to organise source and an expensive way to ship it: the
browser cannot even discover the eighteen real stylesheets until the entry file
has arrived and been parsed, so every visitor paid an extra serial round trip
before the first byte of anything that actually styles the page. Render-blocking
round trips are the most expensive kind.

The `@import` lists survive as `material3.src.css` and `app.src.css`, which is
where the order is declared and where edits belong. This script concatenates
them into the files the templates link. Modules themselves are untouched.

    tools/css/bundle.py           # rebuild
    tools/css/bundle.py --check   # fail if the bundles are stale

The bundles are checked in, so nothing rebuilds them at deploy time; change a
module and you must re-run this, exactly like tools/art.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
CSS = os.path.join(ROOT, "backend_python/web/static/web/css")

ENTRIES = ["material3", "app"]
IMPORT = re.compile(r'^@import\s+url\("([^"]+)"\);\s*$')

BANNER = (
    "/* GENERATED by tools/css/bundle.py from %s.src.css -- do not edit.\n"
    "   Edit the module under %s/ and re-run the script. */\n"
)


def build(name):
    src_path = os.path.join(CSS, name + ".src.css")
    with open(src_path, encoding="utf-8") as f:
        src = f.read()

    out = [BANNER % (name, name)]
    seen = []
    for line in src.splitlines():
        line = line.rstrip()
        if not line or line.lstrip().startswith("/*") or line.lstrip().startswith("*"):
            continue
        m = IMPORT.match(line.strip())
        if not m:
            raise SystemExit("%s: not an @import line: %r" % (src_path, line))
        rel = m.group(1)
        seen.append(rel)
        with open(os.path.join(CSS, rel), encoding="utf-8") as f:
            body = f.read()
        out.append("\n/* ---- %s ---- */\n%s" % (rel, body.rstrip() + "\n"))
    return "".join(out), seen


def main():
    check = "--check" in sys.argv
    stale = []
    for name in ENTRIES:
        text, modules = build(name)
        path = os.path.join(CSS, name + ".css")
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current == text:
            status = "up to date"
        elif check:
            stale.append(name)
            status = "STALE"
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            status = "written"
        print("%-10s %2d module(s)  %7d bytes  %s"
              % (name + ".css", len(modules), len(text.encode("utf-8")), status))
    if stale:
        raise SystemExit("stale bundle(s): %s -- run tools/css/bundle.py"
                         % ", ".join(stale))


if __name__ == "__main__":
    main()
